// Code generated by ent, DO NOT EDIT.

package course

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the course type in the database.
	Label = "course"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldShortDescription holds the string denoting the short_description field in the database.
	FieldShortDescription = "short_description"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldWhatYouWillLearn holds the string denoting the what_you_will_learn field in the database.
	FieldWhatYouWillLearn = "what_you_will_learn"
	// FieldRequirements holds the string denoting the requirements field in the database.
	FieldRequirements = "requirements"
	// FieldTargetAudience holds the string denoting the target_audience field in the database.
	FieldTargetAudience = "target_audience"
	// FieldThumbnail holds the string denoting the thumbnail field in the database.
	FieldThumbnail = "thumbnail"
	// FieldPromoVideoLink holds the string denoting the promo_video_link field in the database.
	FieldPromoVideoLink = "promo_video_url"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldIsFree holds the string denoting the is_free field in the database.
	FieldIsFree = "is_free"
	// FieldIsPublished holds the string denoting the is_published field in the database.
	FieldIsPublished = "is_published"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldTotalLectures holds the string denoting the total_lectures field in the database.
	FieldTotalLectures = "total_lectures"
	// FieldAverageRating holds the string denoting the average_rating field in the database.
	FieldAverageRating = "average_rating"
	// FieldNumberOfReviews holds the string denoting the number_of_reviews field in the database.
	FieldNumberOfReviews = "number_of_reviews"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeInstructor holds the string denoting the instructor edge name in mutations.
	EdgeInstructor = "instructor"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeLessons holds the string denoting the lessons edge name in mutations.
	EdgeLessons = "lessons"
	// EdgeEnrollments holds the string denoting the enrollments edge name in mutations.
	EdgeEnrollments = "enrollments"
	// EdgeReviews holds the string denoting the reviews edge name in mutations.
	EdgeReviews = "reviews"
	// EdgeEnrolledStudents holds the string denoting the enrolled_students edge name in mutations.
	EdgeEnrolledStudents = "enrolled_students"
	// EdgeCompletedStudents holds the string denoting the completed_students edge name in mutations.
	EdgeCompletedStudents = "completed_students"
	// Table holds the table name of the course in the database.
	Table = "courses_course"
	// InstructorTable is the table that holds the instructor relation/edge.
	InstructorTable = "courses_course"
	// InstructorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InstructorInverseTable = "Account_customuser"
	// InstructorColumn is the table column denoting the instructor relation/edge.
	InstructorColumn = "user_taught_courses"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "courses_course"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "Category_category"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_courses"
	// LessonsTable is the table that holds the lessons relation/edge.
	LessonsTable = "Lesson_lesson"
	// LessonsInverseTable is the table name for the Lesson entity.
	// It exists in this package in order to avoid circular dependency with the "lesson" package.
	LessonsInverseTable = "Lesson_lesson"
	// LessonsColumn is the table column denoting the lessons relation/edge.
	LessonsColumn = "course_lessons"
	// EnrollmentsTable is the table that holds the enrollments relation/edge.
	EnrollmentsTable = "Enrollment_enrollment"
	// EnrollmentsInverseTable is the table name for the Enrollment entity.
	// It exists in this package in order to avoid circular dependency with the "enrollment" package.
	EnrollmentsInverseTable = "Enrollment_enrollment"
	// EnrollmentsColumn is the table column denoting the enrollments relation/edge.
	EnrollmentsColumn = "course_id"
	// ReviewsTable is the table that holds the reviews relation/edge.
	ReviewsTable = "Review_review"
	// ReviewsInverseTable is the table name for the Review entity.
	// It exists in this package in order to avoid circular dependency with the "review" package.
	ReviewsInverseTable = "Review_review"
	// ReviewsColumn is the table column denoting the reviews relation/edge.
	ReviewsColumn = "course_reviews"
	// EnrolledStudentsTable is the table that holds the enrolled_students relation/edge. The primary key declared below.
	EnrolledStudentsTable = "user_enrolled_courses"
	// EnrolledStudentsInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	EnrolledStudentsInverseTable = "Account_customuser"
	// CompletedStudentsTable is the table that holds the completed_students relation/edge. The primary key declared below.
	CompletedStudentsTable = "user_completed_courses"
	// CompletedStudentsInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CompletedStudentsInverseTable = "Account_customuser"
)

// Columns holds all SQL columns for course fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldSlug,
	FieldShortDescription,
	FieldDescription,
	FieldWhatYouWillLearn,
	FieldRequirements,
	FieldTargetAudience,
	FieldThumbnail,
	FieldPromoVideoLink,
	FieldPrice,
	FieldIsFree,
	FieldIsPublished,
	FieldLevel,
	FieldDuration,
	FieldTotalLectures,
	FieldAverageRating,
	FieldNumberOfReviews,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "courses_course"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"category_courses",
	"user_taught_courses",
}

var (
	// EnrolledStudentsPrimaryKey and EnrolledStudentsColumn2 are the table columns denoting the
	// primary key for the enrolled_students relation (M2M).
	EnrolledStudentsPrimaryKey = []string{"user_id", "course_id"}
	// CompletedStudentsPrimaryKey and CompletedStudentsColumn2 are the table columns denoting the
	// primary key for the completed_students relation (M2M).
	CompletedStudentsPrimaryKey = []string{"user_id", "course_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// ShortDescriptionValidator is a validator for the "short_description" field. It is called by the builders before save.
	ShortDescriptionValidator func(string) error
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultIsFree holds the default value on creation for the "is_free" field.
	DefaultIsFree bool
	// DefaultIsPublished holds the default value on creation for the "is_published" field.
	DefaultIsPublished bool
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel string
	// DefaultTotalLectures holds the default value on creation for the "total_lectures" field.
	DefaultTotalLectures int
	// DefaultAverageRating holds the default value on creation for the "average_rating" field.
	DefaultAverageRating float64
	// DefaultNumberOfReviews holds the default value on creation for the "number_of_reviews" field.
	DefaultNumberOfReviews int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Course queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByShortDescription orders the results by the short_description field.
func ByShortDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShortDescription, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByWhatYouWillLearn orders the results by the what_you_will_learn field.
func ByWhatYouWillLearn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWhatYouWillLearn, opts...).ToFunc()
}

// ByRequirements orders the results by the requirements field.
func ByRequirements(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequirements, opts...).ToFunc()
}

// ByTargetAudience orders the results by the target_audience field.
func ByTargetAudience(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetAudience, opts...).ToFunc()
}

// ByThumbnail orders the results by the thumbnail field.
func ByThumbnail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnail, opts...).ToFunc()
}

// ByPromoVideoLink orders the results by the promo_video_link field.
func ByPromoVideoLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromoVideoLink, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByIsFree orders the results by the is_free field.
func ByIsFree(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsFree, opts...).ToFunc()
}

// ByIsPublished orders the results by the is_published field.
func ByIsPublished(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPublished, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByDuration orders the results by the duration field.
func ByDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuration, opts...).ToFunc()
}

// ByTotalLectures orders the results by the total_lectures field.
func ByTotalLectures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalLectures, opts...).ToFunc()
}

// ByAverageRating orders the results by the average_rating field.
func ByAverageRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAverageRating, opts...).ToFunc()
}

// ByNumberOfReviews orders the results by the number_of_reviews field.
func ByNumberOfReviews(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumberOfReviews, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByInstructorField orders the results by instructor field.
func ByInstructorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInstructorStep(), sql.OrderByField(field, opts...))
	}
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByLessonsCount orders the results by lessons count.
func ByLessonsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLessonsStep(), opts...)
	}
}

// ByLessons orders the results by lessons terms.
func ByLessons(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLessonsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEnrollmentsCount orders the results by enrollments count.
func ByEnrollmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEnrollmentsStep(), opts...)
	}
}

// ByEnrollments orders the results by enrollments terms.
func ByEnrollments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnrollmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReviewsCount orders the results by reviews count.
func ByReviewsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReviewsStep(), opts...)
	}
}

// ByReviews orders the results by reviews terms.
func ByReviews(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEnrolledStudentsCount orders the results by enrolled_students count.
func ByEnrolledStudentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEnrolledStudentsStep(), opts...)
	}
}

// ByEnrolledStudents orders the results by enrolled_students terms.
func ByEnrolledStudents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnrolledStudentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCompletedStudentsCount orders the results by completed_students count.
func ByCompletedStudentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCompletedStudentsStep(), opts...)
	}
}

// ByCompletedStudents orders the results by completed_students terms.
func ByCompletedStudents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompletedStudentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newInstructorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InstructorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InstructorTable, InstructorColumn),
	)
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
func newLessonsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LessonsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LessonsTable, LessonsColumn),
	)
}
func newEnrollmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnrollmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EnrollmentsTable, EnrollmentsColumn),
	)
}
func newReviewsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReviewsTable, ReviewsColumn),
	)
}
func newEnrolledStudentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnrolledStudentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, EnrolledStudentsTable, EnrolledStudentsPrimaryKey...),
	)
}
func newCompletedStudentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompletedStudentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, CompletedStudentsTable, CompletedStudentsPrimaryKey...),
	)
}
