// Code generated by ent, DO NOT EDIT.

package course

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SHP-Association/E-learningWeb/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTitle, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldSlug, v))
}

// ShortDescription applies equality check predicate on the "short_description" field. It's identical to ShortDescriptionEQ.
func ShortDescription(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldShortDescription, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldDescription, v))
}

// WhatYouWillLearn applies equality check predicate on the "what_you_will_learn" field. It's identical to WhatYouWillLearnEQ.
func WhatYouWillLearn(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldWhatYouWillLearn, v))
}

// Requirements applies equality check predicate on the "requirements" field. It's identical to RequirementsEQ.
func Requirements(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldRequirements, v))
}

// TargetAudience applies equality check predicate on the "target_audience" field. It's identical to TargetAudienceEQ.
func TargetAudience(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTargetAudience, v))
}

// Thumbnail applies equality check predicate on the "thumbnail" field. It's identical to ThumbnailEQ.
func Thumbnail(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldThumbnail, v))
}

// PromoVideoURL applies equality check predicate on the "promo_video_url" field. It's identical to PromoVideoURLEQ.
func PromoVideoURL(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldPromoVideoURL, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldPrice, v))
}

// IsFree applies equality check predicate on the "is_free" field. It's identical to IsFreeEQ.
func IsFree(v bool) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldIsFree, v))
}

// IsPublished applies equality check predicate on the "is_published" field. It's identical to IsPublishedEQ.
func IsPublished(v bool) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldIsPublished, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldLevel, v))
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldDuration, v))
}

// TotalLectures applies equality check predicate on the "total_lectures" field. It's identical to TotalLecturesEQ.
func TotalLectures(v int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTotalLectures, v))
}

// AverageRating applies equality check predicate on the "average_rating" field. It's identical to AverageRatingEQ.
func AverageRating(v float64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldAverageRating, v))
}

// NumberOfReviews applies equality check predicate on the "number_of_reviews" field. It's identical to NumberOfReviewsEQ.
func NumberOfReviews(v int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldNumberOfReviews, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldTitle, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldSlug, v))
}

// ShortDescriptionEQ applies the EQ predicate on the "short_description" field.
func ShortDescriptionEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldShortDescription, v))
}

// ShortDescriptionNEQ applies the NEQ predicate on the "short_description" field.
func ShortDescriptionNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldShortDescription, v))
}

// ShortDescriptionIn applies the In predicate on the "short_description" field.
func ShortDescriptionIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldShortDescription, vs...))
}

// ShortDescriptionNotIn applies the NotIn predicate on the "short_description" field.
func ShortDescriptionNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldShortDescription, vs...))
}

// ShortDescriptionGT applies the GT predicate on the "short_description" field.
func ShortDescriptionGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldShortDescription, v))
}

// ShortDescriptionGTE applies the GTE predicate on the "short_description" field.
func ShortDescriptionGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldShortDescription, v))
}

// ShortDescriptionLT applies the LT predicate on the "short_description" field.
func ShortDescriptionLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldShortDescription, v))
}

// ShortDescriptionLTE applies the LTE predicate on the "short_description" field.
func ShortDescriptionLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldShortDescription, v))
}

// ShortDescriptionContains applies the Contains predicate on the "short_description" field.
func ShortDescriptionContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldShortDescription, v))
}

// ShortDescriptionHasPrefix applies the HasPrefix predicate on the "short_description" field.
func ShortDescriptionHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldShortDescription, v))
}

// ShortDescriptionHasSuffix applies the HasSuffix predicate on the "short_description" field.
func ShortDescriptionHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldShortDescription, v))
}

// ShortDescriptionEqualFold applies the EqualFold predicate on the "short_description" field.
func ShortDescriptionEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldShortDescription, v))
}

// ShortDescriptionContainsFold applies the ContainsFold predicate on the "short_description" field.
func ShortDescriptionContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldShortDescription, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldDescription, v))
}

// WhatYouWillLearnEQ applies the EQ predicate on the "what_you_will_learn" field.
func WhatYouWillLearnEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnNEQ applies the NEQ predicate on the "what_you_will_learn" field.
func WhatYouWillLearnNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnIn applies the In predicate on the "what_you_will_learn" field.
func WhatYouWillLearnIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldWhatYouWillLearn, vs...))
}

// WhatYouWillLearnNotIn applies the NotIn predicate on the "what_you_will_learn" field.
func WhatYouWillLearnNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldWhatYouWillLearn, vs...))
}

// WhatYouWillLearnGT applies the GT predicate on the "what_you_will_learn" field.
func WhatYouWillLearnGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnGTE applies the GTE predicate on the "what_you_will_learn" field.
func WhatYouWillLearnGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnLT applies the LT predicate on the "what_you_will_learn" field.
func WhatYouWillLearnLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnLTE applies the LTE predicate on the "what_you_will_learn" field.
func WhatYouWillLearnLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnContains applies the Contains predicate on the "what_you_will_learn" field.
func WhatYouWillLearnContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnHasPrefix applies the HasPrefix predicate on the "what_you_will_learn" field.
func WhatYouWillLearnHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnHasSuffix applies the HasSuffix predicate on the "what_you_will_learn" field.
func WhatYouWillLearnHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnIsNil applies the IsNil predicate on the "what_you_will_learn" field.
func WhatYouWillLearnIsNil() predicate.Course {
	return predicate.Course(sql.FieldIsNull(FieldWhatYouWillLearn))
}

// WhatYouWillLearnNotNil applies the NotNil predicate on the "what_you_will_learn" field.
func WhatYouWillLearnNotNil() predicate.Course {
	return predicate.Course(sql.FieldNotNull(FieldWhatYouWillLearn))
}

// WhatYouWillLearnEqualFold applies the EqualFold predicate on the "what_you_will_learn" field.
func WhatYouWillLearnEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldWhatYouWillLearn, v))
}

// WhatYouWillLearnContainsFold applies the ContainsFold predicate on the "what_you_will_learn" field.
func WhatYouWillLearnContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldWhatYouWillLearn, v))
}

// RequirementsEQ applies the EQ predicate on the "requirements" field.
func RequirementsEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldRequirements, v))
}

// RequirementsNEQ applies the NEQ predicate on the "requirements" field.
func RequirementsNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldRequirements, v))
}

// RequirementsIn applies the In predicate on the "requirements" field.
func RequirementsIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldRequirements, vs...))
}

// RequirementsNotIn applies the NotIn predicate on the "requirements" field.
func RequirementsNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldRequirements, vs...))
}

// RequirementsGT applies the GT predicate on the "requirements" field.
func RequirementsGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldRequirements, v))
}

// RequirementsGTE applies the GTE predicate on the "requirements" field.
func RequirementsGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldRequirements, v))
}

// RequirementsLT applies the LT predicate on the "requirements" field.
func RequirementsLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldRequirements, v))
}

// RequirementsLTE applies the LTE predicate on the "requirements" field.
func RequirementsLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldRequirements, v))
}

// RequirementsContains applies the Contains predicate on the "requirements" field.
func RequirementsContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldRequirements, v))
}

// RequirementsHasPrefix applies the HasPrefix predicate on the "requirements" field.
func RequirementsHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldRequirements, v))
}

// RequirementsHasSuffix applies the HasSuffix predicate on the "requirements" field.
func RequirementsHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldRequirements, v))
}

// RequirementsIsNil applies the IsNil predicate on the "requirements" field.
func RequirementsIsNil() predicate.Course {
	return predicate.Course(sql.FieldIsNull(FieldRequirements))
}

// RequirementsNotNil applies the NotNil predicate on the "requirements" field.
func RequirementsNotNil() predicate.Course {
	return predicate.Course(sql.FieldNotNull(FieldRequirements))
}

// RequirementsEqualFold applies the EqualFold predicate on the "requirements" field.
func RequirementsEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldRequirements, v))
}

// RequirementsContainsFold applies the ContainsFold predicate on the "requirements" field.
func RequirementsContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldRequirements, v))
}

// TargetAudienceEQ applies the EQ predicate on the "target_audience" field.
func TargetAudienceEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTargetAudience, v))
}

// TargetAudienceNEQ applies the NEQ predicate on the "target_audience" field.
func TargetAudienceNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldTargetAudience, v))
}

// TargetAudienceIn applies the In predicate on the "target_audience" field.
func TargetAudienceIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldTargetAudience, vs...))
}

// TargetAudienceNotIn applies the NotIn predicate on the "target_audience" field.
func TargetAudienceNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldTargetAudience, vs...))
}

// TargetAudienceGT applies the GT predicate on the "target_audience" field.
func TargetAudienceGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldTargetAudience, v))
}

// TargetAudienceGTE applies the GTE predicate on the "target_audience" field.
func TargetAudienceGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldTargetAudience, v))
}

// TargetAudienceLT applies the LT predicate on the "target_audience" field.
func TargetAudienceLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldTargetAudience, v))
}

// TargetAudienceLTE applies the LTE predicate on the "target_audience" field.
func TargetAudienceLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldTargetAudience, v))
}

// TargetAudienceContains applies the Contains predicate on the "target_audience" field.
func TargetAudienceContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldTargetAudience, v))
}

// TargetAudienceHasPrefix applies the HasPrefix predicate on the "target_audience" field.
func TargetAudienceHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldTargetAudience, v))
}

// TargetAudienceHasSuffix applies the HasSuffix predicate on the "target_audience" field.
func TargetAudienceHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldTargetAudience, v))
}

// TargetAudienceIsNil applies the IsNil predicate on the "target_audience" field.
func TargetAudienceIsNil() predicate.Course {
	return predicate.Course(sql.FieldIsNull(FieldTargetAudience))
}

// TargetAudienceNotNil applies the NotNil predicate on the "target_audience" field.
func TargetAudienceNotNil() predicate.Course {
	return predicate.Course(sql.FieldNotNull(FieldTargetAudience))
}

// TargetAudienceEqualFold applies the EqualFold predicate on the "target_audience" field.
func TargetAudienceEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldTargetAudience, v))
}

// TargetAudienceContainsFold applies the ContainsFold predicate on the "target_audience" field.
func TargetAudienceContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldTargetAudience, v))
}

// ThumbnailEQ applies the EQ predicate on the "thumbnail" field.
func ThumbnailEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldThumbnail, v))
}

// ThumbnailNEQ applies the NEQ predicate on the "thumbnail" field.
func ThumbnailNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldThumbnail, v))
}

// ThumbnailIn applies the In predicate on the "thumbnail" field.
func ThumbnailIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldThumbnail, vs...))
}

// ThumbnailNotIn applies the NotIn predicate on the "thumbnail" field.
func ThumbnailNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldThumbnail, vs...))
}

// ThumbnailGT applies the GT predicate on the "thumbnail" field.
func ThumbnailGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldThumbnail, v))
}

// ThumbnailGTE applies the GTE predicate on the "thumbnail" field.
func ThumbnailGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldThumbnail, v))
}

// ThumbnailLT applies the LT predicate on the "thumbnail" field.
func ThumbnailLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldThumbnail, v))
}

// ThumbnailLTE applies the LTE predicate on the "thumbnail" field.
func ThumbnailLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldThumbnail, v))
}

// ThumbnailContains applies the Contains predicate on the "thumbnail" field.
func ThumbnailContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldThumbnail, v))
}

// ThumbnailHasPrefix applies the HasPrefix predicate on the "thumbnail" field.
func ThumbnailHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldThumbnail, v))
}

// ThumbnailHasSuffix applies the HasSuffix predicate on the "thumbnail" field.
func ThumbnailHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldThumbnail, v))
}

// ThumbnailIsNil applies the IsNil predicate on the "thumbnail" field.
func ThumbnailIsNil() predicate.Course {
	return predicate.Course(sql.FieldIsNull(FieldThumbnail))
}

// ThumbnailNotNil applies the NotNil predicate on the "thumbnail" field.
func ThumbnailNotNil() predicate.Course {
	return predicate.Course(sql.FieldNotNull(FieldThumbnail))
}

// ThumbnailEqualFold applies the EqualFold predicate on the "thumbnail" field.
func ThumbnailEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldThumbnail, v))
}

// ThumbnailContainsFold applies the ContainsFold predicate on the "thumbnail" field.
func ThumbnailContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldThumbnail, v))
}

// PromoVideoURLEQ applies the EQ predicate on the "promo_video_url" field.
func PromoVideoURLEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldPromoVideoURL, v))
}

// PromoVideoURLNEQ applies the NEQ predicate on the "promo_video_url" field.
func PromoVideoURLNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldPromoVideoURL, v))
}

// PromoVideoURLIn applies the In predicate on the "promo_video_url" field.
func PromoVideoURLIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldPromoVideoURL, vs...))
}

// PromoVideoURLNotIn applies the NotIn predicate on the "promo_video_url" field.
func PromoVideoURLNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldPromoVideoURL, vs...))
}

// PromoVideoURLGT applies the GT predicate on the "promo_video_url" field.
func PromoVideoURLGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldPromoVideoURL, v))
}

// PromoVideoURLGTE applies the GTE predicate on the "promo_video_url" field.
func PromoVideoURLGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldPromoVideoURL, v))
}

// PromoVideoURLLT applies the LT predicate on the "promo_video_url" field.
func PromoVideoURLLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldPromoVideoURL, v))
}

// PromoVideoURLLTE applies the LTE predicate on the "promo_video_url" field.
func PromoVideoURLLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldPromoVideoURL, v))
}

// PromoVideoURLContains applies the Contains predicate on the "promo_video_url" field.
func PromoVideoURLContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldPromoVideoURL, v))
}

// PromoVideoURLHasPrefix applies the HasPrefix predicate on the "promo_video_url" field.
func PromoVideoURLHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldPromoVideoURL, v))
}

// PromoVideoURLHasSuffix applies the HasSuffix predicate on the "promo_video_url" field.
func PromoVideoURLHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldPromoVideoURL, v))
}

// PromoVideoURLIsNil applies the IsNil predicate on the "promo_video_url" field.
func PromoVideoURLIsNil() predicate.Course {
	return predicate.Course(sql.FieldIsNull(FieldPromoVideoURL))
}

// PromoVideoURLNotNil applies the NotNil predicate on the "promo_video_url" field.
func PromoVideoURLNotNil() predicate.Course {
	return predicate.Course(sql.FieldNotNull(FieldPromoVideoURL))
}

// PromoVideoURLEqualFold applies the EqualFold predicate on the "promo_video_url" field.
func PromoVideoURLEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldPromoVideoURL, v))
}

// PromoVideoURLContainsFold applies the ContainsFold predicate on the "promo_video_url" field.
func PromoVideoURLContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldPromoVideoURL, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldPrice, v))
}

// IsFreeEQ applies the EQ predicate on the "is_free" field.
func IsFreeEQ(v bool) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldIsFree, v))
}

// IsFreeNEQ applies the NEQ predicate on the "is_free" field.
func IsFreeNEQ(v bool) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldIsFree, v))
}

// IsPublishedEQ applies the EQ predicate on the "is_published" field.
func IsPublishedEQ(v bool) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldIsPublished, v))
}

// IsPublishedNEQ applies the NEQ predicate on the "is_published" field.
func IsPublishedNEQ(v bool) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldIsPublished, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldLevel, v))
}

// LevelContains applies the Contains predicate on the "level" field.
func LevelContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldLevel, v))
}

// LevelHasPrefix applies the HasPrefix predicate on the "level" field.
func LevelHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldLevel, v))
}

// LevelHasSuffix applies the HasSuffix predicate on the "level" field.
func LevelHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldLevel, v))
}

// LevelEqualFold applies the EqualFold predicate on the "level" field.
func LevelEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldLevel, v))
}

// LevelContainsFold applies the ContainsFold predicate on the "level" field.
func LevelContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldLevel, v))
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldDuration, v))
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldDuration, v))
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldDuration, vs...))
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldDuration, vs...))
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldDuration, v))
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldDuration, v))
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldDuration, v))
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldDuration, v))
}

// DurationContains applies the Contains predicate on the "duration" field.
func DurationContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldDuration, v))
}

// DurationHasPrefix applies the HasPrefix predicate on the "duration" field.
func DurationHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldDuration, v))
}

// DurationHasSuffix applies the HasSuffix predicate on the "duration" field.
func DurationHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldDuration, v))
}

// DurationIsNil applies the IsNil predicate on the "duration" field.
func DurationIsNil() predicate.Course {
	return predicate.Course(sql.FieldIsNull(FieldDuration))
}

// DurationNotNil applies the NotNil predicate on the "duration" field.
func DurationNotNil() predicate.Course {
	return predicate.Course(sql.FieldNotNull(FieldDuration))
}

// DurationEqualFold applies the EqualFold predicate on the "duration" field.
func DurationEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldDuration, v))
}

// DurationContainsFold applies the ContainsFold predicate on the "duration" field.
func DurationContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldDuration, v))
}

// TotalLecturesEQ applies the EQ predicate on the "total_lectures" field.
func TotalLecturesEQ(v int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTotalLectures, v))
}

// TotalLecturesNEQ applies the NEQ predicate on the "total_lectures" field.
func TotalLecturesNEQ(v int) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldTotalLectures, v))
}

// TotalLecturesIn applies the In predicate on the "total_lectures" field.
func TotalLecturesIn(vs ...int) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldTotalLectures, vs...))
}

// TotalLecturesNotIn applies the NotIn predicate on the "total_lectures" field.
func TotalLecturesNotIn(vs ...int) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldTotalLectures, vs...))
}

// TotalLecturesGT applies the GT predicate on the "total_lectures" field.
func TotalLecturesGT(v int) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldTotalLectures, v))
}

// TotalLecturesGTE applies the GTE predicate on the "total_lectures" field.
func TotalLecturesGTE(v int) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldTotalLectures, v))
}

// TotalLecturesLT applies the LT predicate on the "total_lectures" field.
func TotalLecturesLT(v int) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldTotalLectures, v))
}

// TotalLecturesLTE applies the LTE predicate on the "total_lectures" field.
func TotalLecturesLTE(v int) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldTotalLectures, v))
}

// AverageRatingEQ applies the EQ predicate on the "average_rating" field.
func AverageRatingEQ(v float64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldAverageRating, v))
}

// AverageRatingNEQ applies the NEQ predicate on the "average_rating" field.
func AverageRatingNEQ(v float64) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldAverageRating, v))
}

// AverageRatingIn applies the In predicate on the "average_rating" field.
func AverageRatingIn(vs ...float64) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldAverageRating, vs...))
}

// AverageRatingNotIn applies the NotIn predicate on the "average_rating" field.
func AverageRatingNotIn(vs ...float64) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldAverageRating, vs...))
}

// AverageRatingGT applies the GT predicate on the "average_rating" field.
func AverageRatingGT(v float64) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldAverageRating, v))
}

// AverageRatingGTE applies the GTE predicate on the "average_rating" field.
func AverageRatingGTE(v float64) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldAverageRating, v))
}

// AverageRatingLT applies the LT predicate on the "average_rating" field.
func AverageRatingLT(v float64) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldAverageRating, v))
}

// AverageRatingLTE applies the LTE predicate on the "average_rating" field.
func AverageRatingLTE(v float64) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldAverageRating, v))
}

// NumberOfReviewsEQ applies the EQ predicate on the "number_of_reviews" field.
func NumberOfReviewsEQ(v int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldNumberOfReviews, v))
}

// NumberOfReviewsNEQ applies the NEQ predicate on the "number_of_reviews" field.
func NumberOfReviewsNEQ(v int) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldNumberOfReviews, v))
}

// NumberOfReviewsIn applies the In predicate on the "number_of_reviews" field.
func NumberOfReviewsIn(vs ...int) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldNumberOfReviews, vs...))
}

// NumberOfReviewsNotIn applies the NotIn predicate on the "number_of_reviews" field.
func NumberOfReviewsNotIn(vs ...int) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldNumberOfReviews, vs...))
}

// NumberOfReviewsGT applies the GT predicate on the "number_of_reviews" field.
func NumberOfReviewsGT(v int) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldNumberOfReviews, v))
}

// NumberOfReviewsGTE applies the GTE predicate on the "number_of_reviews" field.
func NumberOfReviewsGTE(v int) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldNumberOfReviews, v))
}

// NumberOfReviewsLT applies the LT predicate on the "number_of_reviews" field.
func NumberOfReviewsLT(v int) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldNumberOfReviews, v))
}

// NumberOfReviewsLTE applies the LTE predicate on the "number_of_reviews" field.
func NumberOfReviewsLTE(v int) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldNumberOfReviews, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasInstructor applies the HasEdge predicate on the "instructor" edge.
func HasInstructor() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InstructorTable, InstructorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstructorWith applies the HasEdge predicate on the "instructor" edge with a given conditions (other predicates).
func HasInstructorWith(preds ...predicate.User) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newInstructorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCategory applies the HasEdge predicate on the "category" edge.
func HasCategory() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoryWith applies the HasEdge predicate on the "category" edge with a given conditions (other predicates).
func HasCategoryWith(preds ...predicate.Category) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newCategoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLessons applies the HasEdge predicate on the "lessons" edge.
func HasLessons() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LessonsTable, LessonsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLessonsWith applies the HasEdge predicate on the "lessons" edge with a given conditions (other predicates).
func HasLessonsWith(preds ...predicate.Lesson) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newLessonsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEnrollments applies the HasEdge predicate on the "enrollments" edge.
func HasEnrollments() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EnrollmentsTable, EnrollmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnrollmentsWith applies the HasEdge predicate on the "enrollments" edge with a given conditions (other predicates).
func HasEnrollmentsWith(preds ...predicate.Enrollment) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newEnrollmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReviews applies the HasEdge predicate on the "reviews" edge.
func HasReviews() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReviewsTable, ReviewsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewsWith applies the HasEdge predicate on the "reviews" edge with a given conditions (other predicates).
func HasReviewsWith(preds ...predicate.Review) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newReviewsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEnrolledStudents applies the HasEdge predicate on the "enrolled_students" edge.
func HasEnrolledStudents() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, EnrolledStudentsTable, EnrolledStudentsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnrolledStudentsWith applies the HasEdge predicate on the "enrolled_students" edge with a given conditions (other predicates).
func HasEnrolledStudentsWith(preds ...predicate.User) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newEnrolledStudentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCompletedStudents applies the HasEdge predicate on the "completed_students" edge.
func HasCompletedStudents() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, CompletedStudentsTable, CompletedStudentsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompletedStudentsWith applies the HasEdge predicate on the "completed_students" edge with a given conditions (other predicates).
func HasCompletedStudentsWith(preds ...predicate.User) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newCompletedStudentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Course) predicate.Course {
	return predicate.Course(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Course) predicate.Course {
	return predicate.Course(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Course) predicate.Course {
	return predicate.Course(sql.NotPredicates(p))
}
