// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldBio holds the string denoting the bio field in the database.
	FieldBio = "bio"
	// FieldProfilePicture holds the string denoting the profile_picture field in the database.
	FieldProfilePicture = "profile_picture"
	// FieldDateOfBirth holds the string denoting the date_of_birth field in the database.
	FieldDateOfBirth = "date_of_birth"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldContactNumber holds the string denoting the contact_number field in the database.
	FieldContactNumber = "contact_number"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldIsEmailVerified holds the string denoting the is_email_verified field in the database.
	FieldIsEmailVerified = "is_email_verified"
	// FieldHighestQualification holds the string denoting the highest_qualification field in the database.
	FieldHighestQualification = "highest_qualification"
	// FieldInstitution holds the string denoting the institution field in the database.
	FieldInstitution = "institution"
	// FieldSkills holds the string denoting the skills field in the database.
	FieldSkills = "skills"
	// FieldLinkedinProfile holds the string denoting the linkedin_profile field in the database.
	FieldLinkedinProfile = "linkedin_profile"
	// FieldGithubProfile holds the string denoting the github_profile field in the database.
	FieldGithubProfile = "github_profile"
	// FieldInstructorRating holds the string denoting the instructor_rating field in the database.
	FieldInstructorRating = "instructor_rating"
	// FieldTotalReviews holds the string denoting the total_reviews field in the database.
	FieldTotalReviews = "total_reviews"
	// FieldIsActiveUser holds the string denoting the is_active_user field in the database.
	FieldIsActiveUser = "is_active_user"
	// FieldLastActivity holds the string denoting the last_activity field in the database.
	FieldLastActivity = "last_activity"
	// FieldLoginAddress holds the string denoting the login_address field in the database.
	FieldLoginAddress = "login_ip"
	// FieldTwoFactorEnabled holds the string denoting the two_factor_enabled field in the database.
	FieldTwoFactorEnabled = "two_factor_enabled"
	// FieldIsStaff holds the string denoting the is_staff field in the database.
	FieldIsStaff = "is_staff"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldIsSuperuser holds the string denoting the is_superuser field in the database.
	FieldIsSuperuser = "is_superuser"
	// FieldLastLogin holds the string denoting the last_login field in the database.
	FieldLastLogin = "last_login"
	// FieldDateJoined holds the string denoting the date_joined field in the database.
	FieldDateJoined = "date_joined"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldAdmin holds the string denoting the admin field in the database.
	FieldAdmin = "admin"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeTaughtCourses holds the string denoting the taught_courses edge name in mutations.
	EdgeTaughtCourses = "taught_courses"
	// EdgeQuizAttempts holds the string denoting the quiz_attempts edge name in mutations.
	EdgeQuizAttempts = "quiz_attempts"
	// EdgeEnrollments holds the string denoting the enrollments edge name in mutations.
	EdgeEnrollments = "enrollments"
	// EdgeReviewsGiven holds the string denoting the reviews_given edge name in mutations.
	EdgeReviewsGiven = "reviews_given"
	// EdgeEnrolledCourses holds the string denoting the enrolled_courses edge name in mutations.
	EdgeEnrolledCourses = "enrolled_courses"
	// EdgeCompletedCourses holds the string denoting the completed_courses edge name in mutations.
	EdgeCompletedCourses = "completed_courses"
	// Table holds the table name of the user in the database.
	Table = "Account_customuser"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "password_tokens"
	// OwnerInverseTable is the table name for the PasswordToken entity.
	// It exists in this package in order to avoid circular dependency with the "passwordtoken" package.
	OwnerInverseTable = "password_tokens"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
	// TaughtCoursesTable is the table that holds the taught_courses relation/edge.
	TaughtCoursesTable = "courses_course"
	// TaughtCoursesInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	TaughtCoursesInverseTable = "courses_course"
	// TaughtCoursesColumn is the table column denoting the taught_courses relation/edge.
	TaughtCoursesColumn = "user_taught_courses"
	// QuizAttemptsTable is the table that holds the quiz_attempts relation/edge.
	QuizAttemptsTable = "Quiz_userquizattempt"
	// QuizAttemptsInverseTable is the table name for the UserQuizAttempt entity.
	// It exists in this package in order to avoid circular dependency with the "userquizattempt" package.
	QuizAttemptsInverseTable = "Quiz_userquizattempt"
	// QuizAttemptsColumn is the table column denoting the quiz_attempts relation/edge.
	QuizAttemptsColumn = "user_quiz_attempts"
	// EnrollmentsTable is the table that holds the enrollments relation/edge.
	EnrollmentsTable = "Enrollment_enrollment"
	// EnrollmentsInverseTable is the table name for the Enrollment entity.
	// It exists in this package in order to avoid circular dependency with the "enrollment" package.
	EnrollmentsInverseTable = "Enrollment_enrollment"
	// EnrollmentsColumn is the table column denoting the enrollments relation/edge.
	EnrollmentsColumn = "user_enrollments"
	// ReviewsGivenTable is the table that holds the reviews_given relation/edge.
	ReviewsGivenTable = "Review_review"
	// ReviewsGivenInverseTable is the table name for the Review entity.
	// It exists in this package in order to avoid circular dependency with the "review" package.
	ReviewsGivenInverseTable = "Review_review"
	// ReviewsGivenColumn is the table column denoting the reviews_given relation/edge.
	ReviewsGivenColumn = "user_reviews_given"
	// EnrolledCoursesTable is the table that holds the enrolled_courses relation/edge. The primary key declared below.
	EnrolledCoursesTable = "user_enrolled_courses"
	// EnrolledCoursesInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	EnrolledCoursesInverseTable = "courses_course"
	// CompletedCoursesTable is the table that holds the completed_courses relation/edge. The primary key declared below.
	CompletedCoursesTable = "user_completed_courses"
	// CompletedCoursesInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	CompletedCoursesInverseTable = "courses_course"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldFirstName,
	FieldLastName,
	FieldEmail,
	FieldPassword,
	FieldRole,
	FieldBio,
	FieldProfilePicture,
	FieldDateOfBirth,
	FieldGender,
	FieldContactNumber,
	FieldAddress,
	FieldCountry,
	FieldIsEmailVerified,
	FieldHighestQualification,
	FieldInstitution,
	FieldSkills,
	FieldLinkedinProfile,
	FieldGithubProfile,
	FieldInstructorRating,
	FieldTotalReviews,
	FieldIsActiveUser,
	FieldLastActivity,
	FieldLoginAddress,
	FieldTwoFactorEnabled,
	FieldIsStaff,
	FieldIsActive,
	FieldIsSuperuser,
	FieldLastLogin,
	FieldDateJoined,
	FieldVerified,
	FieldAdmin,
	FieldCreatedAt,
}

var (
	// EnrolledCoursesPrimaryKey and EnrolledCoursesColumn2 are the table columns denoting the
	// primary key for the enrolled_courses relation (M2M).
	EnrolledCoursesPrimaryKey = []string{"user_id", "course_id"}
	// CompletedCoursesPrimaryKey and CompletedCoursesColumn2 are the table columns denoting the
	// primary key for the completed_courses relation (M2M).
	CompletedCoursesPrimaryKey = []string{"user_id", "course_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole string
	// DefaultIsEmailVerified holds the default value on creation for the "is_email_verified" field.
	DefaultIsEmailVerified bool
	// DefaultInstructorRating holds the default value on creation for the "instructor_rating" field.
	DefaultInstructorRating float64
	// DefaultTotalReviews holds the default value on creation for the "total_reviews" field.
	DefaultTotalReviews int
	// DefaultIsActiveUser holds the default value on creation for the "is_active_user" field.
	DefaultIsActiveUser bool
	// DefaultTwoFactorEnabled holds the default value on creation for the "two_factor_enabled" field.
	DefaultTwoFactorEnabled bool
	// DefaultIsStaff holds the default value on creation for the "is_staff" field.
	DefaultIsStaff bool
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultIsSuperuser holds the default value on creation for the "is_superuser" field.
	DefaultIsSuperuser bool
	// DefaultDateJoined holds the default value on creation for the "date_joined" field.
	DefaultDateJoined func() time.Time
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
	// DefaultAdmin holds the default value on creation for the "admin" field.
	DefaultAdmin bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByFirstName orders the results by the first_name field.
func ByFirstName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstName, opts...).ToFunc()
}

// ByLastName orders the results by the last_name field.
func ByLastName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByBio orders the results by the bio field.
func ByBio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBio, opts...).ToFunc()
}

// ByProfilePicture orders the results by the profile_picture field.
func ByProfilePicture(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfilePicture, opts...).ToFunc()
}

// ByDateOfBirth orders the results by the date_of_birth field.
func ByDateOfBirth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateOfBirth, opts...).ToFunc()
}

// ByGender orders the results by the gender field.
func ByGender(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGender, opts...).ToFunc()
}

// ByContactNumber orders the results by the contact_number field.
func ByContactNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactNumber, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByIsEmailVerified orders the results by the is_email_verified field.
func ByIsEmailVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEmailVerified, opts...).ToFunc()
}

// ByHighestQualification orders the results by the highest_qualification field.
func ByHighestQualification(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHighestQualification, opts...).ToFunc()
}

// ByInstitution orders the results by the institution field.
func ByInstitution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstitution, opts...).ToFunc()
}

// BySkills orders the results by the skills field.
func BySkills(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkills, opts...).ToFunc()
}

// ByLinkedinProfile orders the results by the linkedin_profile field.
func ByLinkedinProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkedinProfile, opts...).ToFunc()
}

// ByGithubProfile orders the results by the github_profile field.
func ByGithubProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubProfile, opts...).ToFunc()
}

// ByInstructorRating orders the results by the instructor_rating field.
func ByInstructorRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstructorRating, opts...).ToFunc()
}

// ByTotalReviews orders the results by the total_reviews field.
func ByTotalReviews(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalReviews, opts...).ToFunc()
}

// ByIsActiveUser orders the results by the is_active_user field.
func ByIsActiveUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActiveUser, opts...).ToFunc()
}

// ByLastActivity orders the results by the last_activity field.
func ByLastActivity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActivity, opts...).ToFunc()
}

// ByLoginAddress orders the results by the login_address field.
func ByLoginAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginAddress, opts...).ToFunc()
}

// ByTwoFactorEnabled orders the results by the two_factor_enabled field.
func ByTwoFactorEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTwoFactorEnabled, opts...).ToFunc()
}

// ByIsStaff orders the results by the is_staff field.
func ByIsStaff(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsStaff, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByIsSuperuser orders the results by the is_superuser field.
func ByIsSuperuser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSuperuser, opts...).ToFunc()
}

// ByLastLogin orders the results by the last_login field.
func ByLastLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLogin, opts...).ToFunc()
}

// ByDateJoined orders the results by the date_joined field.
func ByDateJoined(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateJoined, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByAdmin orders the results by the admin field.
func ByAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdmin, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByOwnerCount orders the results by owner count.
func ByOwnerCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOwnerStep(), opts...)
	}
}

// ByOwner orders the results by owner terms.
func ByOwner(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTaughtCoursesCount orders the results by taught_courses count.
func ByTaughtCoursesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaughtCoursesStep(), opts...)
	}
}

// ByTaughtCourses orders the results by taught_courses terms.
func ByTaughtCourses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaughtCoursesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByQuizAttemptsCount orders the results by quiz_attempts count.
func ByQuizAttemptsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuizAttemptsStep(), opts...)
	}
}

// ByQuizAttempts orders the results by quiz_attempts terms.
func ByQuizAttempts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuizAttemptsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEnrollmentsCount orders the results by enrollments count.
func ByEnrollmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEnrollmentsStep(), opts...)
	}
}

// ByEnrollments orders the results by enrollments terms.
func ByEnrollments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnrollmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReviewsGivenCount orders the results by reviews_given count.
func ByReviewsGivenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReviewsGivenStep(), opts...)
	}
}

// ByReviewsGiven orders the results by reviews_given terms.
func ByReviewsGiven(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewsGivenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEnrolledCoursesCount orders the results by enrolled_courses count.
func ByEnrolledCoursesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEnrolledCoursesStep(), opts...)
	}
}

// ByEnrolledCourses orders the results by enrolled_courses terms.
func ByEnrolledCourses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnrolledCoursesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCompletedCoursesCount orders the results by completed_courses count.
func ByCompletedCoursesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCompletedCoursesStep(), opts...)
	}
}

// ByCompletedCourses orders the results by completed_courses terms.
func ByCompletedCourses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompletedCoursesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, OwnerTable, OwnerColumn),
	)
}
func newTaughtCoursesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaughtCoursesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TaughtCoursesTable, TaughtCoursesColumn),
	)
}
func newQuizAttemptsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuizAttemptsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QuizAttemptsTable, QuizAttemptsColumn),
	)
}
func newEnrollmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnrollmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EnrollmentsTable, EnrollmentsColumn),
	)
}
func newReviewsGivenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewsGivenInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReviewsGivenTable, ReviewsGivenColumn),
	)
}
func newEnrolledCoursesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnrolledCoursesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, EnrolledCoursesTable, EnrolledCoursesPrimaryKey...),
	)
}
func newCompletedCoursesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompletedCoursesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, CompletedCoursesTable, CompletedCoursesPrimaryKey...),
	)
}
