// Code generated by ent, DO NOT EDIT.

package question

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the question type in the database.
	Label = "question"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuestionText holds the string denoting the question_text field in the database.
	FieldQuestionText = "question_text"
	// FieldQuestionType holds the string denoting the question_type field in the database.
	FieldQuestionType = "question_type"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// EdgeQuiz holds the string denoting the quiz edge name in mutations.
	EdgeQuiz = "quiz"
	// EdgeChoices holds the string denoting the choices edge name in mutations.
	EdgeChoices = "choices"
	// Table holds the table name of the question in the database.
	Table = "Question_question"
	// QuizTable is the table that holds the quiz relation/edge.
	QuizTable = "Question_question"
	// QuizInverseTable is the table name for the Quiz entity.
	// It exists in this package in order to avoid circular dependency with the "quiz" package.
	QuizInverseTable = "Quiz_quiz"
	// QuizColumn is the table column denoting the quiz relation/edge.
	QuizColumn = "quiz_questions"
	// ChoicesTable is the table that holds the choices relation/edge.
	ChoicesTable = "Question_answerchoice"
	// ChoicesInverseTable is the table name for the AnswerChoice entity.
	// It exists in this package in order to avoid circular dependency with the "answerchoice" package.
	ChoicesInverseTable = "Question_answerchoice"
	// ChoicesColumn is the table column denoting the choices relation/edge.
	ChoicesColumn = "question_choices"
)

// Columns holds all SQL columns for question fields.
var Columns = []string{
	FieldID,
	FieldQuestionText,
	FieldQuestionType,
	FieldOrder,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "Question_question"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"quiz_questions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultQuestionType holds the default value on creation for the "question_type" field.
	DefaultQuestionType string
	// DefaultOrder holds the default value on creation for the "order" field.
	DefaultOrder int
)

// OrderOption defines the ordering options for the Question queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByQuestionText orders the results by the question_text field.
func ByQuestionText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestionText, opts...).ToFunc()
}

// ByQuestionType orders the results by the question_type field.
func ByQuestionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestionType, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// ByQuizField orders the results by quiz field.
func ByQuizField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuizStep(), sql.OrderByField(field, opts...))
	}
}

// ByChoicesCount orders the results by choices count.
func ByChoicesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChoicesStep(), opts...)
	}
}

// ByChoices orders the results by choices terms.
func ByChoices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChoicesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newQuizStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuizInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, QuizTable, QuizColumn),
	)
}
func newChoicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChoicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChoicesTable, ChoicesColumn),
	)
}
