// Code generated by ent, DO NOT EDIT.

package answerchoice

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SHP-Association/E-learningWeb/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldLTE(FieldID, id))
}

// ChoiceText applies equality check predicate on the "choice_text" field. It's identical to ChoiceTextEQ.
func ChoiceText(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldEQ(FieldChoiceText, v))
}

// IsCorrect applies equality check predicate on the "is_correct" field. It's identical to IsCorrectEQ.
func IsCorrect(v bool) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldEQ(FieldIsCorrect, v))
}

// ChoiceTextEQ applies the EQ predicate on the "choice_text" field.
func ChoiceTextEQ(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldEQ(FieldChoiceText, v))
}

// ChoiceTextNEQ applies the NEQ predicate on the "choice_text" field.
func ChoiceTextNEQ(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldNEQ(FieldChoiceText, v))
}

// ChoiceTextIn applies the In predicate on the "choice_text" field.
func ChoiceTextIn(vs ...string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldIn(FieldChoiceText, vs...))
}

// ChoiceTextNotIn applies the NotIn predicate on the "choice_text" field.
func ChoiceTextNotIn(vs ...string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldNotIn(FieldChoiceText, vs...))
}

// ChoiceTextGT applies the GT predicate on the "choice_text" field.
func ChoiceTextGT(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldGT(FieldChoiceText, v))
}

// ChoiceTextGTE applies the GTE predicate on the "choice_text" field.
func ChoiceTextGTE(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldGTE(FieldChoiceText, v))
}

// ChoiceTextLT applies the LT predicate on the "choice_text" field.
func ChoiceTextLT(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldLT(FieldChoiceText, v))
}

// ChoiceTextLTE applies the LTE predicate on the "choice_text" field.
func ChoiceTextLTE(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldLTE(FieldChoiceText, v))
}

// ChoiceTextContains applies the Contains predicate on the "choice_text" field.
func ChoiceTextContains(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldContains(FieldChoiceText, v))
}

// ChoiceTextHasPrefix applies the HasPrefix predicate on the "choice_text" field.
func ChoiceTextHasPrefix(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldHasPrefix(FieldChoiceText, v))
}

// ChoiceTextHasSuffix applies the HasSuffix predicate on the "choice_text" field.
func ChoiceTextHasSuffix(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldHasSuffix(FieldChoiceText, v))
}

// ChoiceTextEqualFold applies the EqualFold predicate on the "choice_text" field.
func ChoiceTextEqualFold(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldEqualFold(FieldChoiceText, v))
}

// ChoiceTextContainsFold applies the ContainsFold predicate on the "choice_text" field.
func ChoiceTextContainsFold(v string) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldContainsFold(FieldChoiceText, v))
}

// IsCorrectEQ applies the EQ predicate on the "is_correct" field.
func IsCorrectEQ(v bool) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldEQ(FieldIsCorrect, v))
}

// IsCorrectNEQ applies the NEQ predicate on the "is_correct" field.
func IsCorrectNEQ(v bool) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.FieldNEQ(FieldIsCorrect, v))
}

// HasQuestion applies the HasEdge predicate on the "question" edge.
func HasQuestion() predicate.AnswerChoice {
	return predicate.AnswerChoice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuestionTable, QuestionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionWith applies the HasEdge predicate on the "question" edge with a given conditions (other predicates).
func HasQuestionWith(preds ...predicate.Question) predicate.AnswerChoice {
	return predicate.AnswerChoice(func(s *sql.Selector) {
		step := newQuestionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnswerChoice) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnswerChoice) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnswerChoice) predicate.AnswerChoice {
	return predicate.AnswerChoice(sql.NotPredicates(p))
}
