// Code generated by ent, DO NOT EDIT.

package lesson

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SHP-Association/E-learningWeb/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldTitle, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldSlug, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldContent, v))
}

// VideoLink applies equality check predicate on the "video_link" field. It's identical to VideoLinkEQ.
func VideoLink(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldVideoLink, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldOrder, v))
}

// IsPreview applies equality check predicate on the "is_preview" field. It's identical to IsPreviewEQ.
func IsPreview(v bool) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldIsPreview, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContainsFold(FieldTitle, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContainsFold(FieldSlug, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.Lesson {
	return predicate.Lesson(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.Lesson {
	return predicate.Lesson(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContainsFold(FieldContent, v))
}

// VideoLinkEQ applies the EQ predicate on the "video_link" field.
func VideoLinkEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldVideoLink, v))
}

// VideoLinkNEQ applies the NEQ predicate on the "video_link" field.
func VideoLinkNEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldVideoLink, v))
}

// VideoLinkIn applies the In predicate on the "video_link" field.
func VideoLinkIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldVideoLink, vs...))
}

// VideoLinkNotIn applies the NotIn predicate on the "video_link" field.
func VideoLinkNotIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldVideoLink, vs...))
}

// VideoLinkGT applies the GT predicate on the "video_link" field.
func VideoLinkGT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldVideoLink, v))
}

// VideoLinkGTE applies the GTE predicate on the "video_link" field.
func VideoLinkGTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldVideoLink, v))
}

// VideoLinkLT applies the LT predicate on the "video_link" field.
func VideoLinkLT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldVideoLink, v))
}

// VideoLinkLTE applies the LTE predicate on the "video_link" field.
func VideoLinkLTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldVideoLink, v))
}

// VideoLinkContains applies the Contains predicate on the "video_link" field.
func VideoLinkContains(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContains(FieldVideoLink, v))
}

// VideoLinkHasPrefix applies the HasPrefix predicate on the "video_link" field.
func VideoLinkHasPrefix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasPrefix(FieldVideoLink, v))
}

// VideoLinkHasSuffix applies the HasSuffix predicate on the "video_link" field.
func VideoLinkHasSuffix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasSuffix(FieldVideoLink, v))
}

// VideoLinkIsNil applies the IsNil predicate on the "video_link" field.
func VideoLinkIsNil() predicate.Lesson {
	return predicate.Lesson(sql.FieldIsNull(FieldVideoLink))
}

// VideoLinkNotNil applies the NotNil predicate on the "video_link" field.
func VideoLinkNotNil() predicate.Lesson {
	return predicate.Lesson(sql.FieldNotNull(FieldVideoLink))
}

// VideoLinkEqualFold applies the EqualFold predicate on the "video_link" field.
func VideoLinkEqualFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEqualFold(FieldVideoLink, v))
}

// VideoLinkContainsFold applies the ContainsFold predicate on the "video_link" field.
func VideoLinkContainsFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContainsFold(FieldVideoLink, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldOrder, v))
}

// IsPreviewEQ applies the EQ predicate on the "is_preview" field.
func IsPreviewEQ(v bool) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldIsPreview, v))
}

// IsPreviewNEQ applies the NEQ predicate on the "is_preview" field.
func IsPreviewNEQ(v bool) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldIsPreview, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCourse applies the HasEdge predicate on the "course" edge.
func HasCourse() predicate.Lesson {
	return predicate.Lesson(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CourseTable, CourseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCourseWith applies the HasEdge predicate on the "course" edge with a given conditions (other predicates).
func HasCourseWith(preds ...predicate.Course) predicate.Lesson {
	return predicate.Lesson(func(s *sql.Selector) {
		step := newCourseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQuizzes applies the HasEdge predicate on the "quizzes" edge.
func HasQuizzes() predicate.Lesson {
	return predicate.Lesson(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, QuizzesTable, QuizzesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuizzesWith applies the HasEdge predicate on the "quizzes" edge with a given conditions (other predicates).
func HasQuizzesWith(preds ...predicate.Quiz) predicate.Lesson {
	return predicate.Lesson(func(s *sql.Selector) {
		step := newQuizzesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Lesson) predicate.Lesson {
	return predicate.Lesson(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Lesson) predicate.Lesson {
	return predicate.Lesson(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Lesson) predicate.Lesson {
	return predicate.Lesson(sql.NotPredicates(p))
}
