// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SHP-Association/E-learningWeb/backend/ent/answerchoice"
	"github.com/SHP-Association/E-learningWeb/backend/ent/question"
)

// AnswerChoice is the model entity for the AnswerChoice schema.
type AnswerChoice struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ChoiceText holds the value of the "choice_text" field.
	ChoiceText string `json:"choice_text,omitempty"`
	// IsCorrect holds the value of the "is_correct" field.
	IsCorrect bool `json:"is_correct,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnswerChoiceQuery when eager-loading is set.
	Edges            AnswerChoiceEdges `json:"edges"`
	question_choices *int
	selectValues     sql.SelectValues
}

// AnswerChoiceEdges holds the relations/edges for other nodes in the graph.
type AnswerChoiceEdges struct {
	// Question holds the value of the question edge.
	Question *Question `json:"question,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnswerChoiceEdges) QuestionOrErr() (*Question, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: question.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnswerChoice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case answerchoice.FieldIsCorrect:
			values[i] = new(sql.NullBool)
		case answerchoice.FieldID:
			values[i] = new(sql.NullInt64)
		case answerchoice.FieldChoiceText:
			values[i] = new(sql.NullString)
		case answerchoice.ForeignKeys[0]: // question_choices
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnswerChoice fields.
func (_m *AnswerChoice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case answerchoice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case answerchoice.FieldChoiceText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field choice_text", values[i])
			} else if value.Valid {
				_m.ChoiceText = value.String
			}
		case answerchoice.FieldIsCorrect:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_correct", values[i])
			} else if value.Valid {
				_m.IsCorrect = value.Bool
			}
		case answerchoice.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field question_choices", value)
			} else if value.Valid {
				_m.question_choices = new(int)
				*_m.question_choices = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnswerChoice.
// This includes values selected through modifiers, order, etc.
func (_m *AnswerChoice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuestion queries the "question" edge of the AnswerChoice entity.
func (_m *AnswerChoice) QueryQuestion() *QuestionQuery {
	return NewAnswerChoiceClient(_m.config).QueryQuestion(_m)
}

// Update returns a builder for updating this AnswerChoice.
// Note that you need to call AnswerChoice.Unwrap() before calling this method if this AnswerChoice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AnswerChoice) Update() *AnswerChoiceUpdateOne {
	return NewAnswerChoiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AnswerChoice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AnswerChoice) Unwrap() *AnswerChoice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnswerChoice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AnswerChoice) String() string {
	var builder strings.Builder
	builder.WriteString("AnswerChoice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("choice_text=")
	builder.WriteString(_m.ChoiceText)
	builder.WriteString(", ")
	builder.WriteString("is_correct=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCorrect))
	builder.WriteByte(')')
	return builder.String()
}

// AnswerChoices is a parsable slice of AnswerChoice.
type AnswerChoices []*AnswerChoice
