// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SHP-Association/E-learningWeb/backend/ent/certificate"
	"github.com/SHP-Association/E-learningWeb/backend/ent/enrollment"
)

// Certificate is the model entity for the Certificate schema.
type Certificate struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UniqueID holds the value of the "unique_id" field.
	UniqueID string `json:"unique_id,omitempty"`
	// IssueDate holds the value of the "issue_date" field.
	IssueDate time.Time `json:"issue_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CertificateQuery when eager-loading is set.
	Edges                  CertificateEdges `json:"edges"`
	enrollment_certificate *int
	selectValues           sql.SelectValues
}

// CertificateEdges holds the relations/edges for other nodes in the graph.
type CertificateEdges struct {
	// Enrollment holds the value of the enrollment edge.
	Enrollment *Enrollment `json:"enrollment,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EnrollmentOrErr returns the Enrollment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CertificateEdges) EnrollmentOrErr() (*Enrollment, error) {
	if e.Enrollment != nil {
		return e.Enrollment, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: enrollment.Label}
	}
	return nil, &NotLoadedError{edge: "enrollment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Certificate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case certificate.FieldID:
			values[i] = new(sql.NullInt64)
		case certificate.FieldUniqueID:
			values[i] = new(sql.NullString)
		case certificate.FieldIssueDate:
			values[i] = new(sql.NullTime)
		case certificate.ForeignKeys[0]: // enrollment_certificate
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Certificate fields.
func (_m *Certificate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case certificate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case certificate.FieldUniqueID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unique_id", values[i])
			} else if value.Valid {
				_m.UniqueID = value.String
			}
		case certificate.FieldIssueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issue_date", values[i])
			} else if value.Valid {
				_m.IssueDate = value.Time
			}
		case certificate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field enrollment_certificate", value)
			} else if value.Valid {
				_m.enrollment_certificate = new(int)
				*_m.enrollment_certificate = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Certificate.
// This includes values selected through modifiers, order, etc.
func (_m *Certificate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEnrollment queries the "enrollment" edge of the Certificate entity.
func (_m *Certificate) QueryEnrollment() *EnrollmentQuery {
	return NewCertificateClient(_m.config).QueryEnrollment(_m)
}

// Update returns a builder for updating this Certificate.
// Note that you need to call Certificate.Unwrap() before calling this method if this Certificate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Certificate) Update() *CertificateUpdateOne {
	return NewCertificateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Certificate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Certificate) Unwrap() *Certificate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Certificate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Certificate) String() string {
	var builder strings.Builder
	builder.WriteString("Certificate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("unique_id=")
	builder.WriteString(_m.UniqueID)
	builder.WriteString(", ")
	builder.WriteString("issue_date=")
	builder.WriteString(_m.IssueDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Certificates is a parsable slice of Certificate.
type Certificates []*Certificate
