// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SHP-Association/E-learningWeb/backend/ent/category"
	"github.com/SHP-Association/E-learningWeb/backend/ent/course"
	"github.com/SHP-Association/E-learningWeb/backend/ent/enrollment"
	"github.com/SHP-Association/E-learningWeb/backend/ent/lesson"
	"github.com/SHP-Association/E-learningWeb/backend/ent/review"
	"github.com/SHP-Association/E-learningWeb/backend/ent/user"
)

// CourseCreate is the builder for creating a Course entity.
type CourseCreate struct {
	config
	mutation *CourseMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *CourseCreate) SetTitle(v string) *CourseCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *CourseCreate) SetSlug(v string) *CourseCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetShortDescription sets the "short_description" field.
func (_c *CourseCreate) SetShortDescription(v string) *CourseCreate {
	_c.mutation.SetShortDescription(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CourseCreate) SetDescription(v string) *CourseCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetWhatYouWillLearn sets the "what_you_will_learn" field.
func (_c *CourseCreate) SetWhatYouWillLearn(v string) *CourseCreate {
	_c.mutation.SetWhatYouWillLearn(v)
	return _c
}

// SetNillableWhatYouWillLearn sets the "what_you_will_learn" field if the given value is not nil.
func (_c *CourseCreate) SetNillableWhatYouWillLearn(v *string) *CourseCreate {
	if v != nil {
		_c.SetWhatYouWillLearn(*v)
	}
	return _c
}

// SetRequirements sets the "requirements" field.
func (_c *CourseCreate) SetRequirements(v string) *CourseCreate {
	_c.mutation.SetRequirements(v)
	return _c
}

// SetNillableRequirements sets the "requirements" field if the given value is not nil.
func (_c *CourseCreate) SetNillableRequirements(v *string) *CourseCreate {
	if v != nil {
		_c.SetRequirements(*v)
	}
	return _c
}

// SetTargetAudience sets the "target_audience" field.
func (_c *CourseCreate) SetTargetAudience(v string) *CourseCreate {
	_c.mutation.SetTargetAudience(v)
	return _c
}

// SetNillableTargetAudience sets the "target_audience" field if the given value is not nil.
func (_c *CourseCreate) SetNillableTargetAudience(v *string) *CourseCreate {
	if v != nil {
		_c.SetTargetAudience(*v)
	}
	return _c
}

// SetThumbnail sets the "thumbnail" field.
func (_c *CourseCreate) SetThumbnail(v string) *CourseCreate {
	_c.mutation.SetThumbnail(v)
	return _c
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (_c *CourseCreate) SetNillableThumbnail(v *string) *CourseCreate {
	if v != nil {
		_c.SetThumbnail(*v)
	}
	return _c
}

// SetPromoVideoLink sets the "promo_video_link" field.
func (_c *CourseCreate) SetPromoVideoLink(v string) *CourseCreate {
	_c.mutation.SetPromoVideoLink(v)
	return _c
}

// SetNillablePromoVideoLink sets the "promo_video_link" field if the given value is not nil.
func (_c *CourseCreate) SetNillablePromoVideoLink(v *string) *CourseCreate {
	if v != nil {
		_c.SetPromoVideoLink(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *CourseCreate) SetPrice(v float64) *CourseCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *CourseCreate) SetNillablePrice(v *float64) *CourseCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetIsFree sets the "is_free" field.
func (_c *CourseCreate) SetIsFree(v bool) *CourseCreate {
	_c.mutation.SetIsFree(v)
	return _c
}

// SetNillableIsFree sets the "is_free" field if the given value is not nil.
func (_c *CourseCreate) SetNillableIsFree(v *bool) *CourseCreate {
	if v != nil {
		_c.SetIsFree(*v)
	}
	return _c
}

// SetIsPublished sets the "is_published" field.
func (_c *CourseCreate) SetIsPublished(v bool) *CourseCreate {
	_c.mutation.SetIsPublished(v)
	return _c
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_c *CourseCreate) SetNillableIsPublished(v *bool) *CourseCreate {
	if v != nil {
		_c.SetIsPublished(*v)
	}
	return _c
}

// SetLevel sets the "level" field.
func (_c *CourseCreate) SetLevel(v string) *CourseCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *CourseCreate) SetNillableLevel(v *string) *CourseCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetDuration sets the "duration" field.
func (_c *CourseCreate) SetDuration(v string) *CourseCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_c *CourseCreate) SetNillableDuration(v *string) *CourseCreate {
	if v != nil {
		_c.SetDuration(*v)
	}
	return _c
}

// SetTotalLectures sets the "total_lectures" field.
func (_c *CourseCreate) SetTotalLectures(v int) *CourseCreate {
	_c.mutation.SetTotalLectures(v)
	return _c
}

// SetNillableTotalLectures sets the "total_lectures" field if the given value is not nil.
func (_c *CourseCreate) SetNillableTotalLectures(v *int) *CourseCreate {
	if v != nil {
		_c.SetTotalLectures(*v)
	}
	return _c
}

// SetAverageRating sets the "average_rating" field.
func (_c *CourseCreate) SetAverageRating(v float64) *CourseCreate {
	_c.mutation.SetAverageRating(v)
	return _c
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_c *CourseCreate) SetNillableAverageRating(v *float64) *CourseCreate {
	if v != nil {
		_c.SetAverageRating(*v)
	}
	return _c
}

// SetNumberOfReviews sets the "number_of_reviews" field.
func (_c *CourseCreate) SetNumberOfReviews(v int) *CourseCreate {
	_c.mutation.SetNumberOfReviews(v)
	return _c
}

// SetNillableNumberOfReviews sets the "number_of_reviews" field if the given value is not nil.
func (_c *CourseCreate) SetNillableNumberOfReviews(v *int) *CourseCreate {
	if v != nil {
		_c.SetNumberOfReviews(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CourseCreate) SetCreatedAt(v time.Time) *CourseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CourseCreate) SetNillableCreatedAt(v *time.Time) *CourseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CourseCreate) SetUpdatedAt(v time.Time) *CourseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CourseCreate) SetNillableUpdatedAt(v *time.Time) *CourseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CourseCreate) SetID(v int) *CourseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetInstructorID sets the "instructor" edge to the User entity by ID.
func (_c *CourseCreate) SetInstructorID(id int) *CourseCreate {
	_c.mutation.SetInstructorID(id)
	return _c
}

// SetNillableInstructorID sets the "instructor" edge to the User entity by ID if the given value is not nil.
func (_c *CourseCreate) SetNillableInstructorID(id *int) *CourseCreate {
	if id != nil {
		_c = _c.SetInstructorID(*id)
	}
	return _c
}

// SetInstructor sets the "instructor" edge to the User entity.
func (_c *CourseCreate) SetInstructor(v *User) *CourseCreate {
	return _c.SetInstructorID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_c *CourseCreate) SetCategoryID(id int) *CourseCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_c *CourseCreate) SetNillableCategoryID(id *int) *CourseCreate {
	if id != nil {
		_c = _c.SetCategoryID(*id)
	}
	return _c
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *CourseCreate) SetCategory(v *Category) *CourseCreate {
	return _c.SetCategoryID(v.ID)
}

// AddLessonIDs adds the "lessons" edge to the Lesson entity by IDs.
func (_c *CourseCreate) AddLessonIDs(ids ...int) *CourseCreate {
	_c.mutation.AddLessonIDs(ids...)
	return _c
}

// AddLessons adds the "lessons" edges to the Lesson entity.
func (_c *CourseCreate) AddLessons(v ...*Lesson) *CourseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLessonIDs(ids...)
}

// AddEnrollmentIDs adds the "enrollments" edge to the Enrollment entity by IDs.
func (_c *CourseCreate) AddEnrollmentIDs(ids ...int) *CourseCreate {
	_c.mutation.AddEnrollmentIDs(ids...)
	return _c
}

// AddEnrollments adds the "enrollments" edges to the Enrollment entity.
func (_c *CourseCreate) AddEnrollments(v ...*Enrollment) *CourseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEnrollmentIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_c *CourseCreate) AddReviewIDs(ids ...int) *CourseCreate {
	_c.mutation.AddReviewIDs(ids...)
	return _c
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_c *CourseCreate) AddReviews(v ...*Review) *CourseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewIDs(ids...)
}

// AddEnrolledStudentIDs adds the "enrolled_students" edge to the User entity by IDs.
func (_c *CourseCreate) AddEnrolledStudentIDs(ids ...int) *CourseCreate {
	_c.mutation.AddEnrolledStudentIDs(ids...)
	return _c
}

// AddEnrolledStudents adds the "enrolled_students" edges to the User entity.
func (_c *CourseCreate) AddEnrolledStudents(v ...*User) *CourseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEnrolledStudentIDs(ids...)
}

// AddCompletedStudentIDs adds the "completed_students" edge to the User entity by IDs.
func (_c *CourseCreate) AddCompletedStudentIDs(ids ...int) *CourseCreate {
	_c.mutation.AddCompletedStudentIDs(ids...)
	return _c
}

// AddCompletedStudents adds the "completed_students" edges to the User entity.
func (_c *CourseCreate) AddCompletedStudents(v ...*User) *CourseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCompletedStudentIDs(ids...)
}

// Mutation returns the CourseMutation object of the builder.
func (_c *CourseCreate) Mutation() *CourseMutation {
	return _c.mutation
}

// Save creates the Course in the database.
func (_c *CourseCreate) Save(ctx context.Context) (*Course, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseCreate) SaveX(ctx context.Context) *Course {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CourseCreate) defaults() {
	if _, ok := _c.mutation.Price(); !ok {
		v := course.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.IsFree(); !ok {
		v := course.DefaultIsFree
		_c.mutation.SetIsFree(v)
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		v := course.DefaultIsPublished
		_c.mutation.SetIsPublished(v)
	}
	if _, ok := _c.mutation.Level(); !ok {
		v := course.DefaultLevel
		_c.mutation.SetLevel(v)
	}
	if _, ok := _c.mutation.TotalLectures(); !ok {
		v := course.DefaultTotalLectures
		_c.mutation.SetTotalLectures(v)
	}
	if _, ok := _c.mutation.AverageRating(); !ok {
		v := course.DefaultAverageRating
		_c.mutation.SetAverageRating(v)
	}
	if _, ok := _c.mutation.NumberOfReviews(); !ok {
		v := course.DefaultNumberOfReviews
		_c.mutation.SetNumberOfReviews(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := course.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := course.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Course.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := course.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Course.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Course.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := course.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Course.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ShortDescription(); !ok {
		return &ValidationError{Name: "short_description", err: errors.New(`ent: missing required field "Course.short_description"`)}
	}
	if v, ok := _c.mutation.ShortDescription(); ok {
		if err := course.ShortDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "short_description", err: fmt.Errorf(`ent: validator failed for field "Course.short_description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Course.description"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Course.price"`)}
	}
	if _, ok := _c.mutation.IsFree(); !ok {
		return &ValidationError{Name: "is_free", err: errors.New(`ent: missing required field "Course.is_free"`)}
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		return &ValidationError{Name: "is_published", err: errors.New(`ent: missing required field "Course.is_published"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Course.level"`)}
	}
	if _, ok := _c.mutation.TotalLectures(); !ok {
		return &ValidationError{Name: "total_lectures", err: errors.New(`ent: missing required field "Course.total_lectures"`)}
	}
	if _, ok := _c.mutation.AverageRating(); !ok {
		return &ValidationError{Name: "average_rating", err: errors.New(`ent: missing required field "Course.average_rating"`)}
	}
	if _, ok := _c.mutation.NumberOfReviews(); !ok {
		return &ValidationError{Name: "number_of_reviews", err: errors.New(`ent: missing required field "Course.number_of_reviews"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Course.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Course.updated_at"`)}
	}
	return nil
}

func (_c *CourseCreate) sqlSave(ctx context.Context) (*Course, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseCreate) createSpec() (*Course, *sqlgraph.CreateSpec) {
	var (
		_node = &Course{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(course.Table, sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(course.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(course.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.ShortDescription(); ok {
		_spec.SetField(course.FieldShortDescription, field.TypeString, value)
		_node.ShortDescription = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(course.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.WhatYouWillLearn(); ok {
		_spec.SetField(course.FieldWhatYouWillLearn, field.TypeString, value)
		_node.WhatYouWillLearn = value
	}
	if value, ok := _c.mutation.Requirements(); ok {
		_spec.SetField(course.FieldRequirements, field.TypeString, value)
		_node.Requirements = value
	}
	if value, ok := _c.mutation.TargetAudience(); ok {
		_spec.SetField(course.FieldTargetAudience, field.TypeString, value)
		_node.TargetAudience = value
	}
	if value, ok := _c.mutation.Thumbnail(); ok {
		_spec.SetField(course.FieldThumbnail, field.TypeString, value)
		_node.Thumbnail = value
	}
	if value, ok := _c.mutation.PromoVideoLink(); ok {
		_spec.SetField(course.FieldPromoVideoLink, field.TypeString, value)
		_node.PromoVideoLink = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(course.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.IsFree(); ok {
		_spec.SetField(course.FieldIsFree, field.TypeBool, value)
		_node.IsFree = value
	}
	if value, ok := _c.mutation.IsPublished(); ok {
		_spec.SetField(course.FieldIsPublished, field.TypeBool, value)
		_node.IsPublished = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(course.FieldLevel, field.TypeString, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Duration(); ok {
		_spec.SetField(course.FieldDuration, field.TypeString, value)
		_node.Duration = value
	}
	if value, ok := _c.mutation.TotalLectures(); ok {
		_spec.SetField(course.FieldTotalLectures, field.TypeInt, value)
		_node.TotalLectures = value
	}
	if value, ok := _c.mutation.AverageRating(); ok {
		_spec.SetField(course.FieldAverageRating, field.TypeFloat64, value)
		_node.AverageRating = value
	}
	if value, ok := _c.mutation.NumberOfReviews(); ok {
		_spec.SetField(course.FieldNumberOfReviews, field.TypeInt, value)
		_node.NumberOfReviews = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(course.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(course.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.InstructorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   course.InstructorTable,
			Columns: []string{course.InstructorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_taught_courses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   course.CategoryTable,
			Columns: []string{course.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.category_courses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.LessonsTable,
			Columns: []string{course.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lesson.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.EnrollmentsTable,
			Columns: []string{course.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.ReviewsTable,
			Columns: []string{course.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EnrolledStudentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   course.EnrolledStudentsTable,
			Columns: course.EnrolledStudentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CompletedStudentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   course.CompletedStudentsTable,
			Columns: course.CompletedStudentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CourseCreateBulk is the builder for creating many Course entities in bulk.
type CourseCreateBulk struct {
	config
	err      error
	builders []*CourseCreate
}

// Save creates the Course entities in the database.
func (_c *CourseCreateBulk) Save(ctx context.Context) ([]*Course, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Course, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseCreateBulk) SaveX(ctx context.Context) []*Course {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
