// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SHP-Association/E-learningWeb/backend/ent/answerchoice"
	"github.com/SHP-Association/E-learningWeb/backend/ent/question"
	"github.com/SHP-Association/E-learningWeb/backend/ent/quiz"
)

// QuestionCreate is the builder for creating a Question entity.
type QuestionCreate struct {
	config
	mutation *QuestionMutation
	hooks    []Hook
}

// SetQuestionText sets the "question_text" field.
func (_c *QuestionCreate) SetQuestionText(v string) *QuestionCreate {
	_c.mutation.SetQuestionText(v)
	return _c
}

// SetQuestionType sets the "question_type" field.
func (_c *QuestionCreate) SetQuestionType(v string) *QuestionCreate {
	_c.mutation.SetQuestionType(v)
	return _c
}

// SetNillableQuestionType sets the "question_type" field if the given value is not nil.
func (_c *QuestionCreate) SetNillableQuestionType(v *string) *QuestionCreate {
	if v != nil {
		_c.SetQuestionType(*v)
	}
	return _c
}

// SetOrder sets the "order" field.
func (_c *QuestionCreate) SetOrder(v int) *QuestionCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *QuestionCreate) SetNillableOrder(v *int) *QuestionCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuestionCreate) SetID(v int) *QuestionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_c *QuestionCreate) SetQuizID(id int) *QuestionCreate {
	_c.mutation.SetQuizID(id)
	return _c
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_c *QuestionCreate) SetQuiz(v *Quiz) *QuestionCreate {
	return _c.SetQuizID(v.ID)
}

// AddChoiceIDs adds the "choices" edge to the AnswerChoice entity by IDs.
func (_c *QuestionCreate) AddChoiceIDs(ids ...int) *QuestionCreate {
	_c.mutation.AddChoiceIDs(ids...)
	return _c
}

// AddChoices adds the "choices" edges to the AnswerChoice entity.
func (_c *QuestionCreate) AddChoices(v ...*AnswerChoice) *QuestionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChoiceIDs(ids...)
}

// Mutation returns the QuestionMutation object of the builder.
func (_c *QuestionCreate) Mutation() *QuestionMutation {
	return _c.mutation
}

// Save creates the Question in the database.
func (_c *QuestionCreate) Save(ctx context.Context) (*Question, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuestionCreate) SaveX(ctx context.Context) *Question {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuestionCreate) defaults() {
	if _, ok := _c.mutation.QuestionType(); !ok {
		v := question.DefaultQuestionType
		_c.mutation.SetQuestionType(v)
	}
	if _, ok := _c.mutation.Order(); !ok {
		v := question.DefaultOrder
		_c.mutation.SetOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuestionCreate) check() error {
	if _, ok := _c.mutation.QuestionText(); !ok {
		return &ValidationError{Name: "question_text", err: errors.New(`ent: missing required field "Question.question_text"`)}
	}
	if _, ok := _c.mutation.QuestionType(); !ok {
		return &ValidationError{Name: "question_type", err: errors.New(`ent: missing required field "Question.question_type"`)}
	}
	if _, ok := _c.mutation.Order(); !ok {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required field "Question.order"`)}
	}
	if len(_c.mutation.QuizIDs()) == 0 {
		return &ValidationError{Name: "quiz", err: errors.New(`ent: missing required edge "Question.quiz"`)}
	}
	return nil
}

func (_c *QuestionCreate) sqlSave(ctx context.Context) (*Question, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuestionCreate) createSpec() (*Question, *sqlgraph.CreateSpec) {
	var (
		_node = &Question{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(question.Table, sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.QuestionText(); ok {
		_spec.SetField(question.FieldQuestionText, field.TypeString, value)
		_node.QuestionText = value
	}
	if value, ok := _c.mutation.QuestionType(); ok {
		_spec.SetField(question.FieldQuestionType, field.TypeString, value)
		_node.QuestionType = value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(question.FieldOrder, field.TypeInt, value)
		_node.Order = value
	}
	if nodes := _c.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   question.QuizTable,
			Columns: []string{question.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.quiz_questions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.ChoicesTable,
			Columns: []string{question.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answerchoice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuestionCreateBulk is the builder for creating many Question entities in bulk.
type QuestionCreateBulk struct {
	config
	err      error
	builders []*QuestionCreate
}

// Save creates the Question entities in the database.
func (_c *QuestionCreateBulk) Save(ctx context.Context) ([]*Question, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Question, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuestionCreateBulk) SaveX(ctx context.Context) []*Question {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
