// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SHP-Association/E-learningWeb/backend/ent/lesson"
	"github.com/SHP-Association/E-learningWeb/backend/ent/predicate"
	"github.com/SHP-Association/E-learningWeb/backend/ent/question"
	"github.com/SHP-Association/E-learningWeb/backend/ent/quiz"
	"github.com/SHP-Association/E-learningWeb/backend/ent/userquizattempt"
)

// QuizUpdate is the builder for updating Quiz entities.
type QuizUpdate struct {
	config
	hooks    []Hook
	mutation *QuizMutation
}

// Where appends a list predicates to the QuizUpdate builder.
func (_u *QuizUpdate) Where(ps ...predicate.Quiz) *QuizUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *QuizUpdate) SetTitle(v string) *QuizUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *QuizUpdate) SetNillableTitle(v *string) *QuizUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *QuizUpdate) SetDescription(v string) *QuizUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *QuizUpdate) SetNillableDescription(v *string) *QuizUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *QuizUpdate) ClearDescription() *QuizUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPassingScore sets the "passing_score" field.
func (_u *QuizUpdate) SetPassingScore(v int) *QuizUpdate {
	_u.mutation.ResetPassingScore()
	_u.mutation.SetPassingScore(v)
	return _u
}

// SetNillablePassingScore sets the "passing_score" field if the given value is not nil.
func (_u *QuizUpdate) SetNillablePassingScore(v *int) *QuizUpdate {
	if v != nil {
		_u.SetPassingScore(*v)
	}
	return _u
}

// AddPassingScore adds value to the "passing_score" field.
func (_u *QuizUpdate) AddPassingScore(v int) *QuizUpdate {
	_u.mutation.AddPassingScore(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuizUpdate) SetUpdatedAt(v time.Time) *QuizUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLessonID sets the "lesson" edge to the Lesson entity by ID.
func (_u *QuizUpdate) SetLessonID(id int) *QuizUpdate {
	_u.mutation.SetLessonID(id)
	return _u
}

// SetLesson sets the "lesson" edge to the Lesson entity.
func (_u *QuizUpdate) SetLesson(v *Lesson) *QuizUpdate {
	return _u.SetLessonID(v.ID)
}

// AddAttemptIDs adds the "attempts" edge to the UserQuizAttempt entity by IDs.
func (_u *QuizUpdate) AddAttemptIDs(ids ...int) *QuizUpdate {
	_u.mutation.AddAttemptIDs(ids...)
	return _u
}

// AddAttempts adds the "attempts" edges to the UserQuizAttempt entity.
func (_u *QuizUpdate) AddAttempts(v ...*UserQuizAttempt) *QuizUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptIDs(ids...)
}

// AddQuestionIDs adds the "questions" edge to the Question entity by IDs.
func (_u *QuizUpdate) AddQuestionIDs(ids ...int) *QuizUpdate {
	_u.mutation.AddQuestionIDs(ids...)
	return _u
}

// AddQuestions adds the "questions" edges to the Question entity.
func (_u *QuizUpdate) AddQuestions(v ...*Question) *QuizUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestionIDs(ids...)
}

// Mutation returns the QuizMutation object of the builder.
func (_u *QuizUpdate) Mutation() *QuizMutation {
	return _u.mutation
}

// ClearLesson clears the "lesson" edge to the Lesson entity.
func (_u *QuizUpdate) ClearLesson() *QuizUpdate {
	_u.mutation.ClearLesson()
	return _u
}

// ClearAttempts clears all "attempts" edges to the UserQuizAttempt entity.
func (_u *QuizUpdate) ClearAttempts() *QuizUpdate {
	_u.mutation.ClearAttempts()
	return _u
}

// RemoveAttemptIDs removes the "attempts" edge to UserQuizAttempt entities by IDs.
func (_u *QuizUpdate) RemoveAttemptIDs(ids ...int) *QuizUpdate {
	_u.mutation.RemoveAttemptIDs(ids...)
	return _u
}

// RemoveAttempts removes "attempts" edges to UserQuizAttempt entities.
func (_u *QuizUpdate) RemoveAttempts(v ...*UserQuizAttempt) *QuizUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptIDs(ids...)
}

// ClearQuestions clears all "questions" edges to the Question entity.
func (_u *QuizUpdate) ClearQuestions() *QuizUpdate {
	_u.mutation.ClearQuestions()
	return _u
}

// RemoveQuestionIDs removes the "questions" edge to Question entities by IDs.
func (_u *QuizUpdate) RemoveQuestionIDs(ids ...int) *QuizUpdate {
	_u.mutation.RemoveQuestionIDs(ids...)
	return _u
}

// RemoveQuestions removes "questions" edges to Question entities.
func (_u *QuizUpdate) RemoveQuestions(v ...*Question) *QuizUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuizUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuizUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuizUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quiz.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := quiz.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Quiz.title": %w`, err)}
		}
	}
	if _u.mutation.LessonCleared() && len(_u.mutation.LessonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Quiz.lesson"`)
	}
	return nil
}

func (_u *QuizUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quiz.Table, quiz.Columns, sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(quiz.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(quiz.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(quiz.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PassingScore(); ok {
		_spec.SetField(quiz.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassingScore(); ok {
		_spec.AddField(quiz.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quiz.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LessonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.LessonTable,
			Columns: []string{quiz.LessonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lesson.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.LessonTable,
			Columns: []string{quiz.LessonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lesson.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userquizattempt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptsIDs(); len(nodes) > 0 && !_u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userquizattempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userquizattempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestionsIDs(); len(nodes) > 0 && !_u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quiz.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuizUpdateOne is the builder for updating a single Quiz entity.
type QuizUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuizMutation
}

// SetTitle sets the "title" field.
func (_u *QuizUpdateOne) SetTitle(v string) *QuizUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *QuizUpdateOne) SetNillableTitle(v *string) *QuizUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *QuizUpdateOne) SetDescription(v string) *QuizUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *QuizUpdateOne) SetNillableDescription(v *string) *QuizUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *QuizUpdateOne) ClearDescription() *QuizUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPassingScore sets the "passing_score" field.
func (_u *QuizUpdateOne) SetPassingScore(v int) *QuizUpdateOne {
	_u.mutation.ResetPassingScore()
	_u.mutation.SetPassingScore(v)
	return _u
}

// SetNillablePassingScore sets the "passing_score" field if the given value is not nil.
func (_u *QuizUpdateOne) SetNillablePassingScore(v *int) *QuizUpdateOne {
	if v != nil {
		_u.SetPassingScore(*v)
	}
	return _u
}

// AddPassingScore adds value to the "passing_score" field.
func (_u *QuizUpdateOne) AddPassingScore(v int) *QuizUpdateOne {
	_u.mutation.AddPassingScore(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuizUpdateOne) SetUpdatedAt(v time.Time) *QuizUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLessonID sets the "lesson" edge to the Lesson entity by ID.
func (_u *QuizUpdateOne) SetLessonID(id int) *QuizUpdateOne {
	_u.mutation.SetLessonID(id)
	return _u
}

// SetLesson sets the "lesson" edge to the Lesson entity.
func (_u *QuizUpdateOne) SetLesson(v *Lesson) *QuizUpdateOne {
	return _u.SetLessonID(v.ID)
}

// AddAttemptIDs adds the "attempts" edge to the UserQuizAttempt entity by IDs.
func (_u *QuizUpdateOne) AddAttemptIDs(ids ...int) *QuizUpdateOne {
	_u.mutation.AddAttemptIDs(ids...)
	return _u
}

// AddAttempts adds the "attempts" edges to the UserQuizAttempt entity.
func (_u *QuizUpdateOne) AddAttempts(v ...*UserQuizAttempt) *QuizUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptIDs(ids...)
}

// AddQuestionIDs adds the "questions" edge to the Question entity by IDs.
func (_u *QuizUpdateOne) AddQuestionIDs(ids ...int) *QuizUpdateOne {
	_u.mutation.AddQuestionIDs(ids...)
	return _u
}

// AddQuestions adds the "questions" edges to the Question entity.
func (_u *QuizUpdateOne) AddQuestions(v ...*Question) *QuizUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestionIDs(ids...)
}

// Mutation returns the QuizMutation object of the builder.
func (_u *QuizUpdateOne) Mutation() *QuizMutation {
	return _u.mutation
}

// ClearLesson clears the "lesson" edge to the Lesson entity.
func (_u *QuizUpdateOne) ClearLesson() *QuizUpdateOne {
	_u.mutation.ClearLesson()
	return _u
}

// ClearAttempts clears all "attempts" edges to the UserQuizAttempt entity.
func (_u *QuizUpdateOne) ClearAttempts() *QuizUpdateOne {
	_u.mutation.ClearAttempts()
	return _u
}

// RemoveAttemptIDs removes the "attempts" edge to UserQuizAttempt entities by IDs.
func (_u *QuizUpdateOne) RemoveAttemptIDs(ids ...int) *QuizUpdateOne {
	_u.mutation.RemoveAttemptIDs(ids...)
	return _u
}

// RemoveAttempts removes "attempts" edges to UserQuizAttempt entities.
func (_u *QuizUpdateOne) RemoveAttempts(v ...*UserQuizAttempt) *QuizUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptIDs(ids...)
}

// ClearQuestions clears all "questions" edges to the Question entity.
func (_u *QuizUpdateOne) ClearQuestions() *QuizUpdateOne {
	_u.mutation.ClearQuestions()
	return _u
}

// RemoveQuestionIDs removes the "questions" edge to Question entities by IDs.
func (_u *QuizUpdateOne) RemoveQuestionIDs(ids ...int) *QuizUpdateOne {
	_u.mutation.RemoveQuestionIDs(ids...)
	return _u
}

// RemoveQuestions removes "questions" edges to Question entities.
func (_u *QuizUpdateOne) RemoveQuestions(v ...*Question) *QuizUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestionIDs(ids...)
}

// Where appends a list predicates to the QuizUpdate builder.
func (_u *QuizUpdateOne) Where(ps ...predicate.Quiz) *QuizUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuizUpdateOne) Select(field string, fields ...string) *QuizUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Quiz entity.
func (_u *QuizUpdateOne) Save(ctx context.Context) (*Quiz, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizUpdateOne) SaveX(ctx context.Context) *Quiz {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuizUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuizUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quiz.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := quiz.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Quiz.title": %w`, err)}
		}
	}
	if _u.mutation.LessonCleared() && len(_u.mutation.LessonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Quiz.lesson"`)
	}
	return nil
}

func (_u *QuizUpdateOne) sqlSave(ctx context.Context) (_node *Quiz, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quiz.Table, quiz.Columns, sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Quiz.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quiz.FieldID)
		for _, f := range fields {
			if !quiz.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quiz.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(quiz.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(quiz.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(quiz.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PassingScore(); ok {
		_spec.SetField(quiz.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassingScore(); ok {
		_spec.AddField(quiz.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quiz.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LessonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.LessonTable,
			Columns: []string{quiz.LessonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lesson.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.LessonTable,
			Columns: []string{quiz.LessonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lesson.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userquizattempt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptsIDs(); len(nodes) > 0 && !_u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userquizattempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userquizattempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestionsIDs(); len(nodes) > 0 && !_u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Quiz{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quiz.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
