// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SHP-Association/E-learningWeb/backend/ent/quiz"
	"github.com/SHP-Association/E-learningWeb/backend/ent/user"
	"github.com/SHP-Association/E-learningWeb/backend/ent/userquizattempt"
)

// UserQuizAttempt is the model entity for the UserQuizAttempt schema.
type UserQuizAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Score holds the value of the "score" field.
	Score float64 `json:"score,omitempty"`
	// Passed holds the value of the "passed" field.
	Passed bool `json:"passed,omitempty"`
	// AttemptNumber holds the value of the "attempt_number" field.
	AttemptNumber int `json:"attempt_number,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt time.Time `json:"submitted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuizAttemptQuery when eager-loading is set.
	Edges              UserQuizAttemptEdges `json:"edges"`
	quiz_attempts      *int
	user_quiz_attempts *int
	selectValues       sql.SelectValues
}

// UserQuizAttemptEdges holds the relations/edges for other nodes in the graph.
type UserQuizAttemptEdges struct {
	// Student holds the value of the student edge.
	Student *User `json:"student,omitempty"`
	// Quiz holds the value of the quiz edge.
	Quiz *Quiz `json:"quiz,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// StudentOrErr returns the Student value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserQuizAttemptEdges) StudentOrErr() (*User, error) {
	if e.Student != nil {
		return e.Student, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "student"}
}

// QuizOrErr returns the Quiz value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserQuizAttemptEdges) QuizOrErr() (*Quiz, error) {
	if e.Quiz != nil {
		return e.Quiz, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: quiz.Label}
	}
	return nil, &NotLoadedError{edge: "quiz"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserQuizAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userquizattempt.FieldPassed:
			values[i] = new(sql.NullBool)
		case userquizattempt.FieldScore:
			values[i] = new(sql.NullFloat64)
		case userquizattempt.FieldID, userquizattempt.FieldAttemptNumber:
			values[i] = new(sql.NullInt64)
		case userquizattempt.FieldSubmittedAt:
			values[i] = new(sql.NullTime)
		case userquizattempt.ForeignKeys[0]: // quiz_attempts
			values[i] = new(sql.NullInt64)
		case userquizattempt.ForeignKeys[1]: // user_quiz_attempts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserQuizAttempt fields.
func (_m *UserQuizAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userquizattempt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userquizattempt.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = value.Float64
			}
		case userquizattempt.FieldPassed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field passed", values[i])
			} else if value.Valid {
				_m.Passed = value.Bool
			}
		case userquizattempt.FieldAttemptNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_number", values[i])
			} else if value.Valid {
				_m.AttemptNumber = int(value.Int64)
			}
		case userquizattempt.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = value.Time
			}
		case userquizattempt.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field quiz_attempts", value)
			} else if value.Valid {
				_m.quiz_attempts = new(int)
				*_m.quiz_attempts = int(value.Int64)
			}
		case userquizattempt.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_quiz_attempts", value)
			} else if value.Valid {
				_m.user_quiz_attempts = new(int)
				*_m.user_quiz_attempts = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserQuizAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *UserQuizAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStudent queries the "student" edge of the UserQuizAttempt entity.
func (_m *UserQuizAttempt) QueryStudent() *UserQuery {
	return NewUserQuizAttemptClient(_m.config).QueryStudent(_m)
}

// QueryQuiz queries the "quiz" edge of the UserQuizAttempt entity.
func (_m *UserQuizAttempt) QueryQuiz() *QuizQuery {
	return NewUserQuizAttemptClient(_m.config).QueryQuiz(_m)
}

// Update returns a builder for updating this UserQuizAttempt.
// Note that you need to call UserQuizAttempt.Unwrap() before calling this method if this UserQuizAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserQuizAttempt) Update() *UserQuizAttemptUpdateOne {
	return NewUserQuizAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserQuizAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserQuizAttempt) Unwrap() *UserQuizAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserQuizAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserQuizAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("UserQuizAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("passed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Passed))
	builder.WriteString(", ")
	builder.WriteString("attempt_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptNumber))
	builder.WriteString(", ")
	builder.WriteString("submitted_at=")
	builder.WriteString(_m.SubmittedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserQuizAttempts is a parsable slice of UserQuizAttempt.
type UserQuizAttempts []*UserQuizAttempt
