// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SHP-Association/E-learningWeb/backend/ent/predicate"
	"github.com/SHP-Association/E-learningWeb/backend/ent/userquizattempt"
)

// UserQuizAttemptDelete is the builder for deleting a UserQuizAttempt entity.
type UserQuizAttemptDelete struct {
	config
	hooks    []Hook
	mutation *UserQuizAttemptMutation
}

// Where appends a list predicates to the UserQuizAttemptDelete builder.
func (_d *UserQuizAttemptDelete) Where(ps ...predicate.UserQuizAttempt) *UserQuizAttemptDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserQuizAttemptDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserQuizAttemptDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserQuizAttemptDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userquizattempt.Table, sqlgraph.NewFieldSpec(userquizattempt.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserQuizAttemptDeleteOne is the builder for deleting a single UserQuizAttempt entity.
type UserQuizAttemptDeleteOne struct {
	_d *UserQuizAttemptDelete
}

// Where appends a list predicates to the UserQuizAttemptDelete builder.
func (_d *UserQuizAttemptDeleteOne) Where(ps ...predicate.UserQuizAttempt) *UserQuizAttemptDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserQuizAttemptDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userquizattempt.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserQuizAttemptDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
