// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SHP-Association/E-learningWeb/backend/ent/predicate"
	"github.com/SHP-Association/E-learningWeb/backend/ent/quiz"
	"github.com/SHP-Association/E-learningWeb/backend/ent/user"
	"github.com/SHP-Association/E-learningWeb/backend/ent/userquizattempt"
)

// UserQuizAttemptUpdate is the builder for updating UserQuizAttempt entities.
type UserQuizAttemptUpdate struct {
	config
	hooks    []Hook
	mutation *UserQuizAttemptMutation
}

// Where appends a list predicates to the UserQuizAttemptUpdate builder.
func (_u *UserQuizAttemptUpdate) Where(ps ...predicate.UserQuizAttempt) *UserQuizAttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScore sets the "score" field.
func (_u *UserQuizAttemptUpdate) SetScore(v float64) *UserQuizAttemptUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *UserQuizAttemptUpdate) SetNillableScore(v *float64) *UserQuizAttemptUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *UserQuizAttemptUpdate) AddScore(v float64) *UserQuizAttemptUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetPassed sets the "passed" field.
func (_u *UserQuizAttemptUpdate) SetPassed(v bool) *UserQuizAttemptUpdate {
	_u.mutation.SetPassed(v)
	return _u
}

// SetNillablePassed sets the "passed" field if the given value is not nil.
func (_u *UserQuizAttemptUpdate) SetNillablePassed(v *bool) *UserQuizAttemptUpdate {
	if v != nil {
		_u.SetPassed(*v)
	}
	return _u
}

// SetAttemptNumber sets the "attempt_number" field.
func (_u *UserQuizAttemptUpdate) SetAttemptNumber(v int) *UserQuizAttemptUpdate {
	_u.mutation.ResetAttemptNumber()
	_u.mutation.SetAttemptNumber(v)
	return _u
}

// SetNillableAttemptNumber sets the "attempt_number" field if the given value is not nil.
func (_u *UserQuizAttemptUpdate) SetNillableAttemptNumber(v *int) *UserQuizAttemptUpdate {
	if v != nil {
		_u.SetAttemptNumber(*v)
	}
	return _u
}

// AddAttemptNumber adds value to the "attempt_number" field.
func (_u *UserQuizAttemptUpdate) AddAttemptNumber(v int) *UserQuizAttemptUpdate {
	_u.mutation.AddAttemptNumber(v)
	return _u
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (_u *UserQuizAttemptUpdate) SetStudentID(id int) *UserQuizAttemptUpdate {
	_u.mutation.SetStudentID(id)
	return _u
}

// SetStudent sets the "student" edge to the User entity.
func (_u *UserQuizAttemptUpdate) SetStudent(v *User) *UserQuizAttemptUpdate {
	return _u.SetStudentID(v.ID)
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_u *UserQuizAttemptUpdate) SetQuizID(id int) *UserQuizAttemptUpdate {
	_u.mutation.SetQuizID(id)
	return _u
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_u *UserQuizAttemptUpdate) SetQuiz(v *Quiz) *UserQuizAttemptUpdate {
	return _u.SetQuizID(v.ID)
}

// Mutation returns the UserQuizAttemptMutation object of the builder.
func (_u *UserQuizAttemptUpdate) Mutation() *UserQuizAttemptMutation {
	return _u.mutation
}

// ClearStudent clears the "student" edge to the User entity.
func (_u *UserQuizAttemptUpdate) ClearStudent() *UserQuizAttemptUpdate {
	_u.mutation.ClearStudent()
	return _u
}

// ClearQuiz clears the "quiz" edge to the Quiz entity.
func (_u *UserQuizAttemptUpdate) ClearQuiz() *UserQuizAttemptUpdate {
	_u.mutation.ClearQuiz()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserQuizAttemptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserQuizAttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserQuizAttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserQuizAttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserQuizAttemptUpdate) check() error {
	if _u.mutation.StudentCleared() && len(_u.mutation.StudentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserQuizAttempt.student"`)
	}
	if _u.mutation.QuizCleared() && len(_u.mutation.QuizIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserQuizAttempt.quiz"`)
	}
	return nil
}

func (_u *UserQuizAttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userquizattempt.Table, userquizattempt.Columns, sqlgraph.NewFieldSpec(userquizattempt.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(userquizattempt.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(userquizattempt.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Passed(); ok {
		_spec.SetField(userquizattempt.FieldPassed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AttemptNumber(); ok {
		_spec.SetField(userquizattempt.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNumber(); ok {
		_spec.AddField(userquizattempt.FieldAttemptNumber, field.TypeInt, value)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquizattempt.StudentTable,
			Columns: []string{userquizattempt.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquizattempt.StudentTable,
			Columns: []string{userquizattempt.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquizattempt.QuizTable,
			Columns: []string{userquizattempt.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquizattempt.QuizTable,
			Columns: []string{userquizattempt.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userquizattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserQuizAttemptUpdateOne is the builder for updating a single UserQuizAttempt entity.
type UserQuizAttemptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserQuizAttemptMutation
}

// SetScore sets the "score" field.
func (_u *UserQuizAttemptUpdateOne) SetScore(v float64) *UserQuizAttemptUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *UserQuizAttemptUpdateOne) SetNillableScore(v *float64) *UserQuizAttemptUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *UserQuizAttemptUpdateOne) AddScore(v float64) *UserQuizAttemptUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetPassed sets the "passed" field.
func (_u *UserQuizAttemptUpdateOne) SetPassed(v bool) *UserQuizAttemptUpdateOne {
	_u.mutation.SetPassed(v)
	return _u
}

// SetNillablePassed sets the "passed" field if the given value is not nil.
func (_u *UserQuizAttemptUpdateOne) SetNillablePassed(v *bool) *UserQuizAttemptUpdateOne {
	if v != nil {
		_u.SetPassed(*v)
	}
	return _u
}

// SetAttemptNumber sets the "attempt_number" field.
func (_u *UserQuizAttemptUpdateOne) SetAttemptNumber(v int) *UserQuizAttemptUpdateOne {
	_u.mutation.ResetAttemptNumber()
	_u.mutation.SetAttemptNumber(v)
	return _u
}

// SetNillableAttemptNumber sets the "attempt_number" field if the given value is not nil.
func (_u *UserQuizAttemptUpdateOne) SetNillableAttemptNumber(v *int) *UserQuizAttemptUpdateOne {
	if v != nil {
		_u.SetAttemptNumber(*v)
	}
	return _u
}

// AddAttemptNumber adds value to the "attempt_number" field.
func (_u *UserQuizAttemptUpdateOne) AddAttemptNumber(v int) *UserQuizAttemptUpdateOne {
	_u.mutation.AddAttemptNumber(v)
	return _u
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (_u *UserQuizAttemptUpdateOne) SetStudentID(id int) *UserQuizAttemptUpdateOne {
	_u.mutation.SetStudentID(id)
	return _u
}

// SetStudent sets the "student" edge to the User entity.
func (_u *UserQuizAttemptUpdateOne) SetStudent(v *User) *UserQuizAttemptUpdateOne {
	return _u.SetStudentID(v.ID)
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_u *UserQuizAttemptUpdateOne) SetQuizID(id int) *UserQuizAttemptUpdateOne {
	_u.mutation.SetQuizID(id)
	return _u
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_u *UserQuizAttemptUpdateOne) SetQuiz(v *Quiz) *UserQuizAttemptUpdateOne {
	return _u.SetQuizID(v.ID)
}

// Mutation returns the UserQuizAttemptMutation object of the builder.
func (_u *UserQuizAttemptUpdateOne) Mutation() *UserQuizAttemptMutation {
	return _u.mutation
}

// ClearStudent clears the "student" edge to the User entity.
func (_u *UserQuizAttemptUpdateOne) ClearStudent() *UserQuizAttemptUpdateOne {
	_u.mutation.ClearStudent()
	return _u
}

// ClearQuiz clears the "quiz" edge to the Quiz entity.
func (_u *UserQuizAttemptUpdateOne) ClearQuiz() *UserQuizAttemptUpdateOne {
	_u.mutation.ClearQuiz()
	return _u
}

// Where appends a list predicates to the UserQuizAttemptUpdate builder.
func (_u *UserQuizAttemptUpdateOne) Where(ps ...predicate.UserQuizAttempt) *UserQuizAttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserQuizAttemptUpdateOne) Select(field string, fields ...string) *UserQuizAttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserQuizAttempt entity.
func (_u *UserQuizAttemptUpdateOne) Save(ctx context.Context) (*UserQuizAttempt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserQuizAttemptUpdateOne) SaveX(ctx context.Context) *UserQuizAttempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserQuizAttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserQuizAttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserQuizAttemptUpdateOne) check() error {
	if _u.mutation.StudentCleared() && len(_u.mutation.StudentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserQuizAttempt.student"`)
	}
	if _u.mutation.QuizCleared() && len(_u.mutation.QuizIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserQuizAttempt.quiz"`)
	}
	return nil
}

func (_u *UserQuizAttemptUpdateOne) sqlSave(ctx context.Context) (_node *UserQuizAttempt, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userquizattempt.Table, userquizattempt.Columns, sqlgraph.NewFieldSpec(userquizattempt.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserQuizAttempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userquizattempt.FieldID)
		for _, f := range fields {
			if !userquizattempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userquizattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(userquizattempt.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(userquizattempt.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Passed(); ok {
		_spec.SetField(userquizattempt.FieldPassed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AttemptNumber(); ok {
		_spec.SetField(userquizattempt.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNumber(); ok {
		_spec.AddField(userquizattempt.FieldAttemptNumber, field.TypeInt, value)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquizattempt.StudentTable,
			Columns: []string{userquizattempt.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquizattempt.StudentTable,
			Columns: []string{userquizattempt.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquizattempt.QuizTable,
			Columns: []string{userquizattempt.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquizattempt.QuizTable,
			Columns: []string{userquizattempt.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserQuizAttempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userquizattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
