// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SHP-Association/E-learningWeb/backend/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"-"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Bio holds the value of the "bio" field.
	Bio string `json:"bio,omitempty"`
	// ProfilePicture holds the value of the "profile_picture" field.
	ProfilePicture string `json:"profile_picture,omitempty"`
	// DateOfBirth holds the value of the "date_of_birth" field.
	DateOfBirth *time.Time `json:"date_of_birth,omitempty"`
	// Gender holds the value of the "gender" field.
	Gender string `json:"gender,omitempty"`
	// ContactNumber holds the value of the "contact_number" field.
	ContactNumber string `json:"contact_number,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// IsEmailVerified holds the value of the "is_email_verified" field.
	IsEmailVerified bool `json:"is_email_verified,omitempty"`
	// HighestQualification holds the value of the "highest_qualification" field.
	HighestQualification string `json:"highest_qualification,omitempty"`
	// Institution holds the value of the "institution" field.
	Institution string `json:"institution,omitempty"`
	// Skills holds the value of the "skills" field.
	Skills string `json:"skills,omitempty"`
	// LinkedinProfile holds the value of the "linkedin_profile" field.
	LinkedinProfile string `json:"linkedin_profile,omitempty"`
	// GithubProfile holds the value of the "github_profile" field.
	GithubProfile string `json:"github_profile,omitempty"`
	// InstructorRating holds the value of the "instructor_rating" field.
	InstructorRating float64 `json:"instructor_rating,omitempty"`
	// TotalReviews holds the value of the "total_reviews" field.
	TotalReviews int `json:"total_reviews,omitempty"`
	// IsActiveUser holds the value of the "is_active_user" field.
	IsActiveUser bool `json:"is_active_user,omitempty"`
	// LastActivity holds the value of the "last_activity" field.
	LastActivity *time.Time `json:"last_activity,omitempty"`
	// LoginAddress holds the value of the "login_address" field.
	LoginAddress string `json:"login_address,omitempty"`
	// TwoFactorEnabled holds the value of the "two_factor_enabled" field.
	TwoFactorEnabled bool `json:"two_factor_enabled,omitempty"`
	// IsStaff holds the value of the "is_staff" field.
	IsStaff bool `json:"is_staff,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// IsSuperuser holds the value of the "is_superuser" field.
	IsSuperuser bool `json:"is_superuser,omitempty"`
	// LastLogin holds the value of the "last_login" field.
	LastLogin *time.Time `json:"last_login,omitempty"`
	// DateJoined holds the value of the "date_joined" field.
	DateJoined time.Time `json:"date_joined,omitempty"`
	// Verified holds the value of the "verified" field.
	Verified bool `json:"verified,omitempty"`
	// Admin holds the value of the "admin" field.
	Admin bool `json:"admin,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// OtpCode holds the value of the "otp_code" field.
	OtpCode string `json:"otp_code,omitempty"`
	// OtpExpiresAt holds the value of the "otp_expires_at" field.
	OtpExpiresAt time.Time `json:"otp_expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Owner holds the value of the owner edge.
	Owner []*PasswordToken `json:"owner,omitempty"`
	// TaughtCourses holds the value of the taught_courses edge.
	TaughtCourses []*Course `json:"taught_courses,omitempty"`
	// QuizAttempts holds the value of the quiz_attempts edge.
	QuizAttempts []*UserQuizAttempt `json:"quiz_attempts,omitempty"`
	// Enrollments holds the value of the enrollments edge.
	Enrollments []*Enrollment `json:"enrollments,omitempty"`
	// ReviewsGiven holds the value of the reviews_given edge.
	ReviewsGiven []*Review `json:"reviews_given,omitempty"`
	// EnrolledCourses holds the value of the enrolled_courses edge.
	EnrolledCourses []*Course `json:"enrolled_courses,omitempty"`
	// CompletedCourses holds the value of the completed_courses edge.
	CompletedCourses []*Course `json:"completed_courses,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OwnerOrErr() ([]*PasswordToken, error) {
	if e.loadedTypes[0] {
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// TaughtCoursesOrErr returns the TaughtCourses value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TaughtCoursesOrErr() ([]*Course, error) {
	if e.loadedTypes[1] {
		return e.TaughtCourses, nil
	}
	return nil, &NotLoadedError{edge: "taught_courses"}
}

// QuizAttemptsOrErr returns the QuizAttempts value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) QuizAttemptsOrErr() ([]*UserQuizAttempt, error) {
	if e.loadedTypes[2] {
		return e.QuizAttempts, nil
	}
	return nil, &NotLoadedError{edge: "quiz_attempts"}
}

// EnrollmentsOrErr returns the Enrollments value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) EnrollmentsOrErr() ([]*Enrollment, error) {
	if e.loadedTypes[3] {
		return e.Enrollments, nil
	}
	return nil, &NotLoadedError{edge: "enrollments"}
}

// ReviewsGivenOrErr returns the ReviewsGiven value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ReviewsGivenOrErr() ([]*Review, error) {
	if e.loadedTypes[4] {
		return e.ReviewsGiven, nil
	}
	return nil, &NotLoadedError{edge: "reviews_given"}
}

// EnrolledCoursesOrErr returns the EnrolledCourses value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) EnrolledCoursesOrErr() ([]*Course, error) {
	if e.loadedTypes[5] {
		return e.EnrolledCourses, nil
	}
	return nil, &NotLoadedError{edge: "enrolled_courses"}
}

// CompletedCoursesOrErr returns the CompletedCourses value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CompletedCoursesOrErr() ([]*Course, error) {
	if e.loadedTypes[6] {
		return e.CompletedCourses, nil
	}
	return nil, &NotLoadedError{edge: "completed_courses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldIsEmailVerified, user.FieldIsActiveUser, user.FieldTwoFactorEnabled, user.FieldIsStaff, user.FieldIsActive, user.FieldIsSuperuser, user.FieldVerified, user.FieldAdmin:
			values[i] = new(sql.NullBool)
		case user.FieldInstructorRating:
			values[i] = new(sql.NullFloat64)
		case user.FieldID, user.FieldTotalReviews:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername, user.FieldFirstName, user.FieldLastName, user.FieldEmail, user.FieldPassword, user.FieldRole, user.FieldBio, user.FieldProfilePicture, user.FieldGender, user.FieldContactNumber, user.FieldAddress, user.FieldCountry, user.FieldHighestQualification, user.FieldInstitution, user.FieldSkills, user.FieldLinkedinProfile, user.FieldGithubProfile, user.FieldLoginAddress, user.FieldOtpCode:
			values[i] = new(sql.NullString)
		case user.FieldDateOfBirth, user.FieldLastActivity, user.FieldLastLogin, user.FieldDateJoined, user.FieldCreatedAt, user.FieldOtpExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				_m.FirstName = value.String
			}
		case user.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				_m.LastName = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case user.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case user.FieldBio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bio", values[i])
			} else if value.Valid {
				_m.Bio = value.String
			}
		case user.FieldProfilePicture:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_picture", values[i])
			} else if value.Valid {
				_m.ProfilePicture = value.String
			}
		case user.FieldDateOfBirth:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_of_birth", values[i])
			} else if value.Valid {
				_m.DateOfBirth = new(time.Time)
				*_m.DateOfBirth = value.Time
			}
		case user.FieldGender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gender", values[i])
			} else if value.Valid {
				_m.Gender = value.String
			}
		case user.FieldContactNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_number", values[i])
			} else if value.Valid {
				_m.ContactNumber = value.String
			}
		case user.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case user.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case user.FieldIsEmailVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_email_verified", values[i])
			} else if value.Valid {
				_m.IsEmailVerified = value.Bool
			}
		case user.FieldHighestQualification:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field highest_qualification", values[i])
			} else if value.Valid {
				_m.HighestQualification = value.String
			}
		case user.FieldInstitution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field institution", values[i])
			} else if value.Valid {
				_m.Institution = value.String
			}
		case user.FieldSkills:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skills", values[i])
			} else if value.Valid {
				_m.Skills = value.String
			}
		case user.FieldLinkedinProfile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field linkedin_profile", values[i])
			} else if value.Valid {
				_m.LinkedinProfile = value.String
			}
		case user.FieldGithubProfile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field github_profile", values[i])
			} else if value.Valid {
				_m.GithubProfile = value.String
			}
		case user.FieldInstructorRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field instructor_rating", values[i])
			} else if value.Valid {
				_m.InstructorRating = value.Float64
			}
		case user.FieldTotalReviews:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_reviews", values[i])
			} else if value.Valid {
				_m.TotalReviews = int(value.Int64)
			}
		case user.FieldIsActiveUser:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active_user", values[i])
			} else if value.Valid {
				_m.IsActiveUser = value.Bool
			}
		case user.FieldLastActivity:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_activity", values[i])
			} else if value.Valid {
				_m.LastActivity = new(time.Time)
				*_m.LastActivity = value.Time
			}
		case user.FieldLoginAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login_address", values[i])
			} else if value.Valid {
				_m.LoginAddress = value.String
			}
		case user.FieldTwoFactorEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field two_factor_enabled", values[i])
			} else if value.Valid {
				_m.TwoFactorEnabled = value.Bool
			}
		case user.FieldIsStaff:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_staff", values[i])
			} else if value.Valid {
				_m.IsStaff = value.Bool
			}
		case user.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case user.FieldIsSuperuser:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_superuser", values[i])
			} else if value.Valid {
				_m.IsSuperuser = value.Bool
			}
		case user.FieldLastLogin:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login", values[i])
			} else if value.Valid {
				_m.LastLogin = new(time.Time)
				*_m.LastLogin = value.Time
			}
		case user.FieldDateJoined:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_joined", values[i])
			} else if value.Valid {
				_m.DateJoined = value.Time
			}
		case user.FieldVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified", values[i])
			} else if value.Valid {
				_m.Verified = value.Bool
			}
		case user.FieldAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field admin", values[i])
			} else if value.Valid {
				_m.Admin = value.Bool
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldOtpCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field otp_code", values[i])
			} else if value.Valid {
				_m.OtpCode = value.String
			}
		case user.FieldOtpExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field otp_expires_at", values[i])
			} else if value.Valid {
				_m.OtpExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the User entity.
func (_m *User) QueryOwner() *PasswordTokenQuery {
	return NewUserClient(_m.config).QueryOwner(_m)
}

// QueryTaughtCourses queries the "taught_courses" edge of the User entity.
func (_m *User) QueryTaughtCourses() *CourseQuery {
	return NewUserClient(_m.config).QueryTaughtCourses(_m)
}

// QueryQuizAttempts queries the "quiz_attempts" edge of the User entity.
func (_m *User) QueryQuizAttempts() *UserQuizAttemptQuery {
	return NewUserClient(_m.config).QueryQuizAttempts(_m)
}

// QueryEnrollments queries the "enrollments" edge of the User entity.
func (_m *User) QueryEnrollments() *EnrollmentQuery {
	return NewUserClient(_m.config).QueryEnrollments(_m)
}

// QueryReviewsGiven queries the "reviews_given" edge of the User entity.
func (_m *User) QueryReviewsGiven() *ReviewQuery {
	return NewUserClient(_m.config).QueryReviewsGiven(_m)
}

// QueryEnrolledCourses queries the "enrolled_courses" edge of the User entity.
func (_m *User) QueryEnrolledCourses() *CourseQuery {
	return NewUserClient(_m.config).QueryEnrolledCourses(_m)
}

// QueryCompletedCourses queries the "completed_courses" edge of the User entity.
func (_m *User) QueryCompletedCourses() *CourseQuery {
	return NewUserClient(_m.config).QueryCompletedCourses(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("first_name=")
	builder.WriteString(_m.FirstName)
	builder.WriteString(", ")
	builder.WriteString("last_name=")
	builder.WriteString(_m.LastName)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("bio=")
	builder.WriteString(_m.Bio)
	builder.WriteString(", ")
	builder.WriteString("profile_picture=")
	builder.WriteString(_m.ProfilePicture)
	builder.WriteString(", ")
	if v := _m.DateOfBirth; v != nil {
		builder.WriteString("date_of_birth=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("gender=")
	builder.WriteString(_m.Gender)
	builder.WriteString(", ")
	builder.WriteString("contact_number=")
	builder.WriteString(_m.ContactNumber)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("is_email_verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEmailVerified))
	builder.WriteString(", ")
	builder.WriteString("highest_qualification=")
	builder.WriteString(_m.HighestQualification)
	builder.WriteString(", ")
	builder.WriteString("institution=")
	builder.WriteString(_m.Institution)
	builder.WriteString(", ")
	builder.WriteString("skills=")
	builder.WriteString(_m.Skills)
	builder.WriteString(", ")
	builder.WriteString("linkedin_profile=")
	builder.WriteString(_m.LinkedinProfile)
	builder.WriteString(", ")
	builder.WriteString("github_profile=")
	builder.WriteString(_m.GithubProfile)
	builder.WriteString(", ")
	builder.WriteString("instructor_rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstructorRating))
	builder.WriteString(", ")
	builder.WriteString("total_reviews=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalReviews))
	builder.WriteString(", ")
	builder.WriteString("is_active_user=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActiveUser))
	builder.WriteString(", ")
	if v := _m.LastActivity; v != nil {
		builder.WriteString("last_activity=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("login_address=")
	builder.WriteString(_m.LoginAddress)
	builder.WriteString(", ")
	builder.WriteString("two_factor_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.TwoFactorEnabled))
	builder.WriteString(", ")
	builder.WriteString("is_staff=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsStaff))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("is_superuser=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSuperuser))
	builder.WriteString(", ")
	if v := _m.LastLogin; v != nil {
		builder.WriteString("last_login=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("date_joined=")
	builder.WriteString(_m.DateJoined.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.Verified))
	builder.WriteString(", ")
	builder.WriteString("admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.Admin))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("otp_code=")
	builder.WriteString(_m.OtpCode)
	builder.WriteString(", ")
	builder.WriteString("otp_expires_at=")
	builder.WriteString(_m.OtpExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
