// Code generated by ent, DO NOT EDIT.

package enrollment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the enrollment type in the database.
	Label = "enrollment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEnrolledAt holds the string denoting the enrolled_at field in the database.
	FieldEnrolledAt = "enrolled_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldIsCompleted holds the string denoting the is_completed field in the database.
	FieldIsCompleted = "is_completed"
	// EdgeStudent holds the string denoting the student edge name in mutations.
	EdgeStudent = "student"
	// EdgeCourse holds the string denoting the course edge name in mutations.
	EdgeCourse = "course"
	// EdgeCertificate holds the string denoting the certificate edge name in mutations.
	EdgeCertificate = "certificate"
	// Table holds the table name of the enrollment in the database.
	Table = "Enrollment_enrollment"
	// StudentTable is the table that holds the student relation/edge.
	StudentTable = "Enrollment_enrollment"
	// StudentInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	StudentInverseTable = "Account_customuser"
	// StudentColumn is the table column denoting the student relation/edge.
	StudentColumn = "user_enrollments"
	// CourseTable is the table that holds the course relation/edge.
	CourseTable = "Enrollment_enrollment"
	// CourseInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	CourseInverseTable = "courses_course"
	// CourseColumn is the table column denoting the course relation/edge.
	CourseColumn = "course_enrollments"
	// CertificateTable is the table that holds the certificate relation/edge.
	CertificateTable = "Certificate_certificate"
	// CertificateInverseTable is the table name for the Certificate entity.
	// It exists in this package in order to avoid circular dependency with the "certificate" package.
	CertificateInverseTable = "Certificate_certificate"
	// CertificateColumn is the table column denoting the certificate relation/edge.
	CertificateColumn = "enrollment_certificate"
)

// Columns holds all SQL columns for enrollment fields.
var Columns = []string{
	FieldID,
	FieldEnrolledAt,
	FieldCompletedAt,
	FieldProgress,
	FieldIsCompleted,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "Enrollment_enrollment"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"course_enrollments",
	"user_enrollments",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnrolledAt holds the default value on creation for the "enrolled_at" field.
	DefaultEnrolledAt func() time.Time
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress float64
	// DefaultIsCompleted holds the default value on creation for the "is_completed" field.
	DefaultIsCompleted bool
)

// OrderOption defines the ordering options for the Enrollment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEnrolledAt orders the results by the enrolled_at field.
func ByEnrolledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnrolledAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByIsCompleted orders the results by the is_completed field.
func ByIsCompleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCompleted, opts...).ToFunc()
}

// ByStudentField orders the results by student field.
func ByStudentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStudentStep(), sql.OrderByField(field, opts...))
	}
}

// ByCourseField orders the results by course field.
func ByCourseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCourseStep(), sql.OrderByField(field, opts...))
	}
}

// ByCertificateField orders the results by certificate field.
func ByCertificateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCertificateStep(), sql.OrderByField(field, opts...))
	}
}
func newStudentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StudentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StudentTable, StudentColumn),
	)
}
func newCourseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CourseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CourseTable, CourseColumn),
	)
}
func newCertificateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CertificateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, CertificateTable, CertificateColumn),
	)
}
