// Code generated by ent, DO NOT EDIT.

package enrollment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SHP-Association/E-learningWeb/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldLTE(FieldID, id))
}

// EnrolledAt applies equality check predicate on the "enrolled_at" field. It's identical to EnrolledAtEQ.
func EnrolledAt(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldEnrolledAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldCompletedAt, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v float64) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldProgress, v))
}

// IsCompleted applies equality check predicate on the "is_completed" field. It's identical to IsCompletedEQ.
func IsCompleted(v bool) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldIsCompleted, v))
}

// EnrolledAtEQ applies the EQ predicate on the "enrolled_at" field.
func EnrolledAtEQ(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldEnrolledAt, v))
}

// EnrolledAtNEQ applies the NEQ predicate on the "enrolled_at" field.
func EnrolledAtNEQ(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNEQ(FieldEnrolledAt, v))
}

// EnrolledAtIn applies the In predicate on the "enrolled_at" field.
func EnrolledAtIn(vs ...time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldIn(FieldEnrolledAt, vs...))
}

// EnrolledAtNotIn applies the NotIn predicate on the "enrolled_at" field.
func EnrolledAtNotIn(vs ...time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNotIn(FieldEnrolledAt, vs...))
}

// EnrolledAtGT applies the GT predicate on the "enrolled_at" field.
func EnrolledAtGT(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldGT(FieldEnrolledAt, v))
}

// EnrolledAtGTE applies the GTE predicate on the "enrolled_at" field.
func EnrolledAtGTE(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldGTE(FieldEnrolledAt, v))
}

// EnrolledAtLT applies the LT predicate on the "enrolled_at" field.
func EnrolledAtLT(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldLT(FieldEnrolledAt, v))
}

// EnrolledAtLTE applies the LTE predicate on the "enrolled_at" field.
func EnrolledAtLTE(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldLTE(FieldEnrolledAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Enrollment {
	return predicate.Enrollment(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNotNull(FieldCompletedAt))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v float64) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v float64) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...float64) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...float64) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v float64) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v float64) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v float64) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v float64) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldLTE(FieldProgress, v))
}

// IsCompletedEQ applies the EQ predicate on the "is_completed" field.
func IsCompletedEQ(v bool) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldEQ(FieldIsCompleted, v))
}

// IsCompletedNEQ applies the NEQ predicate on the "is_completed" field.
func IsCompletedNEQ(v bool) predicate.Enrollment {
	return predicate.Enrollment(sql.FieldNEQ(FieldIsCompleted, v))
}

// HasStudent applies the HasEdge predicate on the "student" edge.
func HasStudent() predicate.Enrollment {
	return predicate.Enrollment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StudentTable, StudentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStudentWith applies the HasEdge predicate on the "student" edge with a given conditions (other predicates).
func HasStudentWith(preds ...predicate.User) predicate.Enrollment {
	return predicate.Enrollment(func(s *sql.Selector) {
		step := newStudentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCourse applies the HasEdge predicate on the "course" edge.
func HasCourse() predicate.Enrollment {
	return predicate.Enrollment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CourseTable, CourseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCourseWith applies the HasEdge predicate on the "course" edge with a given conditions (other predicates).
func HasCourseWith(preds ...predicate.Course) predicate.Enrollment {
	return predicate.Enrollment(func(s *sql.Selector) {
		step := newCourseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCertificate applies the HasEdge predicate on the "certificate" edge.
func HasCertificate() predicate.Enrollment {
	return predicate.Enrollment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, CertificateTable, CertificateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCertificateWith applies the HasEdge predicate on the "certificate" edge with a given conditions (other predicates).
func HasCertificateWith(preds ...predicate.Certificate) predicate.Enrollment {
	return predicate.Enrollment(func(s *sql.Selector) {
		step := newCertificateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Enrollment) predicate.Enrollment {
	return predicate.Enrollment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Enrollment) predicate.Enrollment {
	return predicate.Enrollment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Enrollment) predicate.Enrollment {
	return predicate.Enrollment(sql.NotPredicates(p))
}
