// Code generated by ent, DO NOT EDIT.
package admin

import (
	"fmt"
	"net/url"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/labstack/echo/v4"

	"github.com/SHP-Association/E-learningWeb/backend/ent"
	"github.com/SHP-Association/E-learningWeb/backend/ent/answerchoice"
	"github.com/SHP-Association/E-learningWeb/backend/ent/category"
	"github.com/SHP-Association/E-learningWeb/backend/ent/certificate"
	"github.com/SHP-Association/E-learningWeb/backend/ent/course"
	"github.com/SHP-Association/E-learningWeb/backend/ent/enrollment"
	"github.com/SHP-Association/E-learningWeb/backend/ent/faq"
	"github.com/SHP-Association/E-learningWeb/backend/ent/lesson"
	"github.com/SHP-Association/E-learningWeb/backend/ent/passwordtoken"
	"github.com/SHP-Association/E-learningWeb/backend/ent/question"
	"github.com/SHP-Association/E-learningWeb/backend/ent/quiz"
	"github.com/SHP-Association/E-learningWeb/backend/ent/review"
	"github.com/SHP-Association/E-learningWeb/backend/ent/user"
	"github.com/SHP-Association/E-learningWeb/backend/ent/userquizattempt"
)

const dateTimeFormat = "2006-01-02T15:04:05"
const dateTimeFormatNoSeconds = "2006-01-02T15:04"

type Handler struct {
	client *ent.Client
	Config HandlerConfig
}

func NewHandler(client *ent.Client, cfg HandlerConfig) *Handler {
	return &Handler{
		client: client,
		Config: cfg,
	}
}

func (h *Handler) Create(ctx echo.Context, entityType EntityType) error {
	switch entityType.(type) {
	case *AnswerChoice:
		return h.AnswerChoiceCreate(ctx)
	case *Category:
		return h.CategoryCreate(ctx)
	case *Certificate:
		return h.CertificateCreate(ctx)
	case *Course:
		return h.CourseCreate(ctx)
	case *Enrollment:
		return h.EnrollmentCreate(ctx)
	case *FAQ:
		return h.FAQCreate(ctx)
	case *Lesson:
		return h.LessonCreate(ctx)
	case *PasswordToken:
		return h.PasswordTokenCreate(ctx)
	case *Question:
		return h.QuestionCreate(ctx)
	case *Quiz:
		return h.QuizCreate(ctx)
	case *Review:
		return h.ReviewCreate(ctx)
	case *User:
		return h.UserCreate(ctx)
	case *UserQuizAttempt:
		return h.UserQuizAttemptCreate(ctx)
	default:
		return fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) Get(ctx echo.Context, entityType EntityType, id int) (url.Values, error) {
	switch entityType.(type) {
	case *AnswerChoice:
		return h.AnswerChoiceGet(ctx, id)
	case *Category:
		return h.CategoryGet(ctx, id)
	case *Certificate:
		return h.CertificateGet(ctx, id)
	case *Course:
		return h.CourseGet(ctx, id)
	case *Enrollment:
		return h.EnrollmentGet(ctx, id)
	case *FAQ:
		return h.FAQGet(ctx, id)
	case *Lesson:
		return h.LessonGet(ctx, id)
	case *PasswordToken:
		return h.PasswordTokenGet(ctx, id)
	case *Question:
		return h.QuestionGet(ctx, id)
	case *Quiz:
		return h.QuizGet(ctx, id)
	case *Review:
		return h.ReviewGet(ctx, id)
	case *User:
		return h.UserGet(ctx, id)
	case *UserQuizAttempt:
		return h.UserQuizAttemptGet(ctx, id)
	default:
		return nil, fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) Delete(ctx echo.Context, entityType EntityType, id int) error {
	switch entityType.(type) {
	case *AnswerChoice:
		return h.AnswerChoiceDelete(ctx, id)
	case *Category:
		return h.CategoryDelete(ctx, id)
	case *Certificate:
		return h.CertificateDelete(ctx, id)
	case *Course:
		return h.CourseDelete(ctx, id)
	case *Enrollment:
		return h.EnrollmentDelete(ctx, id)
	case *FAQ:
		return h.FAQDelete(ctx, id)
	case *Lesson:
		return h.LessonDelete(ctx, id)
	case *PasswordToken:
		return h.PasswordTokenDelete(ctx, id)
	case *Question:
		return h.QuestionDelete(ctx, id)
	case *Quiz:
		return h.QuizDelete(ctx, id)
	case *Review:
		return h.ReviewDelete(ctx, id)
	case *User:
		return h.UserDelete(ctx, id)
	case *UserQuizAttempt:
		return h.UserQuizAttemptDelete(ctx, id)
	default:
		return fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) Update(ctx echo.Context, entityType EntityType, id int) error {
	switch entityType.(type) {
	case *AnswerChoice:
		return h.AnswerChoiceUpdate(ctx, id)
	case *Category:
		return h.CategoryUpdate(ctx, id)
	case *Certificate:
		return h.CertificateUpdate(ctx, id)
	case *Course:
		return h.CourseUpdate(ctx, id)
	case *Enrollment:
		return h.EnrollmentUpdate(ctx, id)
	case *FAQ:
		return h.FAQUpdate(ctx, id)
	case *Lesson:
		return h.LessonUpdate(ctx, id)
	case *PasswordToken:
		return h.PasswordTokenUpdate(ctx, id)
	case *Question:
		return h.QuestionUpdate(ctx, id)
	case *Quiz:
		return h.QuizUpdate(ctx, id)
	case *Review:
		return h.ReviewUpdate(ctx, id)
	case *User:
		return h.UserUpdate(ctx, id)
	case *UserQuizAttempt:
		return h.UserQuizAttemptUpdate(ctx, id)
	default:
		return fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) List(ctx echo.Context, entityType EntityType) (*EntityList, error) {
	switch entityType.(type) {
	case *AnswerChoice:
		return h.AnswerChoiceList(ctx)
	case *Category:
		return h.CategoryList(ctx)
	case *Certificate:
		return h.CertificateList(ctx)
	case *Course:
		return h.CourseList(ctx)
	case *Enrollment:
		return h.EnrollmentList(ctx)
	case *FAQ:
		return h.FAQList(ctx)
	case *Lesson:
		return h.LessonList(ctx)
	case *PasswordToken:
		return h.PasswordTokenList(ctx)
	case *Question:
		return h.QuestionList(ctx)
	case *Quiz:
		return h.QuizList(ctx)
	case *Review:
		return h.ReviewList(ctx)
	case *User:
		return h.UserList(ctx)
	case *UserQuizAttempt:
		return h.UserQuizAttemptList(ctx)
	default:
		return nil, fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) AnswerChoiceCreate(ctx echo.Context) error {
	var payload AnswerChoice
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.AnswerChoice.Create()
	op.SetChoiceText(payload.ChoiceText)
	op.SetIsCorrect(payload.IsCorrect)
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) AnswerChoiceUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.AnswerChoice.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload AnswerChoice
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetChoiceText(payload.ChoiceText)
	op.SetIsCorrect(payload.IsCorrect)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) AnswerChoiceDelete(ctx echo.Context, id int) error {
	return h.client.AnswerChoice.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) AnswerChoiceList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.AnswerChoice.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(answerchoice.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Choice text",
			"Is correct",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].ChoiceText,
				fmt.Sprint(res[i].IsCorrect),
			},
		})
	}

	return list, err
}

func (h *Handler) AnswerChoiceGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.AnswerChoice.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("choice_text", entity.ChoiceText)
	v.Set("is_correct", fmt.Sprint(entity.IsCorrect))
	return v, err
}

func (h *Handler) CategoryCreate(ctx echo.Context) error {
	var payload Category
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Category.Create()
	op.SetName(payload.Name)
	op.SetSlug(payload.Slug)
	if payload.Description != nil {
		op.SetDescription(*payload.Description)
	}
	if payload.Image != nil {
		op.SetImage(*payload.Image)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CategoryUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Category.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Category
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetName(payload.Name)
	op.SetSlug(payload.Slug)
	if payload.Description == nil {
		op.ClearDescription()
	} else {
		op.SetDescription(*payload.Description)
	}
	if payload.Image == nil {
		op.ClearImage()
	} else {
		op.SetImage(*payload.Image)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CategoryDelete(ctx echo.Context, id int) error {
	return h.client.Category.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) CategoryList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Category.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(category.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Name",
			"Slug",
			"Description",
			"Image",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Name,
				res[i].Slug,
				res[i].Description,
				res[i].Image,
			},
		})
	}

	return list, err
}

func (h *Handler) CategoryGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Category.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("name", entity.Name)
	v.Set("slug", entity.Slug)
	v.Set("description", entity.Description)
	v.Set("image", entity.Image)
	return v, err
}

func (h *Handler) CertificateCreate(ctx echo.Context) error {
	var payload Certificate
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Certificate.Create()
	op.SetUniqueID(payload.UniqueID)
	if payload.IssueDate != nil {
		op.SetIssueDate(*payload.IssueDate)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CertificateUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Certificate.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Certificate
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetUniqueID(payload.UniqueID)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CertificateDelete(ctx echo.Context, id int) error {
	return h.client.Certificate.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) CertificateList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Certificate.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(certificate.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Unique ID",
			"Issue date",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].UniqueID,
				res[i].IssueDate.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) CertificateGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Certificate.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("unique_id", entity.UniqueID)
	return v, err
}

func (h *Handler) CourseCreate(ctx echo.Context) error {
	var payload Course
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Course.Create()
	op.SetTitle(payload.Title)
	op.SetSlug(payload.Slug)
	op.SetShortDescription(payload.ShortDescription)
	op.SetDescription(payload.Description)
	if payload.WhatYouWillLearn != nil {
		op.SetWhatYouWillLearn(*payload.WhatYouWillLearn)
	}
	if payload.Requirements != nil {
		op.SetRequirements(*payload.Requirements)
	}
	if payload.TargetAudience != nil {
		op.SetTargetAudience(*payload.TargetAudience)
	}
	if payload.Thumbnail != nil {
		op.SetThumbnail(*payload.Thumbnail)
	}
	if payload.PromoVideoLink != nil {
		op.SetPromoVideoLink(*payload.PromoVideoLink)
	}
	if payload.Price != nil {
		op.SetPrice(*payload.Price)
	}
	op.SetIsFree(payload.IsFree)
	op.SetIsPublished(payload.IsPublished)
	if payload.Level != nil {
		op.SetLevel(*payload.Level)
	}
	if payload.Duration != nil {
		op.SetDuration(*payload.Duration)
	}
	if payload.TotalLectures != nil {
		op.SetTotalLectures(*payload.TotalLectures)
	}
	if payload.AverageRating != nil {
		op.SetAverageRating(*payload.AverageRating)
	}
	if payload.NumberOfReviews != nil {
		op.SetNumberOfReviews(*payload.NumberOfReviews)
	}
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	if payload.UpdatedAt != nil {
		op.SetUpdatedAt(*payload.UpdatedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CourseUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Course.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Course
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetTitle(payload.Title)
	op.SetSlug(payload.Slug)
	op.SetShortDescription(payload.ShortDescription)
	op.SetDescription(payload.Description)
	if payload.WhatYouWillLearn == nil {
		op.ClearWhatYouWillLearn()
	} else {
		op.SetWhatYouWillLearn(*payload.WhatYouWillLearn)
	}
	if payload.Requirements == nil {
		op.ClearRequirements()
	} else {
		op.SetRequirements(*payload.Requirements)
	}
	if payload.TargetAudience == nil {
		op.ClearTargetAudience()
	} else {
		op.SetTargetAudience(*payload.TargetAudience)
	}
	if payload.Thumbnail == nil {
		op.ClearThumbnail()
	} else {
		op.SetThumbnail(*payload.Thumbnail)
	}
	if payload.PromoVideoLink == nil {
		op.ClearPromoVideoLink()
	} else {
		op.SetPromoVideoLink(*payload.PromoVideoLink)
	}
	if payload.Price == nil {
		var empty float64
		op.SetPrice(empty)
	} else {
		op.SetPrice(*payload.Price)
	}
	op.SetIsFree(payload.IsFree)
	op.SetIsPublished(payload.IsPublished)
	if payload.Level == nil {
		var empty string
		op.SetLevel(empty)
	} else {
		op.SetLevel(*payload.Level)
	}
	if payload.Duration == nil {
		op.ClearDuration()
	} else {
		op.SetDuration(*payload.Duration)
	}
	if payload.TotalLectures == nil {
		var empty int
		op.SetTotalLectures(empty)
	} else {
		op.SetTotalLectures(*payload.TotalLectures)
	}
	if payload.AverageRating == nil {
		var empty float64
		op.SetAverageRating(empty)
	} else {
		op.SetAverageRating(*payload.AverageRating)
	}
	if payload.NumberOfReviews == nil {
		var empty int
		op.SetNumberOfReviews(empty)
	} else {
		op.SetNumberOfReviews(*payload.NumberOfReviews)
	}
	if payload.UpdatedAt == nil {
		var empty time.Time
		op.SetUpdatedAt(empty)
	} else {
		op.SetUpdatedAt(*payload.UpdatedAt)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CourseDelete(ctx echo.Context, id int) error {
	return h.client.Course.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) CourseList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Course.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(course.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Title",
			"Slug",
			"Short description",
			"Description",
			"What you will learn",
			"Requirements",
			"Target audience",
			"Thumbnail",
			"Promo video link",
			"Price",
			"Is free",
			"Is published",
			"Level",
			"Duration",
			"Total lectures",
			"Average rating",
			"Number of reviews",
			"Created at",
			"Updated at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Title,
				res[i].Slug,
				res[i].ShortDescription,
				res[i].Description,
				res[i].WhatYouWillLearn,
				res[i].Requirements,
				res[i].TargetAudience,
				res[i].Thumbnail,
				res[i].PromoVideoLink,
				fmt.Sprint(res[i].Price),
				fmt.Sprint(res[i].IsFree),
				fmt.Sprint(res[i].IsPublished),
				res[i].Level,
				res[i].Duration,
				fmt.Sprint(res[i].TotalLectures),
				fmt.Sprint(res[i].AverageRating),
				fmt.Sprint(res[i].NumberOfReviews),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
				res[i].UpdatedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) CourseGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Course.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("title", entity.Title)
	v.Set("slug", entity.Slug)
	v.Set("short_description", entity.ShortDescription)
	v.Set("description", entity.Description)
	v.Set("what_you_will_learn", entity.WhatYouWillLearn)
	v.Set("requirements", entity.Requirements)
	v.Set("target_audience", entity.TargetAudience)
	v.Set("thumbnail", entity.Thumbnail)
	v.Set("promo_video_link", entity.PromoVideoLink)
	v.Set("price", fmt.Sprint(entity.Price))
	v.Set("is_free", fmt.Sprint(entity.IsFree))
	v.Set("is_published", fmt.Sprint(entity.IsPublished))
	v.Set("level", entity.Level)
	v.Set("duration", entity.Duration)
	v.Set("total_lectures", fmt.Sprint(entity.TotalLectures))
	v.Set("average_rating", fmt.Sprint(entity.AverageRating))
	v.Set("number_of_reviews", fmt.Sprint(entity.NumberOfReviews))
	v.Set("updated_at", entity.UpdatedAt.Format(dateTimeFormat))
	return v, err
}

func (h *Handler) EnrollmentCreate(ctx echo.Context) error {
	var payload Enrollment
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Enrollment.Create()
	if payload.EnrolledAt != nil {
		op.SetEnrolledAt(*payload.EnrolledAt)
	}
	if payload.CompletedAt != nil {
		op.SetCompletedAt(*payload.CompletedAt)
	}
	if payload.Progress != nil {
		op.SetProgress(*payload.Progress)
	}
	op.SetIsCompleted(payload.IsCompleted)
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) EnrollmentUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Enrollment.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Enrollment
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetNillableCompletedAt(payload.CompletedAt)
	if payload.Progress == nil {
		var empty float64
		op.SetProgress(empty)
	} else {
		op.SetProgress(*payload.Progress)
	}
	op.SetIsCompleted(payload.IsCompleted)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) EnrollmentDelete(ctx echo.Context, id int) error {
	return h.client.Enrollment.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) EnrollmentList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Enrollment.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(enrollment.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Enrolled at",
			"Completed at",
			"Progress",
			"Is completed",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].EnrolledAt.Format(h.Config.TimeFormat),
				formatTimePtr(res[i].CompletedAt, h.Config.TimeFormat),
				fmt.Sprint(res[i].Progress),
				fmt.Sprint(res[i].IsCompleted),
			},
		})
	}

	return list, err
}

func (h *Handler) EnrollmentGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Enrollment.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("completed_at", formatTimePtr(entity.CompletedAt, dateTimeFormat))
	v.Set("progress", fmt.Sprint(entity.Progress))
	v.Set("is_completed", fmt.Sprint(entity.IsCompleted))
	return v, err
}

func (h *Handler) FAQCreate(ctx echo.Context) error {
	var payload FAQ
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.FAQ.Create()
	op.SetQuestion(payload.Question)
	op.SetAnswer(payload.Answer)
	op.SetIsPublished(payload.IsPublished)
	if payload.Order != nil {
		op.SetOrder(*payload.Order)
	}
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	if payload.UpdatedAt != nil {
		op.SetUpdatedAt(*payload.UpdatedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) FAQUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.FAQ.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload FAQ
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetQuestion(payload.Question)
	op.SetAnswer(payload.Answer)
	op.SetIsPublished(payload.IsPublished)
	if payload.Order == nil {
		var empty int
		op.SetOrder(empty)
	} else {
		op.SetOrder(*payload.Order)
	}
	if payload.UpdatedAt == nil {
		var empty time.Time
		op.SetUpdatedAt(empty)
	} else {
		op.SetUpdatedAt(*payload.UpdatedAt)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) FAQDelete(ctx echo.Context, id int) error {
	return h.client.FAQ.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) FAQList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.FAQ.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(faq.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Question",
			"Answer",
			"Is published",
			"Order",
			"Created at",
			"Updated at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Question,
				res[i].Answer,
				fmt.Sprint(res[i].IsPublished),
				fmt.Sprint(res[i].Order),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
				res[i].UpdatedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) FAQGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.FAQ.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("question", entity.Question)
	v.Set("answer", entity.Answer)
	v.Set("is_published", fmt.Sprint(entity.IsPublished))
	v.Set("order", fmt.Sprint(entity.Order))
	v.Set("updated_at", entity.UpdatedAt.Format(dateTimeFormat))
	return v, err
}

func (h *Handler) LessonCreate(ctx echo.Context) error {
	var payload Lesson
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Lesson.Create()
	op.SetTitle(payload.Title)
	op.SetSlug(payload.Slug)
	if payload.Content != nil {
		op.SetContent(*payload.Content)
	}
	if payload.VideoLink != nil {
		op.SetVideoLink(*payload.VideoLink)
	}
	op.SetOrder(payload.Order)
	op.SetIsPreview(payload.IsPreview)
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	if payload.UpdatedAt != nil {
		op.SetUpdatedAt(*payload.UpdatedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) LessonUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Lesson.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Lesson
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetTitle(payload.Title)
	op.SetSlug(payload.Slug)
	if payload.Content == nil {
		op.ClearContent()
	} else {
		op.SetContent(*payload.Content)
	}
	if payload.VideoLink == nil {
		op.ClearVideoLink()
	} else {
		op.SetVideoLink(*payload.VideoLink)
	}
	op.SetOrder(payload.Order)
	op.SetIsPreview(payload.IsPreview)
	if payload.UpdatedAt == nil {
		var empty time.Time
		op.SetUpdatedAt(empty)
	} else {
		op.SetUpdatedAt(*payload.UpdatedAt)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) LessonDelete(ctx echo.Context, id int) error {
	return h.client.Lesson.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) LessonList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Lesson.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(lesson.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Title",
			"Slug",
			"Content",
			"Video link",
			"Order",
			"Is preview",
			"Created at",
			"Updated at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Title,
				res[i].Slug,
				res[i].Content,
				res[i].VideoLink,
				fmt.Sprint(res[i].Order),
				fmt.Sprint(res[i].IsPreview),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
				res[i].UpdatedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) LessonGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Lesson.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("title", entity.Title)
	v.Set("slug", entity.Slug)
	v.Set("content", entity.Content)
	v.Set("video_link", entity.VideoLink)
	v.Set("order", fmt.Sprint(entity.Order))
	v.Set("is_preview", fmt.Sprint(entity.IsPreview))
	v.Set("updated_at", entity.UpdatedAt.Format(dateTimeFormat))
	return v, err
}

func (h *Handler) PasswordTokenCreate(ctx echo.Context) error {
	var payload PasswordToken
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.PasswordToken.Create()
	if payload.Token != nil {
		op.SetToken(*payload.Token)
	}
	op.SetUserID(payload.UserID)
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) PasswordTokenUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.PasswordToken.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload PasswordToken
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	if payload.Token != nil {
		op.SetToken(*payload.Token)
	}
	op.SetUserID(payload.UserID)
	if payload.CreatedAt == nil {
		var empty time.Time
		op.SetCreatedAt(empty)
	} else {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) PasswordTokenDelete(ctx echo.Context, id int) error {
	return h.client.PasswordToken.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) PasswordTokenList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.PasswordToken.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(passwordtoken.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"User ID",
			"Created at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				fmt.Sprint(res[i].UserID),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) PasswordTokenGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.PasswordToken.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("user_id", fmt.Sprint(entity.UserID))
	v.Set("created_at", entity.CreatedAt.Format(dateTimeFormat))
	return v, err
}

func (h *Handler) QuestionCreate(ctx echo.Context) error {
	var payload Question
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Question.Create()
	op.SetQuestionText(payload.QuestionText)
	if payload.QuestionType != nil {
		op.SetQuestionType(*payload.QuestionType)
	}
	if payload.Order != nil {
		op.SetOrder(*payload.Order)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) QuestionUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Question.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Question
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetQuestionText(payload.QuestionText)
	if payload.QuestionType == nil {
		var empty string
		op.SetQuestionType(empty)
	} else {
		op.SetQuestionType(*payload.QuestionType)
	}
	if payload.Order == nil {
		var empty int
		op.SetOrder(empty)
	} else {
		op.SetOrder(*payload.Order)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) QuestionDelete(ctx echo.Context, id int) error {
	return h.client.Question.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) QuestionList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Question.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(question.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Question text",
			"Question type",
			"Order",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].QuestionText,
				res[i].QuestionType,
				fmt.Sprint(res[i].Order),
			},
		})
	}

	return list, err
}

func (h *Handler) QuestionGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Question.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("question_text", entity.QuestionText)
	v.Set("question_type", entity.QuestionType)
	v.Set("order", fmt.Sprint(entity.Order))
	return v, err
}

func (h *Handler) QuizCreate(ctx echo.Context) error {
	var payload Quiz
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Quiz.Create()
	op.SetTitle(payload.Title)
	if payload.Description != nil {
		op.SetDescription(*payload.Description)
	}
	if payload.PassingScore != nil {
		op.SetPassingScore(*payload.PassingScore)
	}
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	if payload.UpdatedAt != nil {
		op.SetUpdatedAt(*payload.UpdatedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) QuizUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Quiz.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Quiz
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetTitle(payload.Title)
	if payload.Description == nil {
		op.ClearDescription()
	} else {
		op.SetDescription(*payload.Description)
	}
	if payload.PassingScore == nil {
		var empty int
		op.SetPassingScore(empty)
	} else {
		op.SetPassingScore(*payload.PassingScore)
	}
	if payload.UpdatedAt == nil {
		var empty time.Time
		op.SetUpdatedAt(empty)
	} else {
		op.SetUpdatedAt(*payload.UpdatedAt)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) QuizDelete(ctx echo.Context, id int) error {
	return h.client.Quiz.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) QuizList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Quiz.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(quiz.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Title",
			"Description",
			"Passing score",
			"Created at",
			"Updated at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Title,
				res[i].Description,
				fmt.Sprint(res[i].PassingScore),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
				res[i].UpdatedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) QuizGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Quiz.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("title", entity.Title)
	v.Set("description", entity.Description)
	v.Set("passing_score", fmt.Sprint(entity.PassingScore))
	v.Set("updated_at", entity.UpdatedAt.Format(dateTimeFormat))
	return v, err
}

func (h *Handler) ReviewCreate(ctx echo.Context) error {
	var payload Review
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Review.Create()
	op.SetRating(payload.Rating)
	if payload.Comment != nil {
		op.SetComment(*payload.Comment)
	}
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	op.SetIsApproved(payload.IsApproved)
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) ReviewUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Review.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Review
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetRating(payload.Rating)
	if payload.Comment == nil {
		op.ClearComment()
	} else {
		op.SetComment(*payload.Comment)
	}
	op.SetIsApproved(payload.IsApproved)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) ReviewDelete(ctx echo.Context, id int) error {
	return h.client.Review.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) ReviewList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Review.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(review.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Rating",
			"Comment",
			"Created at",
			"Is approved",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				fmt.Sprint(res[i].Rating),
				res[i].Comment,
				res[i].CreatedAt.Format(h.Config.TimeFormat),
				fmt.Sprint(res[i].IsApproved),
			},
		})
	}

	return list, err
}

func (h *Handler) ReviewGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Review.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("rating", fmt.Sprint(entity.Rating))
	v.Set("comment", entity.Comment)
	v.Set("is_approved", fmt.Sprint(entity.IsApproved))
	return v, err
}

func (h *Handler) UserCreate(ctx echo.Context) error {
	var payload User
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.User.Create()
	op.SetUsername(payload.Username)
	if payload.FirstName != nil {
		op.SetFirstName(*payload.FirstName)
	}
	if payload.LastName != nil {
		op.SetLastName(*payload.LastName)
	}
	op.SetEmail(payload.Email)
	if payload.Password != nil {
		op.SetPassword(*payload.Password)
	}
	if payload.Role != nil {
		op.SetRole(*payload.Role)
	}
	if payload.Bio != nil {
		op.SetBio(*payload.Bio)
	}
	if payload.ProfilePicture != nil {
		op.SetProfilePicture(*payload.ProfilePicture)
	}
	if payload.DateOfBirth != nil {
		op.SetDateOfBirth(*payload.DateOfBirth)
	}
	if payload.Gender != nil {
		op.SetGender(*payload.Gender)
	}
	if payload.ContactNumber != nil {
		op.SetContactNumber(*payload.ContactNumber)
	}
	if payload.Address != nil {
		op.SetAddress(*payload.Address)
	}
	if payload.Country != nil {
		op.SetCountry(*payload.Country)
	}
	op.SetIsEmailVerified(payload.IsEmailVerified)
	if payload.HighestQualification != nil {
		op.SetHighestQualification(*payload.HighestQualification)
	}
	if payload.Institution != nil {
		op.SetInstitution(*payload.Institution)
	}
	if payload.Skills != nil {
		op.SetSkills(*payload.Skills)
	}
	if payload.LinkedinProfile != nil {
		op.SetLinkedinProfile(*payload.LinkedinProfile)
	}
	if payload.GithubProfile != nil {
		op.SetGithubProfile(*payload.GithubProfile)
	}
	if payload.InstructorRating != nil {
		op.SetInstructorRating(*payload.InstructorRating)
	}
	if payload.TotalReviews != nil {
		op.SetTotalReviews(*payload.TotalReviews)
	}
	op.SetIsActiveUser(payload.IsActiveUser)
	if payload.LastActivity != nil {
		op.SetLastActivity(*payload.LastActivity)
	}
	if payload.LoginAddress != nil {
		op.SetLoginAddress(*payload.LoginAddress)
	}
	op.SetTwoFactorEnabled(payload.TwoFactorEnabled)
	op.SetIsStaff(payload.IsStaff)
	op.SetIsActive(payload.IsActive)
	op.SetIsSuperuser(payload.IsSuperuser)
	if payload.LastLogin != nil {
		op.SetLastLogin(*payload.LastLogin)
	}
	if payload.DateJoined != nil {
		op.SetDateJoined(*payload.DateJoined)
	}
	op.SetVerified(payload.Verified)
	op.SetAdmin(payload.Admin)
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) UserUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.User.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload User
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetUsername(payload.Username)
	if payload.FirstName == nil {
		op.ClearFirstName()
	} else {
		op.SetFirstName(*payload.FirstName)
	}
	if payload.LastName == nil {
		op.ClearLastName()
	} else {
		op.SetLastName(*payload.LastName)
	}
	op.SetEmail(payload.Email)
	if payload.Password != nil {
		op.SetPassword(*payload.Password)
	}
	if payload.Role == nil {
		var empty string
		op.SetRole(empty)
	} else {
		op.SetRole(*payload.Role)
	}
	if payload.Bio == nil {
		op.ClearBio()
	} else {
		op.SetBio(*payload.Bio)
	}
	if payload.ProfilePicture == nil {
		op.ClearProfilePicture()
	} else {
		op.SetProfilePicture(*payload.ProfilePicture)
	}
	op.SetNillableDateOfBirth(payload.DateOfBirth)
	if payload.Gender == nil {
		op.ClearGender()
	} else {
		op.SetGender(*payload.Gender)
	}
	if payload.ContactNumber == nil {
		op.ClearContactNumber()
	} else {
		op.SetContactNumber(*payload.ContactNumber)
	}
	if payload.Address == nil {
		op.ClearAddress()
	} else {
		op.SetAddress(*payload.Address)
	}
	if payload.Country == nil {
		op.ClearCountry()
	} else {
		op.SetCountry(*payload.Country)
	}
	op.SetIsEmailVerified(payload.IsEmailVerified)
	if payload.HighestQualification == nil {
		op.ClearHighestQualification()
	} else {
		op.SetHighestQualification(*payload.HighestQualification)
	}
	if payload.Institution == nil {
		op.ClearInstitution()
	} else {
		op.SetInstitution(*payload.Institution)
	}
	if payload.Skills == nil {
		op.ClearSkills()
	} else {
		op.SetSkills(*payload.Skills)
	}
	if payload.LinkedinProfile == nil {
		op.ClearLinkedinProfile()
	} else {
		op.SetLinkedinProfile(*payload.LinkedinProfile)
	}
	if payload.GithubProfile == nil {
		op.ClearGithubProfile()
	} else {
		op.SetGithubProfile(*payload.GithubProfile)
	}
	if payload.InstructorRating == nil {
		var empty float64
		op.SetInstructorRating(empty)
	} else {
		op.SetInstructorRating(*payload.InstructorRating)
	}
	if payload.TotalReviews == nil {
		var empty int
		op.SetTotalReviews(empty)
	} else {
		op.SetTotalReviews(*payload.TotalReviews)
	}
	op.SetIsActiveUser(payload.IsActiveUser)
	op.SetNillableLastActivity(payload.LastActivity)
	if payload.LoginAddress == nil {
		op.ClearLoginAddress()
	} else {
		op.SetLoginAddress(*payload.LoginAddress)
	}
	op.SetTwoFactorEnabled(payload.TwoFactorEnabled)
	op.SetIsStaff(payload.IsStaff)
	op.SetIsActive(payload.IsActive)
	op.SetIsSuperuser(payload.IsSuperuser)
	op.SetNillableLastLogin(payload.LastLogin)
	op.SetVerified(payload.Verified)
	op.SetAdmin(payload.Admin)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) UserDelete(ctx echo.Context, id int) error {
	return h.client.User.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) UserList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.User.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(user.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Username",
			"First name",
			"Last name",
			"Email",
			"Role",
			"Bio",
			"Profile picture",
			"Date of birth",
			"Gender",
			"Contact number",
			"Address",
			"Country",
			"Is email verified",
			"Highest qualification",
			"Institution",
			"Skills",
			"Linkedin profile",
			"Github profile",
			"Instructor rating",
			"Total reviews",
			"Is active user",
			"Last activity",
			"Login address",
			"Two factor enabled",
			"Is staff",
			"Is active",
			"Is superuser",
			"Last login",
			"Date joined",
			"Verified",
			"Admin",
			"Created at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Username,
				res[i].FirstName,
				res[i].LastName,
				res[i].Email,
				res[i].Role,
				res[i].Bio,
				res[i].ProfilePicture,
				formatTimePtr(res[i].DateOfBirth, h.Config.TimeFormat),
				res[i].Gender,
				res[i].ContactNumber,
				res[i].Address,
				res[i].Country,
				fmt.Sprint(res[i].IsEmailVerified),
				res[i].HighestQualification,
				res[i].Institution,
				res[i].Skills,
				res[i].LinkedinProfile,
				res[i].GithubProfile,
				fmt.Sprint(res[i].InstructorRating),
				fmt.Sprint(res[i].TotalReviews),
				fmt.Sprint(res[i].IsActiveUser),
				formatTimePtr(res[i].LastActivity, h.Config.TimeFormat),
				res[i].LoginAddress,
				fmt.Sprint(res[i].TwoFactorEnabled),
				fmt.Sprint(res[i].IsStaff),
				fmt.Sprint(res[i].IsActive),
				fmt.Sprint(res[i].IsSuperuser),
				formatTimePtr(res[i].LastLogin, h.Config.TimeFormat),
				res[i].DateJoined.Format(h.Config.TimeFormat),
				fmt.Sprint(res[i].Verified),
				fmt.Sprint(res[i].Admin),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) UserGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.User.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("username", entity.Username)
	v.Set("first_name", entity.FirstName)
	v.Set("last_name", entity.LastName)
	v.Set("email", entity.Email)
	v.Set("role", entity.Role)
	v.Set("bio", entity.Bio)
	v.Set("profile_picture", entity.ProfilePicture)
	v.Set("date_of_birth", formatTimePtr(entity.DateOfBirth, dateTimeFormat))
	v.Set("gender", entity.Gender)
	v.Set("contact_number", entity.ContactNumber)
	v.Set("address", entity.Address)
	v.Set("country", entity.Country)
	v.Set("is_email_verified", fmt.Sprint(entity.IsEmailVerified))
	v.Set("highest_qualification", entity.HighestQualification)
	v.Set("institution", entity.Institution)
	v.Set("skills", entity.Skills)
	v.Set("linkedin_profile", entity.LinkedinProfile)
	v.Set("github_profile", entity.GithubProfile)
	v.Set("instructor_rating", fmt.Sprint(entity.InstructorRating))
	v.Set("total_reviews", fmt.Sprint(entity.TotalReviews))
	v.Set("is_active_user", fmt.Sprint(entity.IsActiveUser))
	v.Set("last_activity", formatTimePtr(entity.LastActivity, dateTimeFormat))
	v.Set("login_address", entity.LoginAddress)
	v.Set("two_factor_enabled", fmt.Sprint(entity.TwoFactorEnabled))
	v.Set("is_staff", fmt.Sprint(entity.IsStaff))
	v.Set("is_active", fmt.Sprint(entity.IsActive))
	v.Set("is_superuser", fmt.Sprint(entity.IsSuperuser))
	v.Set("last_login", formatTimePtr(entity.LastLogin, dateTimeFormat))
	v.Set("verified", fmt.Sprint(entity.Verified))
	v.Set("admin", fmt.Sprint(entity.Admin))
	return v, err
}

func (h *Handler) UserQuizAttemptCreate(ctx echo.Context) error {
	var payload UserQuizAttempt
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.UserQuizAttempt.Create()
	if payload.Score != nil {
		op.SetScore(*payload.Score)
	}
	op.SetPassed(payload.Passed)
	if payload.AttemptNumber != nil {
		op.SetAttemptNumber(*payload.AttemptNumber)
	}
	if payload.SubmittedAt != nil {
		op.SetSubmittedAt(*payload.SubmittedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) UserQuizAttemptUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.UserQuizAttempt.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload UserQuizAttempt
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	if payload.Score == nil {
		var empty float64
		op.SetScore(empty)
	} else {
		op.SetScore(*payload.Score)
	}
	op.SetPassed(payload.Passed)
	if payload.AttemptNumber == nil {
		var empty int
		op.SetAttemptNumber(empty)
	} else {
		op.SetAttemptNumber(*payload.AttemptNumber)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) UserQuizAttemptDelete(ctx echo.Context, id int) error {
	return h.client.UserQuizAttempt.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) UserQuizAttemptList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.UserQuizAttempt.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(userquizattempt.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Score",
			"Passed",
			"Attempt number",
			"Submitted at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				fmt.Sprint(res[i].Score),
				fmt.Sprint(res[i].Passed),
				fmt.Sprint(res[i].AttemptNumber),
				res[i].SubmittedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) UserQuizAttemptGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.UserQuizAttempt.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("score", fmt.Sprint(entity.Score))
	v.Set("passed", fmt.Sprint(entity.Passed))
	v.Set("attempt_number", fmt.Sprint(entity.AttemptNumber))
	return v, err
}

func (h *Handler) getPageAndOffset(ctx echo.Context) (int, int) {
	if page, err := strconv.Atoi(ctx.QueryParam(h.Config.PageQueryKey)); err == nil {
		if page > 1 {
			return page, (page - 1) * h.Config.ItemsPerPage
		}
	}
	return 1, 0
}

func (h *Handler) bind(ctx echo.Context, entity any) error {
	// Echo requires some pre-processing of form values to avoid problems.
	for k, v := range ctx.Request().Form {
		// Remove empty field values so Echo's bind does not fail when trying to parse things like
		// times, etc.
		if len(v) == 1 && len(v[0]) == 0 {
			delete(ctx.Request().Form, k)
			continue
		}

		// Echo expects datetime values to be in a certain format but that does not align with the datetime-local
		// HTML form element format, so we will attempt to convert it here.
		for _, format := range []string{dateTimeFormatNoSeconds, dateTimeFormat} {
			if t, err := time.Parse(format, v[0]); err == nil {
				ctx.Request().Form[k][0] = t.Format(time.RFC3339)
				break
			}
		}
	}
	return ctx.Bind(entity)
}

func formatTimePtr(t *time.Time, layout string) string {
	if t == nil {
		return ""
	}
	return t.Format(layout)
}

