// Code generated by ent, DO NOT EDIT.
package admin

import (
	"entgo.io/ent/schema/field"
)

type Enum struct {
	Label, Value string
}

type FieldSchema struct {
	Name      string
	Type      field.Type
	Optional  bool
	Immutable bool
	Sensitive bool
	Enums     []string
}

const NameAnswerChoice = "AnswerChoice"

var fieldsAnswerChoice = []*FieldSchema{
	{
		Name:      "choice_text",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_correct",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameCategory = "Category"

var fieldsCategory = []*FieldSchema{
	{
		Name:      "name",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "slug",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "description",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "image",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameCertificate = "Certificate"

var fieldsCertificate = []*FieldSchema{
	{
		Name:      "unique_id",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "issue_date",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameCourse = "Course"

var fieldsCourse = []*FieldSchema{
	{
		Name:      "title",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "slug",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "short_description",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "description",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "what_you_will_learn",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "requirements",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "target_audience",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "thumbnail",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "promo_video_link",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "price",
		Type:      field.TypeFloat64,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_free",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_published",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "level",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "duration",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "total_lectures",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "average_rating",
		Type:      field.TypeFloat64,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "number_of_reviews",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "updated_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameEnrollment = "Enrollment"

var fieldsEnrollment = []*FieldSchema{
	{
		Name:      "enrolled_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "completed_at",
		Type:      field.TypeTime,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "progress",
		Type:      field.TypeFloat64,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_completed",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameFAQ = "FAQ"

var fieldsFAQ = []*FieldSchema{
	{
		Name:      "question",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "answer",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_published",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "order",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "updated_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameLesson = "Lesson"

var fieldsLesson = []*FieldSchema{
	{
		Name:      "title",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "slug",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "content",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "video_link",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "order",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_preview",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "updated_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NamePasswordToken = "PasswordToken"

var fieldsPasswordToken = []*FieldSchema{
	{
		Name:      "token",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: true,
		Enums:     nil,
	},
	{
		Name:      "user_id",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameQuestion = "Question"

var fieldsQuestion = []*FieldSchema{
	{
		Name:      "question_text",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "question_type",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "order",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameQuiz = "Quiz"

var fieldsQuiz = []*FieldSchema{
	{
		Name:      "title",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "description",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "passing_score",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "updated_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameReview = "Review"

var fieldsReview = []*FieldSchema{
	{
		Name:      "rating",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "comment",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_approved",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameUser = "User"

var fieldsUser = []*FieldSchema{
	{
		Name:      "username",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "first_name",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "last_name",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "email",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "password",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: true,
		Enums:     nil,
	},
	{
		Name:      "role",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "bio",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "profile_picture",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "date_of_birth",
		Type:      field.TypeTime,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "gender",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "contact_number",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "address",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "country",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_email_verified",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "highest_qualification",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "institution",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "skills",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "linkedin_profile",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "github_profile",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "instructor_rating",
		Type:      field.TypeFloat64,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "total_reviews",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_active_user",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "last_activity",
		Type:      field.TypeTime,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "login_address",
		Type:      field.TypeString,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "two_factor_enabled",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_staff",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_active",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "is_superuser",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "last_login",
		Type:      field.TypeTime,
		Optional:  true,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "date_joined",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "verified",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "admin",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameUserQuizAttempt = "UserQuizAttempt"

var fieldsUserQuizAttempt = []*FieldSchema{
	{
		Name:      "score",
		Type:      field.TypeFloat64,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "passed",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "attempt_number",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "submitted_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
}
