// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// QuestionAnswerchoiceColumns holds the columns for the "Question_answerchoice" table.
	QuestionAnswerchoiceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "choice_text", Type: field.TypeString, Size: 500},
		{Name: "is_correct", Type: field.TypeBool, Default: false},
		{Name: "question_choices", Type: field.TypeInt},
	}
	// QuestionAnswerchoiceTable holds the schema information for the "Question_answerchoice" table.
	QuestionAnswerchoiceTable = &schema.Table{
		Name:       "Question_answerchoice",
		Columns:    QuestionAnswerchoiceColumns,
		PrimaryKey: []*schema.Column{QuestionAnswerchoiceColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Question_answerchoice_Question_question_choices",
				Columns:    []*schema.Column{QuestionAnswerchoiceColumns[3]},
				RefColumns: []*schema.Column{QuestionQuestionColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CategoryCategoryColumns holds the columns for the "Category_category" table.
	CategoryCategoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "image", Type: field.TypeString, Nullable: true},
	}
	// CategoryCategoryTable holds the schema information for the "Category_category" table.
	CategoryCategoryTable = &schema.Table{
		Name:       "Category_category",
		Columns:    CategoryCategoryColumns,
		PrimaryKey: []*schema.Column{CategoryCategoryColumns[0]},
	}
	// CertificateCertificateColumns holds the columns for the "Certificate_certificate" table.
	CertificateCertificateColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "unique_id", Type: field.TypeString, Unique: true},
		{Name: "issue_date", Type: field.TypeTime},
		{Name: "enrollment_certificate", Type: field.TypeInt, Unique: true},
	}
	// CertificateCertificateTable holds the schema information for the "Certificate_certificate" table.
	CertificateCertificateTable = &schema.Table{
		Name:       "Certificate_certificate",
		Columns:    CertificateCertificateColumns,
		PrimaryKey: []*schema.Column{CertificateCertificateColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Certificate_certificate_Enrollment_enrollment_certificate",
				Columns:    []*schema.Column{CertificateCertificateColumns[3]},
				RefColumns: []*schema.Column{EnrollmentEnrollmentColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CoursesCourseColumns holds the columns for the "courses_course" table.
	CoursesCourseColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 200},
		{Name: "short_description", Type: field.TypeString, Size: 500},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "what_you_will_learn", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "requirements", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "target_audience", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "thumbnail", Type: field.TypeString, Nullable: true},
		{Name: "promo_video_url", Type: field.TypeString, Nullable: true},
		{Name: "price", Type: field.TypeFloat64, Default: 0},
		{Name: "is_free", Type: field.TypeBool, Default: false},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "level", Type: field.TypeString, Default: "beginner"},
		{Name: "duration", Type: field.TypeString, Nullable: true},
		{Name: "total_lectures", Type: field.TypeInt, Default: 0},
		{Name: "average_rating", Type: field.TypeFloat64, Default: 0},
		{Name: "number_of_reviews", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "category_courses", Type: field.TypeInt, Nullable: true},
		{Name: "user_taught_courses", Type: field.TypeInt, Nullable: true},
	}
	// CoursesCourseTable holds the schema information for the "courses_course" table.
	CoursesCourseTable = &schema.Table{
		Name:       "courses_course",
		Columns:    CoursesCourseColumns,
		PrimaryKey: []*schema.Column{CoursesCourseColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "courses_course_Category_category_courses",
				Columns:    []*schema.Column{CoursesCourseColumns[20]},
				RefColumns: []*schema.Column{CategoryCategoryColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "courses_course_Account_customuser_taught_courses",
				Columns:    []*schema.Column{CoursesCourseColumns[21]},
				RefColumns: []*schema.Column{AccountCustomuserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EnrollmentEnrollmentColumns holds the columns for the "Enrollment_enrollment" table.
	EnrollmentEnrollmentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "enrolled_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "progress", Type: field.TypeFloat64, Default: 0},
		{Name: "is_completed", Type: field.TypeBool, Default: false},
		{Name: "course_enrollments", Type: field.TypeInt},
		{Name: "user_enrollments", Type: field.TypeInt},
	}
	// EnrollmentEnrollmentTable holds the schema information for the "Enrollment_enrollment" table.
	EnrollmentEnrollmentTable = &schema.Table{
		Name:       "Enrollment_enrollment",
		Columns:    EnrollmentEnrollmentColumns,
		PrimaryKey: []*schema.Column{EnrollmentEnrollmentColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Enrollment_enrollment_courses_course_enrollments",
				Columns:    []*schema.Column{EnrollmentEnrollmentColumns[5]},
				RefColumns: []*schema.Column{CoursesCourseColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "Enrollment_enrollment_Account_customuser_enrollments",
				Columns:    []*schema.Column{EnrollmentEnrollmentColumns[6]},
				RefColumns: []*schema.Column{AccountCustomuserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// FAQFaqColumns holds the columns for the "FAQ_faq" table.
	FAQFaqColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "question", Type: field.TypeString, Size: 2147483647},
		{Name: "answer", Type: field.TypeString, Size: 2147483647},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "category_faqs", Type: field.TypeInt, Nullable: true},
	}
	// FAQFaqTable holds the schema information for the "FAQ_faq" table.
	FAQFaqTable = &schema.Table{
		Name:       "FAQ_faq",
		Columns:    FAQFaqColumns,
		PrimaryKey: []*schema.Column{FAQFaqColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "FAQ_faq_Category_category_faqs",
				Columns:    []*schema.Column{FAQFaqColumns[7]},
				RefColumns: []*schema.Column{CategoryCategoryColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LessonLessonColumns holds the columns for the "Lesson_lesson" table.
	LessonLessonColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "slug", Type: field.TypeString, Size: 250},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "video_url", Type: field.TypeString, Nullable: true},
		{Name: "order", Type: field.TypeInt},
		{Name: "is_preview", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "course_lessons", Type: field.TypeInt},
	}
	// LessonLessonTable holds the schema information for the "Lesson_lesson" table.
	LessonLessonTable = &schema.Table{
		Name:       "Lesson_lesson",
		Columns:    LessonLessonColumns,
		PrimaryKey: []*schema.Column{LessonLessonColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Lesson_lesson_courses_course_lessons",
				Columns:    []*schema.Column{LessonLessonColumns[9]},
				RefColumns: []*schema.Column{CoursesCourseColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PasswordTokensColumns holds the columns for the "password_tokens" table.
	PasswordTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// PasswordTokensTable holds the schema information for the "password_tokens" table.
	PasswordTokensTable = &schema.Table{
		Name:       "password_tokens",
		Columns:    PasswordTokensColumns,
		PrimaryKey: []*schema.Column{PasswordTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "password_tokens_Account_customuser_user",
				Columns:    []*schema.Column{PasswordTokensColumns[3]},
				RefColumns: []*schema.Column{AccountCustomuserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// QuestionQuestionColumns holds the columns for the "Question_question" table.
	QuestionQuestionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "question_text", Type: field.TypeString, Size: 2147483647},
		{Name: "question_type", Type: field.TypeString, Default: "mcq"},
		{Name: "order", Type: field.TypeInt, Default: 0},
		{Name: "quiz_questions", Type: field.TypeInt},
	}
	// QuestionQuestionTable holds the schema information for the "Question_question" table.
	QuestionQuestionTable = &schema.Table{
		Name:       "Question_question",
		Columns:    QuestionQuestionColumns,
		PrimaryKey: []*schema.Column{QuestionQuestionColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Question_question_Quiz_quiz_questions",
				Columns:    []*schema.Column{QuestionQuestionColumns[4]},
				RefColumns: []*schema.Column{QuizQuizColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// QuizQuizColumns holds the columns for the "Quiz_quiz" table.
	QuizQuizColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "passing_score", Type: field.TypeInt, Default: 70},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "lesson_quizzes", Type: field.TypeInt},
	}
	// QuizQuizTable holds the schema information for the "Quiz_quiz" table.
	QuizQuizTable = &schema.Table{
		Name:       "Quiz_quiz",
		Columns:    QuizQuizColumns,
		PrimaryKey: []*schema.Column{QuizQuizColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Quiz_quiz_Lesson_lesson_quizzes",
				Columns:    []*schema.Column{QuizQuizColumns[6]},
				RefColumns: []*schema.Column{LessonLessonColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ReviewReviewColumns holds the columns for the "Review_review" table.
	ReviewReviewColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "rating", Type: field.TypeInt},
		{Name: "comment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "is_approved", Type: field.TypeBool, Default: false},
		{Name: "course_reviews", Type: field.TypeInt},
		{Name: "user_reviews_given", Type: field.TypeInt},
	}
	// ReviewReviewTable holds the schema information for the "Review_review" table.
	ReviewReviewTable = &schema.Table{
		Name:       "Review_review",
		Columns:    ReviewReviewColumns,
		PrimaryKey: []*schema.Column{ReviewReviewColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Review_review_courses_course_reviews",
				Columns:    []*schema.Column{ReviewReviewColumns[5]},
				RefColumns: []*schema.Column{CoursesCourseColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "Review_review_Account_customuser_reviews_given",
				Columns:    []*schema.Column{ReviewReviewColumns[6]},
				RefColumns: []*schema.Column{AccountCustomuserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AccountCustomuserColumns holds the columns for the "Account_customuser" table.
	AccountCustomuserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "first_name", Type: field.TypeString, Nullable: true},
		{Name: "last_name", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "student"},
		{Name: "bio", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "profile_picture", Type: field.TypeString, Nullable: true},
		{Name: "date_of_birth", Type: field.TypeTime, Nullable: true},
		{Name: "gender", Type: field.TypeString, Nullable: true},
		{Name: "contact_number", Type: field.TypeString, Nullable: true},
		{Name: "address", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "country", Type: field.TypeString, Nullable: true},
		{Name: "is_email_verified", Type: field.TypeBool, Default: false},
		{Name: "highest_qualification", Type: field.TypeString, Nullable: true},
		{Name: "institution", Type: field.TypeString, Nullable: true},
		{Name: "skills", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "linkedin_profile", Type: field.TypeString, Nullable: true},
		{Name: "github_profile", Type: field.TypeString, Nullable: true},
		{Name: "instructor_rating", Type: field.TypeFloat64, Default: 0},
		{Name: "total_reviews", Type: field.TypeInt, Default: 0},
		{Name: "is_active_user", Type: field.TypeBool, Default: true},
		{Name: "last_activity", Type: field.TypeTime, Nullable: true},
		{Name: "login_ip", Type: field.TypeString, Nullable: true},
		{Name: "two_factor_enabled", Type: field.TypeBool, Default: false},
		{Name: "is_staff", Type: field.TypeBool, Default: false},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_superuser", Type: field.TypeBool, Default: false},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
		{Name: "date_joined", Type: field.TypeTime},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "admin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AccountCustomuserTable holds the schema information for the "Account_customuser" table.
	AccountCustomuserTable = &schema.Table{
		Name:       "Account_customuser",
		Columns:    AccountCustomuserColumns,
		PrimaryKey: []*schema.Column{AccountCustomuserColumns[0]},
	}
	// QuizUserquizattemptColumns holds the columns for the "Quiz_userquizattempt" table.
	QuizUserquizattemptColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "score", Type: field.TypeFloat64, Default: 0},
		{Name: "passed", Type: field.TypeBool, Default: false},
		{Name: "attempt_number", Type: field.TypeInt, Default: 1},
		{Name: "submitted_at", Type: field.TypeTime},
		{Name: "quiz_attempts", Type: field.TypeInt},
		{Name: "user_quiz_attempts", Type: field.TypeInt},
	}
	// QuizUserquizattemptTable holds the schema information for the "Quiz_userquizattempt" table.
	QuizUserquizattemptTable = &schema.Table{
		Name:       "Quiz_userquizattempt",
		Columns:    QuizUserquizattemptColumns,
		PrimaryKey: []*schema.Column{QuizUserquizattemptColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Quiz_userquizattempt_Quiz_quiz_attempts",
				Columns:    []*schema.Column{QuizUserquizattemptColumns[5]},
				RefColumns: []*schema.Column{QuizQuizColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "Quiz_userquizattempt_Account_customuser_quiz_attempts",
				Columns:    []*schema.Column{QuizUserquizattemptColumns[6]},
				RefColumns: []*schema.Column{AccountCustomuserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UserEnrolledCoursesColumns holds the columns for the "user_enrolled_courses" table.
	UserEnrolledCoursesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "course_id", Type: field.TypeInt},
	}
	// UserEnrolledCoursesTable holds the schema information for the "user_enrolled_courses" table.
	UserEnrolledCoursesTable = &schema.Table{
		Name:       "user_enrolled_courses",
		Columns:    UserEnrolledCoursesColumns,
		PrimaryKey: []*schema.Column{UserEnrolledCoursesColumns[0], UserEnrolledCoursesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_enrolled_courses_user_id",
				Columns:    []*schema.Column{UserEnrolledCoursesColumns[0]},
				RefColumns: []*schema.Column{AccountCustomuserColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_enrolled_courses_course_id",
				Columns:    []*schema.Column{UserEnrolledCoursesColumns[1]},
				RefColumns: []*schema.Column{CoursesCourseColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserCompletedCoursesColumns holds the columns for the "user_completed_courses" table.
	UserCompletedCoursesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "course_id", Type: field.TypeInt},
	}
	// UserCompletedCoursesTable holds the schema information for the "user_completed_courses" table.
	UserCompletedCoursesTable = &schema.Table{
		Name:       "user_completed_courses",
		Columns:    UserCompletedCoursesColumns,
		PrimaryKey: []*schema.Column{UserCompletedCoursesColumns[0], UserCompletedCoursesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_completed_courses_user_id",
				Columns:    []*schema.Column{UserCompletedCoursesColumns[0]},
				RefColumns: []*schema.Column{AccountCustomuserColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_completed_courses_course_id",
				Columns:    []*schema.Column{UserCompletedCoursesColumns[1]},
				RefColumns: []*schema.Column{CoursesCourseColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		QuestionAnswerchoiceTable,
		CategoryCategoryTable,
		CertificateCertificateTable,
		CoursesCourseTable,
		EnrollmentEnrollmentTable,
		FAQFaqTable,
		LessonLessonTable,
		PasswordTokensTable,
		QuestionQuestionTable,
		QuizQuizTable,
		ReviewReviewTable,
		AccountCustomuserTable,
		QuizUserquizattemptTable,
		UserEnrolledCoursesTable,
		UserCompletedCoursesTable,
	}
)

func init() {
	QuestionAnswerchoiceTable.ForeignKeys[0].RefTable = QuestionQuestionTable
	QuestionAnswerchoiceTable.Annotation = &entsql.Annotation{
		Table: "Question_answerchoice",
	}
	CategoryCategoryTable.Annotation = &entsql.Annotation{
		Table: "Category_category",
	}
	CertificateCertificateTable.ForeignKeys[0].RefTable = EnrollmentEnrollmentTable
	CertificateCertificateTable.Annotation = &entsql.Annotation{
		Table: "Certificate_certificate",
	}
	CoursesCourseTable.ForeignKeys[0].RefTable = CategoryCategoryTable
	CoursesCourseTable.ForeignKeys[1].RefTable = AccountCustomuserTable
	CoursesCourseTable.Annotation = &entsql.Annotation{
		Table: "courses_course",
	}
	EnrollmentEnrollmentTable.ForeignKeys[0].RefTable = CoursesCourseTable
	EnrollmentEnrollmentTable.ForeignKeys[1].RefTable = AccountCustomuserTable
	EnrollmentEnrollmentTable.Annotation = &entsql.Annotation{
		Table: "Enrollment_enrollment",
	}
	FAQFaqTable.ForeignKeys[0].RefTable = CategoryCategoryTable
	FAQFaqTable.Annotation = &entsql.Annotation{
		Table: "FAQ_faq",
	}
	LessonLessonTable.ForeignKeys[0].RefTable = CoursesCourseTable
	LessonLessonTable.Annotation = &entsql.Annotation{
		Table: "Lesson_lesson",
	}
	PasswordTokensTable.ForeignKeys[0].RefTable = AccountCustomuserTable
	QuestionQuestionTable.ForeignKeys[0].RefTable = QuizQuizTable
	QuestionQuestionTable.Annotation = &entsql.Annotation{
		Table: "Question_question",
	}
	QuizQuizTable.ForeignKeys[0].RefTable = LessonLessonTable
	QuizQuizTable.Annotation = &entsql.Annotation{
		Table: "Quiz_quiz",
	}
	ReviewReviewTable.ForeignKeys[0].RefTable = CoursesCourseTable
	ReviewReviewTable.ForeignKeys[1].RefTable = AccountCustomuserTable
	ReviewReviewTable.Annotation = &entsql.Annotation{
		Table: "Review_review",
	}
	AccountCustomuserTable.Annotation = &entsql.Annotation{
		Table: "Account_customuser",
	}
	QuizUserquizattemptTable.ForeignKeys[0].RefTable = QuizQuizTable
	QuizUserquizattemptTable.ForeignKeys[1].RefTable = AccountCustomuserTable
	QuizUserquizattemptTable.Annotation = &entsql.Annotation{
		Table: "Quiz_userquizattempt",
	}
	UserEnrolledCoursesTable.ForeignKeys[0].RefTable = AccountCustomuserTable
	UserEnrolledCoursesTable.ForeignKeys[1].RefTable = CoursesCourseTable
	UserCompletedCoursesTable.ForeignKeys[0].RefTable = AccountCustomuserTable
	UserCompletedCoursesTable.ForeignKeys[1].RefTable = CoursesCourseTable
}
