// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/SHP-Association/E-learningWeb/backend/ent/answerchoice"
	"github.com/SHP-Association/E-learningWeb/backend/ent/category"
	"github.com/SHP-Association/E-learningWeb/backend/ent/certificate"
	"github.com/SHP-Association/E-learningWeb/backend/ent/course"
	"github.com/SHP-Association/E-learningWeb/backend/ent/enrollment"
	"github.com/SHP-Association/E-learningWeb/backend/ent/faq"
	"github.com/SHP-Association/E-learningWeb/backend/ent/lesson"
	"github.com/SHP-Association/E-learningWeb/backend/ent/passwordtoken"
	"github.com/SHP-Association/E-learningWeb/backend/ent/question"
	"github.com/SHP-Association/E-learningWeb/backend/ent/quiz"
	"github.com/SHP-Association/E-learningWeb/backend/ent/review"
	"github.com/SHP-Association/E-learningWeb/backend/ent/schema"
	"github.com/SHP-Association/E-learningWeb/backend/ent/user"
	"github.com/SHP-Association/E-learningWeb/backend/ent/userquizattempt"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	answerchoiceFields := schema.AnswerChoice{}.Fields()
	_ = answerchoiceFields
	// answerchoiceDescChoiceText is the schema descriptor for choice_text field.
	answerchoiceDescChoiceText := answerchoiceFields[1].Descriptor()
	// answerchoice.ChoiceTextValidator is a validator for the "choice_text" field. It is called by the builders before save.
	answerchoice.ChoiceTextValidator = answerchoiceDescChoiceText.Validators[0].(func(string) error)
	// answerchoiceDescIsCorrect is the schema descriptor for is_correct field.
	answerchoiceDescIsCorrect := answerchoiceFields[2].Descriptor()
	// answerchoice.DefaultIsCorrect holds the default value on creation for the is_correct field.
	answerchoice.DefaultIsCorrect = answerchoiceDescIsCorrect.Default.(bool)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescSlug is the schema descriptor for slug field.
	categoryDescSlug := categoryFields[2].Descriptor()
	// category.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	category.SlugValidator = categoryDescSlug.Validators[0].(func(string) error)
	certificateFields := schema.Certificate{}.Fields()
	_ = certificateFields
	// certificateDescIssueDate is the schema descriptor for issue_date field.
	certificateDescIssueDate := certificateFields[2].Descriptor()
	// certificate.DefaultIssueDate holds the default value on creation for the issue_date field.
	certificate.DefaultIssueDate = certificateDescIssueDate.Default.(func() time.Time)
	courseFields := schema.Course{}.Fields()
	_ = courseFields
	// courseDescTitle is the schema descriptor for title field.
	courseDescTitle := courseFields[1].Descriptor()
	// course.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	course.TitleValidator = courseDescTitle.Validators[0].(func(string) error)
	// courseDescSlug is the schema descriptor for slug field.
	courseDescSlug := courseFields[2].Descriptor()
	// course.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	course.SlugValidator = courseDescSlug.Validators[0].(func(string) error)
	// courseDescShortDescription is the schema descriptor for short_description field.
	courseDescShortDescription := courseFields[3].Descriptor()
	// course.ShortDescriptionValidator is a validator for the "short_description" field. It is called by the builders before save.
	course.ShortDescriptionValidator = courseDescShortDescription.Validators[0].(func(string) error)
	// courseDescPrice is the schema descriptor for price field.
	courseDescPrice := courseFields[10].Descriptor()
	// course.DefaultPrice holds the default value on creation for the price field.
	course.DefaultPrice = courseDescPrice.Default.(float64)
	// courseDescIsFree is the schema descriptor for is_free field.
	courseDescIsFree := courseFields[11].Descriptor()
	// course.DefaultIsFree holds the default value on creation for the is_free field.
	course.DefaultIsFree = courseDescIsFree.Default.(bool)
	// courseDescIsPublished is the schema descriptor for is_published field.
	courseDescIsPublished := courseFields[12].Descriptor()
	// course.DefaultIsPublished holds the default value on creation for the is_published field.
	course.DefaultIsPublished = courseDescIsPublished.Default.(bool)
	// courseDescLevel is the schema descriptor for level field.
	courseDescLevel := courseFields[13].Descriptor()
	// course.DefaultLevel holds the default value on creation for the level field.
	course.DefaultLevel = courseDescLevel.Default.(string)
	// courseDescTotalLectures is the schema descriptor for total_lectures field.
	courseDescTotalLectures := courseFields[15].Descriptor()
	// course.DefaultTotalLectures holds the default value on creation for the total_lectures field.
	course.DefaultTotalLectures = courseDescTotalLectures.Default.(int)
	// courseDescAverageRating is the schema descriptor for average_rating field.
	courseDescAverageRating := courseFields[16].Descriptor()
	// course.DefaultAverageRating holds the default value on creation for the average_rating field.
	course.DefaultAverageRating = courseDescAverageRating.Default.(float64)
	// courseDescNumberOfReviews is the schema descriptor for number_of_reviews field.
	courseDescNumberOfReviews := courseFields[17].Descriptor()
	// course.DefaultNumberOfReviews holds the default value on creation for the number_of_reviews field.
	course.DefaultNumberOfReviews = courseDescNumberOfReviews.Default.(int)
	// courseDescCreatedAt is the schema descriptor for created_at field.
	courseDescCreatedAt := courseFields[18].Descriptor()
	// course.DefaultCreatedAt holds the default value on creation for the created_at field.
	course.DefaultCreatedAt = courseDescCreatedAt.Default.(func() time.Time)
	// courseDescUpdatedAt is the schema descriptor for updated_at field.
	courseDescUpdatedAt := courseFields[19].Descriptor()
	// course.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	course.DefaultUpdatedAt = courseDescUpdatedAt.Default.(func() time.Time)
	// course.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	course.UpdateDefaultUpdatedAt = courseDescUpdatedAt.UpdateDefault.(func() time.Time)
	enrollmentFields := schema.Enrollment{}.Fields()
	_ = enrollmentFields
	// enrollmentDescEnrolledAt is the schema descriptor for enrolled_at field.
	enrollmentDescEnrolledAt := enrollmentFields[1].Descriptor()
	// enrollment.DefaultEnrolledAt holds the default value on creation for the enrolled_at field.
	enrollment.DefaultEnrolledAt = enrollmentDescEnrolledAt.Default.(func() time.Time)
	// enrollmentDescProgress is the schema descriptor for progress field.
	enrollmentDescProgress := enrollmentFields[3].Descriptor()
	// enrollment.DefaultProgress holds the default value on creation for the progress field.
	enrollment.DefaultProgress = enrollmentDescProgress.Default.(float64)
	// enrollmentDescIsCompleted is the schema descriptor for is_completed field.
	enrollmentDescIsCompleted := enrollmentFields[4].Descriptor()
	// enrollment.DefaultIsCompleted holds the default value on creation for the is_completed field.
	enrollment.DefaultIsCompleted = enrollmentDescIsCompleted.Default.(bool)
	faqFields := schema.FAQ{}.Fields()
	_ = faqFields
	// faqDescIsPublished is the schema descriptor for is_published field.
	faqDescIsPublished := faqFields[3].Descriptor()
	// faq.DefaultIsPublished holds the default value on creation for the is_published field.
	faq.DefaultIsPublished = faqDescIsPublished.Default.(bool)
	// faqDescOrder is the schema descriptor for order field.
	faqDescOrder := faqFields[4].Descriptor()
	// faq.DefaultOrder holds the default value on creation for the order field.
	faq.DefaultOrder = faqDescOrder.Default.(int)
	// faqDescCreatedAt is the schema descriptor for created_at field.
	faqDescCreatedAt := faqFields[5].Descriptor()
	// faq.DefaultCreatedAt holds the default value on creation for the created_at field.
	faq.DefaultCreatedAt = faqDescCreatedAt.Default.(func() time.Time)
	// faqDescUpdatedAt is the schema descriptor for updated_at field.
	faqDescUpdatedAt := faqFields[6].Descriptor()
	// faq.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	faq.DefaultUpdatedAt = faqDescUpdatedAt.Default.(func() time.Time)
	// faq.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	faq.UpdateDefaultUpdatedAt = faqDescUpdatedAt.UpdateDefault.(func() time.Time)
	lessonFields := schema.Lesson{}.Fields()
	_ = lessonFields
	// lessonDescTitle is the schema descriptor for title field.
	lessonDescTitle := lessonFields[1].Descriptor()
	// lesson.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	lesson.TitleValidator = lessonDescTitle.Validators[0].(func(string) error)
	// lessonDescSlug is the schema descriptor for slug field.
	lessonDescSlug := lessonFields[2].Descriptor()
	// lesson.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	lesson.SlugValidator = lessonDescSlug.Validators[0].(func(string) error)
	// lessonDescIsPreview is the schema descriptor for is_preview field.
	lessonDescIsPreview := lessonFields[6].Descriptor()
	// lesson.DefaultIsPreview holds the default value on creation for the is_preview field.
	lesson.DefaultIsPreview = lessonDescIsPreview.Default.(bool)
	// lessonDescCreatedAt is the schema descriptor for created_at field.
	lessonDescCreatedAt := lessonFields[7].Descriptor()
	// lesson.DefaultCreatedAt holds the default value on creation for the created_at field.
	lesson.DefaultCreatedAt = lessonDescCreatedAt.Default.(func() time.Time)
	// lessonDescUpdatedAt is the schema descriptor for updated_at field.
	lessonDescUpdatedAt := lessonFields[8].Descriptor()
	// lesson.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	lesson.DefaultUpdatedAt = lessonDescUpdatedAt.Default.(func() time.Time)
	// lesson.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	lesson.UpdateDefaultUpdatedAt = lessonDescUpdatedAt.UpdateDefault.(func() time.Time)
	passwordtokenHooks := schema.PasswordToken{}.Hooks()
	passwordtoken.Hooks[0] = passwordtokenHooks[0]
	passwordtokenFields := schema.PasswordToken{}.Fields()
	_ = passwordtokenFields
	// passwordtokenDescToken is the schema descriptor for token field.
	passwordtokenDescToken := passwordtokenFields[0].Descriptor()
	// passwordtoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	passwordtoken.TokenValidator = passwordtokenDescToken.Validators[0].(func(string) error)
	// passwordtokenDescCreatedAt is the schema descriptor for created_at field.
	passwordtokenDescCreatedAt := passwordtokenFields[2].Descriptor()
	// passwordtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordtoken.DefaultCreatedAt = passwordtokenDescCreatedAt.Default.(func() time.Time)
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescQuestionType is the schema descriptor for question_type field.
	questionDescQuestionType := questionFields[2].Descriptor()
	// question.DefaultQuestionType holds the default value on creation for the question_type field.
	question.DefaultQuestionType = questionDescQuestionType.Default.(string)
	// questionDescOrder is the schema descriptor for order field.
	questionDescOrder := questionFields[3].Descriptor()
	// question.DefaultOrder holds the default value on creation for the order field.
	question.DefaultOrder = questionDescOrder.Default.(int)
	quizFields := schema.Quiz{}.Fields()
	_ = quizFields
	// quizDescTitle is the schema descriptor for title field.
	quizDescTitle := quizFields[1].Descriptor()
	// quiz.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	quiz.TitleValidator = quizDescTitle.Validators[0].(func(string) error)
	// quizDescPassingScore is the schema descriptor for passing_score field.
	quizDescPassingScore := quizFields[3].Descriptor()
	// quiz.DefaultPassingScore holds the default value on creation for the passing_score field.
	quiz.DefaultPassingScore = quizDescPassingScore.Default.(int)
	// quizDescCreatedAt is the schema descriptor for created_at field.
	quizDescCreatedAt := quizFields[4].Descriptor()
	// quiz.DefaultCreatedAt holds the default value on creation for the created_at field.
	quiz.DefaultCreatedAt = quizDescCreatedAt.Default.(func() time.Time)
	// quizDescUpdatedAt is the schema descriptor for updated_at field.
	quizDescUpdatedAt := quizFields[5].Descriptor()
	// quiz.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	quiz.DefaultUpdatedAt = quizDescUpdatedAt.Default.(func() time.Time)
	// quiz.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	quiz.UpdateDefaultUpdatedAt = quizDescUpdatedAt.UpdateDefault.(func() time.Time)
	reviewFields := schema.Review{}.Fields()
	_ = reviewFields
	// reviewDescCreatedAt is the schema descriptor for created_at field.
	reviewDescCreatedAt := reviewFields[3].Descriptor()
	// review.DefaultCreatedAt holds the default value on creation for the created_at field.
	review.DefaultCreatedAt = reviewDescCreatedAt.Default.(func() time.Time)
	// reviewDescIsApproved is the schema descriptor for is_approved field.
	reviewDescIsApproved := reviewFields[4].Descriptor()
	// review.DefaultIsApproved holds the default value on creation for the is_approved field.
	review.DefaultIsApproved = reviewDescIsApproved.Default.(bool)
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[5].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[6].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescIsEmailVerified is the schema descriptor for is_email_verified field.
	userDescIsEmailVerified := userFields[14].Descriptor()
	// user.DefaultIsEmailVerified holds the default value on creation for the is_email_verified field.
	user.DefaultIsEmailVerified = userDescIsEmailVerified.Default.(bool)
	// userDescInstructorRating is the schema descriptor for instructor_rating field.
	userDescInstructorRating := userFields[20].Descriptor()
	// user.DefaultInstructorRating holds the default value on creation for the instructor_rating field.
	user.DefaultInstructorRating = userDescInstructorRating.Default.(float64)
	// userDescTotalReviews is the schema descriptor for total_reviews field.
	userDescTotalReviews := userFields[21].Descriptor()
	// user.DefaultTotalReviews holds the default value on creation for the total_reviews field.
	user.DefaultTotalReviews = userDescTotalReviews.Default.(int)
	// userDescIsActiveUser is the schema descriptor for is_active_user field.
	userDescIsActiveUser := userFields[22].Descriptor()
	// user.DefaultIsActiveUser holds the default value on creation for the is_active_user field.
	user.DefaultIsActiveUser = userDescIsActiveUser.Default.(bool)
	// userDescTwoFactorEnabled is the schema descriptor for two_factor_enabled field.
	userDescTwoFactorEnabled := userFields[25].Descriptor()
	// user.DefaultTwoFactorEnabled holds the default value on creation for the two_factor_enabled field.
	user.DefaultTwoFactorEnabled = userDescTwoFactorEnabled.Default.(bool)
	// userDescIsStaff is the schema descriptor for is_staff field.
	userDescIsStaff := userFields[26].Descriptor()
	// user.DefaultIsStaff holds the default value on creation for the is_staff field.
	user.DefaultIsStaff = userDescIsStaff.Default.(bool)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[27].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescIsSuperuser is the schema descriptor for is_superuser field.
	userDescIsSuperuser := userFields[28].Descriptor()
	// user.DefaultIsSuperuser holds the default value on creation for the is_superuser field.
	user.DefaultIsSuperuser = userDescIsSuperuser.Default.(bool)
	// userDescDateJoined is the schema descriptor for date_joined field.
	userDescDateJoined := userFields[30].Descriptor()
	// user.DefaultDateJoined holds the default value on creation for the date_joined field.
	user.DefaultDateJoined = userDescDateJoined.Default.(func() time.Time)
	// userDescVerified is the schema descriptor for verified field.
	userDescVerified := userFields[31].Descriptor()
	// user.DefaultVerified holds the default value on creation for the verified field.
	user.DefaultVerified = userDescVerified.Default.(bool)
	// userDescAdmin is the schema descriptor for admin field.
	userDescAdmin := userFields[32].Descriptor()
	// user.DefaultAdmin holds the default value on creation for the admin field.
	user.DefaultAdmin = userDescAdmin.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[33].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	userquizattemptFields := schema.UserQuizAttempt{}.Fields()
	_ = userquizattemptFields
	// userquizattemptDescScore is the schema descriptor for score field.
	userquizattemptDescScore := userquizattemptFields[1].Descriptor()
	// userquizattempt.DefaultScore holds the default value on creation for the score field.
	userquizattempt.DefaultScore = userquizattemptDescScore.Default.(float64)
	// userquizattemptDescPassed is the schema descriptor for passed field.
	userquizattemptDescPassed := userquizattemptFields[2].Descriptor()
	// userquizattempt.DefaultPassed holds the default value on creation for the passed field.
	userquizattempt.DefaultPassed = userquizattemptDescPassed.Default.(bool)
	// userquizattemptDescAttemptNumber is the schema descriptor for attempt_number field.
	userquizattemptDescAttemptNumber := userquizattemptFields[3].Descriptor()
	// userquizattempt.DefaultAttemptNumber holds the default value on creation for the attempt_number field.
	userquizattempt.DefaultAttemptNumber = userquizattemptDescAttemptNumber.Default.(int)
	// userquizattemptDescSubmittedAt is the schema descriptor for submitted_at field.
	userquizattemptDescSubmittedAt := userquizattemptFields[4].Descriptor()
	// userquizattempt.DefaultSubmittedAt holds the default value on creation for the submitted_at field.
	userquizattempt.DefaultSubmittedAt = userquizattemptDescSubmittedAt.Default.(func() time.Time)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
