// Code generated by ent, DO NOT EDIT.

package certificate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the certificate type in the database.
	Label = "certificate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUniqueID holds the string denoting the unique_id field in the database.
	FieldUniqueID = "unique_id"
	// FieldIssueDate holds the string denoting the issue_date field in the database.
	FieldIssueDate = "issue_date"
	// EdgeEnrollment holds the string denoting the enrollment edge name in mutations.
	EdgeEnrollment = "enrollment"
	// Table holds the table name of the certificate in the database.
	Table = "Certificate_certificate"
	// EnrollmentTable is the table that holds the enrollment relation/edge.
	EnrollmentTable = "Certificate_certificate"
	// EnrollmentInverseTable is the table name for the Enrollment entity.
	// It exists in this package in order to avoid circular dependency with the "enrollment" package.
	EnrollmentInverseTable = "Enrollment_enrollment"
	// EnrollmentColumn is the table column denoting the enrollment relation/edge.
	EnrollmentColumn = "enrollment_certificate"
)

// Columns holds all SQL columns for certificate fields.
var Columns = []string{
	FieldID,
	FieldUniqueID,
	FieldIssueDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "Certificate_certificate"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"enrollment_certificate",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIssueDate holds the default value on creation for the "issue_date" field.
	DefaultIssueDate func() time.Time
)

// OrderOption defines the ordering options for the Certificate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUniqueID orders the results by the unique_id field.
func ByUniqueID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUniqueID, opts...).ToFunc()
}

// ByIssueDate orders the results by the issue_date field.
func ByIssueDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssueDate, opts...).ToFunc()
}

// ByEnrollmentField orders the results by enrollment field.
func ByEnrollmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnrollmentStep(), sql.OrderByField(field, opts...))
	}
}
func newEnrollmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnrollmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, EnrollmentTable, EnrollmentColumn),
	)
}
