// Code generated by ent, DO NOT EDIT.

package certificate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SHP-Association/E-learningWeb/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldID, id))
}

// UniqueID applies equality check predicate on the "unique_id" field. It's identical to UniqueIDEQ.
func UniqueID(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUniqueID, v))
}

// IssueDate applies equality check predicate on the "issue_date" field. It's identical to IssueDateEQ.
func IssueDate(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIssueDate, v))
}

// UniqueIDEQ applies the EQ predicate on the "unique_id" field.
func UniqueIDEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUniqueID, v))
}

// UniqueIDNEQ applies the NEQ predicate on the "unique_id" field.
func UniqueIDNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldUniqueID, v))
}

// UniqueIDIn applies the In predicate on the "unique_id" field.
func UniqueIDIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldUniqueID, vs...))
}

// UniqueIDNotIn applies the NotIn predicate on the "unique_id" field.
func UniqueIDNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldUniqueID, vs...))
}

// UniqueIDGT applies the GT predicate on the "unique_id" field.
func UniqueIDGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldUniqueID, v))
}

// UniqueIDGTE applies the GTE predicate on the "unique_id" field.
func UniqueIDGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldUniqueID, v))
}

// UniqueIDLT applies the LT predicate on the "unique_id" field.
func UniqueIDLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldUniqueID, v))
}

// UniqueIDLTE applies the LTE predicate on the "unique_id" field.
func UniqueIDLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldUniqueID, v))
}

// UniqueIDContains applies the Contains predicate on the "unique_id" field.
func UniqueIDContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldUniqueID, v))
}

// UniqueIDHasPrefix applies the HasPrefix predicate on the "unique_id" field.
func UniqueIDHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldUniqueID, v))
}

// UniqueIDHasSuffix applies the HasSuffix predicate on the "unique_id" field.
func UniqueIDHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldUniqueID, v))
}

// UniqueIDEqualFold applies the EqualFold predicate on the "unique_id" field.
func UniqueIDEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldUniqueID, v))
}

// UniqueIDContainsFold applies the ContainsFold predicate on the "unique_id" field.
func UniqueIDContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldUniqueID, v))
}

// IssueDateEQ applies the EQ predicate on the "issue_date" field.
func IssueDateEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIssueDate, v))
}

// IssueDateNEQ applies the NEQ predicate on the "issue_date" field.
func IssueDateNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldIssueDate, v))
}

// IssueDateIn applies the In predicate on the "issue_date" field.
func IssueDateIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldIssueDate, vs...))
}

// IssueDateNotIn applies the NotIn predicate on the "issue_date" field.
func IssueDateNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldIssueDate, vs...))
}

// IssueDateGT applies the GT predicate on the "issue_date" field.
func IssueDateGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldIssueDate, v))
}

// IssueDateGTE applies the GTE predicate on the "issue_date" field.
func IssueDateGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldIssueDate, v))
}

// IssueDateLT applies the LT predicate on the "issue_date" field.
func IssueDateLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldIssueDate, v))
}

// IssueDateLTE applies the LTE predicate on the "issue_date" field.
func IssueDateLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldIssueDate, v))
}

// HasEnrollment applies the HasEdge predicate on the "enrollment" edge.
func HasEnrollment() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, EnrollmentTable, EnrollmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnrollmentWith applies the HasEdge predicate on the "enrollment" edge with a given conditions (other predicates).
func HasEnrollmentWith(preds ...predicate.Enrollment) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newEnrollmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.NotPredicates(p))
}
