# Generated by Django 4.2.11 on 2026-04-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
